### ISSUE TITLE
Uncaught TypeError: get_class() expects parameter 1 to be object, string given in vendor/nunomaduro/larastan/src/ReturnTypes/ContainerArrayAccessDynamicMethodReturnTypeExtension.php:64

### ISSUE THREAD

**Issue by mfn** [nunomaduro/larastan#1019]
- Larastan Version: 1.0.1
- `--level` used:2
- Pull request with failing test:

### Description
After upgrading to 1.0.1, I see this error:
```
+ $ time composer phpstan-tests -- --debug
> Composer\Config::disableProcessTimeout
> @php vendor/bin/phpstan analyse --configuration=phpstan-tests.neon tests '--debug'
[lots of files processed correctly]
…/tests/TestWhichIsFailing.php
Uncaught TypeError: get_class() expects parameter 1 to be object, string given in project/vendor/nunomaduro/larastan/src/ReturnTypes/ContainerArrayAccessDynamicMethodReturnTypeExtension.php:64
#0 project/vendor/nunomaduro/larastan/src/ReturnTypes/ContainerArrayAccessDynamicMethodReturnTypeExtension.php(64): get_class('/Users/neo/src/...')
#1 phar://project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(3335): NunoMaduro\Larastan\ReturnTypes\ContainerArrayAccessDynamicMethodReturnTypeExtension->getTypeFromMethodCall(Object(PHPStan\Reflection\ResolvedMethodReflection), Object(PhpParser\Node\Expr\MethodCall), Object(PHPStan\Analyser\MutatingScope))
#2 phar://project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1531): PHPStan\Analyser\MutatingScope->methodCallReturnType(Object(PHPStan\Type\ObjectType), 'offsetGet', Object(PhpParser\Node\Expr\MethodCall))
#3 phar://project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1537): PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}()
#4 phar://project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(445): PHPStan\Analyser\MutatingScope->resolveType(Object(PhpParser\Node\Expr\MethodCall))
#5 phar://project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1720): PHPStan\Analyser\MutatingScope->getType(Object(PhpParser\Node\Expr\MethodCall))
#6 phar://project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1527): PHPStan\Analyser\MutatingScope->getTypeFromArrayDimFetch(Object(PhpParser\Node\Expr\ArrayDimFetch), Object(PHPStan\Type\Constant\ConstantStringType), Object(PHPStan\Type\ObjectType))
#7 phar://project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(445): PHPStan\Analyser\MutatingScope->resolveType(Object(PhpParser\Node\Expr\ArrayDimFetch))
#8 phar://project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(730): PHPStan\Analyser\MutatingScope->getType(Object(PhpParser\Node\Expr\ArrayDimFetch))
#9 phar://project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(445): PHPStan\Analyser\MutatingScope->resolveType(Object(PhpParser\Node\Expr\BinaryOp\Concat))
#10 phar://project/vendor/phpstan/phpstan/phpstan.phar/src/Rules/Operators/InvalidBinaryOperationRule.php(37): PHPStan\Analyser\MutatingScope->getType(Object(PhpParser\Node\Expr\BinaryOp\Concat))
#11 phar://project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(77): PHPStan\Rules\Operators\InvalidBinaryOperationRule->processNode(Object(PhpParser\Node\Expr\BinaryOp\Concat), Object(PHPStan\Analyser\MutatingScope))
#12 phar://project/vendor/phpstan/phpstan/phpstan.phar/src/Node/ClassStatementsGatherer.php(91): PHPStan\Analyser\FileAnalyser->PHPStan\Analyser\{closure}(Object(PhpParser\Node\Expr\BinaryOp\Concat), Object(PHPStan\Analyser\MutatingScope))
#13 phar://project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(399): PHPStan\Node\ClassStatementsGatherer->__invoke(Object(PhpParser\Node\Expr\BinaryOp\Concat), Object(PHPStan\Analyser\MutatingScope))
#14 phar://project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(2236): PHPStan\Analyser\NodeScopeResolver::PHPStan\Analyser\{closure}(Object(PhpParser\Node\Expr\BinaryOp\Concat), Object(PHPStan\Analyser\MutatingScope))
#15 phar://project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1329): PHPStan\Analyser\NodeScopeResolver->callNodeCallbackWithExpression(Object(Closure), Object(PhpParser\Node\Expr\BinaryOp\Concat), Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Analyser\ExpressionContext))
#16 phar://project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(429): PHPStan\Analyser\NodeScopeResolver->processExprNode(Object(PhpParser\Node\Expr\BinaryOp\Concat), Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\ExpressionContext))
#17 phar://project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(249): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Return_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#18 phar://project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(414): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\ClassMethod), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#19 phar://project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(249): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\ClassMethod), Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer))
#20 phar://project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(2890): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Trait_), Array, Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer))
#21 phar://project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(2905): PHPStan\Analyser\NodeScopeResolver->processNodesForTraitUse(Object(PhpParser\Node\Stmt\Trait_), Object(PHPStan\Reflection\ClassReflection), Object(PHPStan\Analyser\MutatingScope), Array, Object(PHPStan\Node\ClassStatementsGatherer))
#22 phar://project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(2901): PHPStan\Analyser\NodeScopeResolver->processNodesForTraitUse(Array, Object(PHPStan\Reflection\ClassReflection), Object(PHPStan\Analyser\MutatingScope), Array, Object(PHPStan\Node\ClassStatementsGatherer))
#23 phar://project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(2905): PHPStan\Analyser\NodeScopeResolver->processNodesForTraitUse(Object(PhpParser\Node\Stmt\Namespace_), Object(PHPStan\Reflection\ClassReflection), Object(PHPStan\Analyser\MutatingScope), Array, Object(PHPStan\Node\ClassStatementsGatherer))
#24 phar://project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(2853): PHPStan\Analyser\NodeScopeResolver->processNodesForTraitUse(Array, Object(PHPStan\Reflection\ClassReflection), Object(PHPStan\Analyser\MutatingScope), Array, Object(PHPStan\Node\ClassStatementsGatherer))
#25 phar://project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(597): PHPStan\Analyser\NodeScopeResolver->processTraitUse(Object(PhpParser\Node\Stmt\TraitUse), Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer))
#26 phar://project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(249): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\TraitUse), Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer))
#27 phar://project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(498): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Class_), Array, Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer))
#28 phar://project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(249): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Class_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#29 phar://project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(464): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Namespace_), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#30 phar://project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(217): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Namespace_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#31 phar://project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(164): PHPStan\Analyser\NodeScopeResolver->processNodes(Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#32 phar://project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/Analyser.php(52): PHPStan\Analyser\FileAnalyser->analyseFile('/Users/neo/src/...', Array, Object(PHPStan\Rules\Registry), NULL)
#33 phar://project/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyserRunner.php(56): PHPStan\Analyser\Analyser->analyse(Array, Object(Closure), NULL, true, Array)
#34 phar://project/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseApplication.php(146): PHPStan\Command\AnalyserRunner->runAnalyser(Array, Array, Object(Closure), NULL, true, true, '/Users/neo/src/...', NULL, NULL, Object(_PHPStan_9b5387833\Symfony\Component\Console\Input\ArgvInput))
#35 phar://project/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseApplication.php(78): PHPStan\Command\AnalyseApplication->runAnalyser(Array, Array, true, '/Users/neo/src/...', Object(PHPStan\Command\Symfony\SymfonyOutput), Object(PHPStan\Command\Symfony\SymfonyOutput), Object(_PHPStan_9b5387833\Symfony\Component\Console\Input\ArgvInput))
#36 phar://project/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseCommand.php(144): PHPStan\Command\AnalyseApplication->analyse(Array, false, Object(PHPStan\Command\Symfony\SymfonyOutput), Object(PHPStan\Command\Symfony\SymfonyOutput), false, true, '/Users/neo/src/...', Array, Object(_PHPStan_9b5387833\Symfony\Component\Console\Input\ArgvInput))
#37 phar://project/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(228): PHPStan\Command\AnalyseCommand->execute(Object(_PHPStan_9b5387833\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_9b5387833\Symfony\Component\Console\Output\ConsoleOutput))
#38 phar://project/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(856): _PHPStan_9b5387833\Symfony\Component\Console\Command\Command->run(Object(_PHPStan_9b5387833\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_9b5387833\Symfony\Component\Console\Output\ConsoleOutput))
#39 phar://project/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(237): _PHPStan_9b5387833\Symfony\Component\Console\Application->doRunCommand(Object(PHPStan\Command\AnalyseCommand), Object(_PHPStan_9b5387833\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_9b5387833\Symfony\Component\Console\Output\ConsoleOutput))
#40 phar://project/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(138): _PHPStan_9b5387833\Symfony\Component\Console\Application->doRun(Object(_PHPStan_9b5387833\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_9b5387833\Symfony\Component\Console\Output\ConsoleOutput))
#41 phar://project/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(82): _PHPStan_9b5387833\Symfony\Component\Console\Application->run()
#42 phar://project/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(83): _PHPStan_9b5387833\{closure}()
#43 project/vendor/phpstan/phpstan/phpstan(8): require('phar:///Users/n...')
#44 {main}
Script @php vendor/bin/phpstan analyse --configuration=phpstan-tests.neon tests handling the phpstan-tests event returned with error code 1

real	0m27.990s
user	0m26.915s
sys	0m1.275s
```

### Laravel code where the issue was found
The particular code was using this pattern to access the base path
```php
return $this->app['base.path'] . '/some/app/path/;
```
I've never (or: don't remember) every seeing this before, but apparently it's a thing, see https://github.com/laravel/framework/blob/8e2d72728d6911816a97843ec3341e28c92af120/src/Illuminate/Foundation/Application.php#L305-L321
```php
    /**
     * Bind all of the application paths in the container.
     *
     * @return void
     */
    protected function bindPathsInContainer()
    {
        $this->instance('path', $this->path());
        $this->instance('path.base', $this->basePath());
        $this->instance('path.lang', $this->langPath());
        $this->instance('path.config', $this->configPath());
        $this->instance('path.public', $this->publicPath());
        $this->instance('path.storage', $this->storagePath());
        $this->instance('path.database', $this->databasePath());
        $this->instance('path.resources', $this->resourcePath());
        $this->instance('path.bootstrap', $this->bootstrapPath());
    }
```
Apparently there are things bound which are not instances 😬

### Workaround
The fix was easy for me: I just replaced with with:
```php
return $this->app->basePath() . '/some/app/path/;
```
and carried on.

But I thought you might want to know about this, as it did work with pre 1.0 release.

**Comment by szepeviktor** [comment]
> The fix was easy for me: I just replaced with with:
> 
> ```
> return $this->app->basePath() . '/some/app/path/;
> ```

Hello @mfn!
This is not a fix, this is the Laravel way :)

**Comment by szepeviktor** [comment]
`ContainerArrayAccessDynamicMethodReturnTypeExtension.php` is brand new.
@canvural may tell us more.

**Comment by szepeviktor** [comment]
> > The fix was easy for me: I just replaced with with:
> > ```
> > return $this->app->basePath() . '/some/app/path/;
> > ```
> 
> This is not a fix, this is the Laravel way :)

Actually I was wrong.
It is `$this->app->basePath('some/app/path/');`

https://github.com/laravel/framework/blob/545181da688db64fed6d8427e55f630a90ca0d32/src/Illuminate/Foundation/Application.php#L351-L360

**Comment by mfn** [comment]
@canvural thank you!
