### ISSUE TITLE
Internal error: Failed to retrieve the reflection object

### ISSUE THREAD

**Issue by misa-neopix** [nunomaduro/larastan#1024]
- Larastan Version: 1.0.1
- Laravel version: 8.68.1
- PHP version: 8.1.0RC4
- `--level` used: 5
- Pull request with failing test:

### Description

Larastan gets an internal error when analysing a controller that executes queries using some methods (e.g. `firstOrFail()` or `get()`). 

### Laravel code where the issue was found

Here's an example that fails:

```php
<?php

namespace App\Http\Controllers\Admin\Auth;

use App\Models\Admin;

class SetPasswordController
{
    public function edit(string $email)
    {
        /** @var \App\Models\Admin $admin */
        $admin = Admin::query()->where('email', $email)->firstOrFail();

        return view('admin.edit', compact('email'));
    }
}
```

But, if I change it to the following approach:

```php
<?php

namespace App\Http\Controllers\Admin\Auth;

use App\Models\Admin;

class SetPasswordController
{
    public function edit(string $email)
    {
        /** @var \App\Models\Admin|null $admin */
        $admin = Admin::query()->firstWhere(['email' => $email]);

        if ($admin === null) {
            abort(404);
        }

        return view('admin.edit', compact('email'));
    }
}
```

Everything works fine. 

Here's the stack trace generated by the `analyse --debug` command:

```
/var/www/html/app/Http/Controllers/Admin/Auth/SetPasswordController.php
Uncaught Error: Internal error: Failed to retrieve the reflection object in phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/Php/PhpMethodReflection.php:156
#0 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/Php/PhpMethodReflection.php(156): ReflectionClass->getTraitAliases()
#1 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/Php/PhpMethodReflection.php(290): PHPStan\Reflection\Php\PhpMethodReflection->getName()
#2 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/Php/PhpMethodReflection.php(187): PHPStan\Reflection\Php\PhpMethodReflection->getReturnType()
#3 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/Type/CalledOnTypeUnresolvedMethodPrototypeReflection.php(67): PHPStan\Reflection\Php\PhpMethodReflection->getVariants()
#4 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/Type/CalledOnTypeUnresolvedMethodPrototypeReflection.php(55): PHPStan\Reflection\Type\CalledOnTypeUnresolvedMethodPrototypeReflection->transformMethodWithStaticType()
#5 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Type/Generic/GenericObjectType.php(166): PHPStan\Reflection\Type\CalledOnTypeUnresolvedMethodPrototypeReflection->getTransformedMethod()
#6 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(3314): PHPStan\Type\Generic\GenericObjectType->getMethod()
#7 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(3324): PHPStan\Analyser\MutatingScope->getMethodReflection()
#8 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1531): PHPStan\Analyser\MutatingScope->methodCallReturnType()
#9 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1537): PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}()
#10 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(445): PHPStan\Analyser\MutatingScope->resolveType()
#11 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1531): PHPStan\Analyser\MutatingScope->getType()
#12 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1537): PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}()
#13 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(445): PHPStan\Analyser\MutatingScope->resolveType()
#14 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(701): PHPStan\Analyser\MutatingScope->getType()
#15 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(445): PHPStan\Analyser\MutatingScope->resolveType()
#16 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1314): PHPStan\Analyser\MutatingScope->getType()
#17 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(450): PHPStan\Analyser\NodeScopeResolver->findEarlyTerminatingExpr()
#18 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(249): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#19 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(414): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()
#20 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(249): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#21 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(498): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()
#22 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(249): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#23 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(464): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()
#24 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(217): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#25 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(164): PHPStan\Analyser\NodeScopeResolver->processNodes()
#26 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/Analyser.php(52): PHPStan\Analyser\FileAnalyser->analyseFile()
#27 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyserRunner.php(56): PHPStan\Analyser\Analyser->analyse()
#28 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseApplication.php(146): PHPStan\Command\AnalyserRunner->runAnalyser()
#29 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseApplication.php(78): PHPStan\Command\AnalyseApplication->runAnalyser()
#30 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseCommand.php(144): PHPStan\Command\AnalyseApplication->analyse()
#31 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(228): PHPStan\Command\AnalyseCommand->execute()
#32 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(856): _PHPStan_9b5387833\Symfony\Component\Console\Command\Command->run()
#33 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(237): _PHPStan_9b5387833\Symfony\Component\Console\Application->doRunCommand()
#34 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(138): _PHPStan_9b5387833\Symfony\Component\Console\Application->doRun()
#35 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(82): _PHPStan_9b5387833\Symfony\Component\Console\Application->run()
#36 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(83): _PHPStan_9b5387833\{closure}()
#37 /var/www/html/vendor/phpstan/phpstan/phpstan(8): require('...')
#38 {main}

```

**Comment by szepeviktor** [comment]
Thank you for your report Miša!

Please continue in https://github.com/phpstan/phpstan/issues/5954
