### ISSUE TITLE
AuthExtension cannot resolve AuthManager correctly

### ISSUE THREAD

**Issue by stemis** [nunomaduro/larastan#1071]
- Larastan Version: 1.0.2
- `--level` used: 1
- Pull request with failing test:

### Description

When running Rector PHP with larastan enabled I get an error on a class that uses `auth()->user()`

```
PHP Fatal error:  Uncaught TypeError: get_class(): Argument #1 ($object) must be of type object, null given in /app/vendor/nunomaduro/larastan/src/ReturnTypes/Helpers/AuthExtension.php:45
```

The exception occurs in `src/ReturnTypes/Helpers/AuthExtension.php`
```php
public function getTypeFromFunctionCall(
        FunctionReflection $functionReflection,
        FuncCall $functionCall,
        Scope $scope
    ): Type {
        if (count($functionCall->getArgs()) < 1) {
            /** @var object $class */
            $class = $this->resolve(\Illuminate\Contracts\Auth\Factory::class);

            return new ObjectType(get_class($class));
        }

        return TypeCombinator::intersect(new ObjectType(Guard::class), new ObjectType(StatefulGuard::class));
    }
```
`$class` is null when resolved.
When I run `$class = app(\Illuminate\Contracts\Auth\Factory::class);` in tinker, it resolves to `Illuminate\Auth\AuthManager` without issue

### Laravel code where the issue was found

```php
final class MyScopedExceptionHandler
{
    public static function createResponse(Throwable $e): ?Response
    {
        /** @var User $user */
        $user = auth()->user();
    }
}
```

Please let me know if you need any more details!

### StackTrace
<details><summary>Stack Trace</summary>

```
PHP Fatal error:  Uncaught TypeError: get_class(): Argument #1 ($object) must be of type object, null given in /app/vendor/nunomaduro/larastan/src/ReturnTypes/Helpers/AuthExtension.php:45
Stack trace:
#0 /app/vendor/nunomaduro/larastan/src/ReturnTypes/Helpers/AuthExtension.php(45): get_class(NULL)
#1 phar:///app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1683): NunoMaduro\Larastan\ReturnTypes\Helpers\AuthExtension->getTypeFromFunctionCall(Object(PHPStan\Reflection\Php\PhpFunctionReflection), Object(PhpParser\Node\Expr\FuncCall
), Object(PHPStan\Analyser\MutatingScope))
#2 phar:///app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(445): PHPStan\Analyser\MutatingScope->resolveType(Object(PhpParser\Node\Expr\FuncCall))
#3 phar:///app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1591): PHPStan\Analyser\MutatingScope->getType(Object(PhpParser\Node\Expr\FuncCall))
#4 phar:///app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1597): PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}()
#5 phar:///app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(445): PHPStan\Analyser\MutatingScope->resolveType(Object(PhpParser\Node\Expr\MethodCall))
#6 phar:///app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(701): PHPStan\Analyser\MutatingScope->getType(Object(PhpParser\Node\Expr\MethodCall))
#7 phar:///app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(445): PHPStan\Analyser\MutatingScope->resolveType(Object(PhpParser\Node\Expr\Assign))
#8 phar:///app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1318): PHPStan\Analyser\MutatingScope->getType(Object(PhpParser\Node\Expr\Assign))
#9 phar:///app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(454): PHPStan\Analyser\NodeScopeResolver->findEarlyTerminatingExpr(Object(PhpParser\Node\Expr\Assign), Object(PHPStan\Analyser\MutatingScope))
#10 phar:///app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(253): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Expression), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#11 phar:///app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(418): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\ClassMethod), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#12 phar:///app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(253): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\ClassMethod), Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatem
entsGatherer))
#13 phar:///app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(502): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Class_), Array, Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassSta
tementsGatherer))
#14 phar:///app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(253): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Class_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#15 phar:///app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(468): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Namespace_), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#16 phar:///app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(221): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Namespace_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#17 /app/vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php(152): PHPStan\Analyser\NodeScopeResolver->processNodes(Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#18 /app/vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php(144): Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->processNodesWithDependentFiles(Object(RectorPrefix20211221\Symplify\SmartFileSystem\SmartFileInfo), Array, Ob
ject(PHPStan\Analyser\MutatingScope), Object(Closure))
#19 /app/vendor/rector/rector/packages/NodeTypeResolver/NodeScopeAndMetadataDecorator.php(63): Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->processNodes(Array, Object(RectorPrefix20211221\Symplify\SmartFileSystem\SmartFileInfo))
#20 /app/vendor/rector/rector/src/Application/FileProcessor.php(49): Rector\NodeTypeResolver\NodeScopeAndMetadataDecorator->decorateNodesFromFile(Object(Rector\Core\ValueObject\Application\File), Array)
#21 /app/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(147): Rector\Core\Application\FileProcessor->parseFileInfoToLocalCache(Object(Rector\Core\ValueObject\Application\File))
#22 /app/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(85): Rector\Core\Application\FileProcessor\PhpFileProcessor->parseFileAndDecorateNodes(Object(Rector\Core\ValueObject\Application\File))
#23 /app/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(96): Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#24 /app/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(74): Rector\Core\Application\ApplicationFileProcessor->processFiles(Array, Object(Rector\Core\ValueObject\Configuration))
#25 /app/vendor/rector/rector/src/Console/Command/ProcessCommand.php(161): Rector\Core\Application\ApplicationFileProcessor->run(Array, Object(Rector\Core\ValueObject\Configuration))
#26 /app/vendor/rector/rector/vendor/symfony/console/Command/Command.php(282): Rector\Core\Console\Command\ProcessCommand->execute(Object(RectorPrefix20211221\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20211221\Symfony\Component\Console\Output\ConsoleOutput)
)
#27 /app/vendor/rector/rector/vendor/symfony/console/Application.php(853): RectorPrefix20211221\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix20211221\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20211221\Symfony\Component\Console\Output\Co
nsoleOutput))
#28 /app/vendor/rector/rector/vendor/symfony/console/Application.php(289): RectorPrefix20211221\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\ProcessCommand), Object(RectorPrefix20211221\Symfony\Component\Console\Input\ArgvInput), Object
(RectorPrefix20211221\Symfony\Component\Console\Output\ConsoleOutput))
#29 /app/vendor/rector/rector/src/Console/ConsoleApplication.php(67): RectorPrefix20211221\Symfony\Component\Console\Application->doRun(Object(RectorPrefix20211221\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20211221\Symfony\Component\Console\Output\ConsoleOu
tput))
#30 /app/vendor/rector/rector/vendor/symfony/console/Application.php(187): Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix20211221\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20211221\Symfony\Component\Console\Output\ConsoleOutput))
#31 /app/vendor/rector/rector/bin/rector.php(56): RectorPrefix20211221\Symfony\Component\Console\Application->run()
#32 /app/vendor/rector/rector/bin/rector(5): require_once('/app/vendor/rec...')
#33 /app/vendor/bin/rector(97): include('/app/vendor/rec...')
#34 {main}
  thrown in /app/vendor/nunomaduro/larastan/src/ReturnTypes/Helpers/AuthExtension.php on line 45
```
</details>

**Comment by szepeviktor** [comment]
Hello Steff! 👋 
Thank you for your report.

We have the very same line in our tests.
https://github.com/nunomaduro/larastan/blob/e8b02b21348333297f169af5c0095641975b4a54/tests/Features/ReturnTypes/Helpers/AuthExtension.php#L31

Are you working on a Laravel application or package?

**Comment by stemis** [comment]
Hi @szepeviktor !

Yes, I'm working on a large private Laravel application where this is occurring where we are running rector to go from PHP 7.4 to PHP 8.0.

When I disable larastan and just keep phpstan, rector succeeds, but with larastan enabled this error occurs.
We are running multiple auth guards in our application, and I haven't figured out yet why it doesn't resolve.
I can try narrowing it down further to provide a reproducible sample, but as you know these things take time to make :)
So I was hoping maybe you already knew what this could be.
If not, let me know and I will try to produce a test case

**Comment by szepeviktor** [comment]
> I can try narrowing it down further to provide a reproducible sample, but as you know these things take time to find & make with the complexity of my lara application :)

I see. Try exclude your auth guards from Rectorizing.

**Comment by canvural** [comment]
Hi,

Not sure what might cause this. But I added a `null` check for this: b3413dabec73db6291b07c322784061688d31e8d  Hope that'll solve it.
