### ISSUE TITLE
Call to undefined method IntersectionType::getClassReflection()

### ISSUE THREAD

**Issue by crynobone** [nunomaduro/larastan#1100]
- Larastan Version: `dev-master b7c2d7f`
- `--level` used: 6
- Pull request with failing test: 

### Description

![image](https://user-images.githubusercontent.com/172966/150619385-0e189005-a764-477b-a5fb-fa6cd4dfb602.png)

### Laravel code where the issue was found

Larastan or PHPStan doesn't provide any line where the issue occurred, only the filename.

```php
phpstan analyse --debug
// ... 

/Users/crynobone/Projects/laravel/nova/aries/src/Fields/HasOne.php
Uncaught Error: Call to undefined method PHPStan\Type\IntersectionType::getClassReflection() in /Users/crynobone/Projects/laravel/nova/aries/vendor/nunomaduro/larastan/src/ReturnTypes/CollectionGenericStaticMethodDynamicMethodReturnTypeExtension.php:64
#0 phar:///Users/crynobone/Projects/laravel/nova/aries/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(3609): NunoMaduro\Larastan\ReturnTypes\CollectionGenericStaticMethodDynamicMethodReturnTypeExtension->getTypeFromMethodCall(Object(PHPStan\Reflection\ResolvedMethodReflection), Object(PhpParser\Node\Expr\MethodCall), Object(PHPStan\Analyser\MutatingScope))
#1 phar:///Users/crynobone/Projects/laravel/nova/aries/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1701): PHPStan\Analyser\MutatingScope->methodCallReturnType(Object(PHPStan\Type\IntersectionType), 'map', Object(PhpParser\Node\Expr\MethodCall))
#2 phar:///Users/crynobone/Projects/laravel/nova/aries/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1707): PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}()
#3 phar:///Users/crynobone/Projects/laravel/nova/aries/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(533): PHPStan\Analyser\MutatingScope->resolveType(Object(PhpParser\Node\Expr\MethodCall))
#4 phar:///Users/crynobone/Projects/laravel/nova/aries/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(789): PHPStan\Analyser\MutatingScope->getType(Object(PhpParser\Node\Expr\MethodCall))
#5 phar:///Users/crynobone/Projects/laravel/nova/aries/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(533): PHPStan\Analyser\MutatingScope->resolveType(Object(PhpParser\Node\Expr\Assign))
#6 phar:///Users/crynobone/Projects/laravel/nova/aries/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1380): PHPStan\Analyser\MutatingScope->getType(Object(PhpParser\Node\Expr\Assign))
#7 phar:///Users/crynobone/Projects/laravel/nova/aries/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(496): PHPStan\Analyser\NodeScopeResolver->findEarlyTerminatingExpr(Object(PhpParser\Node\Expr\Assign), Object(PHPStan\Analyser\MutatingScope))
#8 phar:///Users/crynobone/Projects/laravel/nova/aries/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(298): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Expression), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#9 phar:///Users/crynobone/Projects/laravel/nova/aries/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(460): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\ClassMethod), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#10 phar:///Users/crynobone/Projects/laravel/nova/aries/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(298): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\ClassMethod), Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer))
#11 phar:///Users/crynobone/Projects/laravel/nova/aries/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(544): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Class_), Array, Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer))
#12 phar:///Users/crynobone/Projects/laravel/nova/aries/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(298): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Class_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#13 phar:///Users/crynobone/Projects/laravel/nova/aries/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(510): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Namespace_), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#14 phar:///Users/crynobone/Projects/laravel/nova/aries/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(269): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Namespace_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#15 phar:///Users/crynobone/Projects/laravel/nova/aries/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(181): PHPStan\Analyser\NodeScopeResolver->processNodes(Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#16 phar:///Users/crynobone/Projects/laravel/nova/aries/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/Analyser.php(69): PHPStan\Analyser\FileAnalyser->analyseFile('/Users/crynobon...', Array, Object(PHPStan\Rules\Registry), NULL)
#17 phar:///Users/crynobone/Projects/laravel/nova/aries/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyserRunner.php(62): PHPStan\Analyser\Analyser->analyse(Array, Object(Closure), NULL, true, Array)
#18 phar:///Users/crynobone/Projects/laravel/nova/aries/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseApplication.php(163): PHPStan\Command\AnalyserRunner->runAnalyser(Array, Array, Object(Closure), NULL, true, true, '/Users/crynobon...', NULL, NULL, Object(_PHPStan_1aef99d3c\Symfony\Component\Console\Input\ArgvInput))
#19 phar:///Users/crynobone/Projects/laravel/nova/aries/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseApplication.php(95): PHPStan\Command\AnalyseApplication->runAnalyser(Array, Array, true, '/Users/crynobon...', Object(PHPStan\Command\Symfony\SymfonyOutput), Object(PHPStan\Command\Symfony\SymfonyOutput), Object(_PHPStan_1aef99d3c\Symfony\Component\Console\Input\ArgvInput))
#20 phar:///Users/crynobone/Projects/laravel/nova/aries/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseCommand.php(175): PHPStan\Command\AnalyseApplication->analyse(Array, false, Object(PHPStan\Command\Symfony\SymfonyOutput), Object(PHPStan\Command\Symfony\SymfonyOutput), false, true, '/Users/crynobon...', Array, Object(_PHPStan_1aef99d3c\Symfony\Component\Console\Input\ArgvInput))
#21 phar:///Users/crynobone/Projects/laravel/nova/aries/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(259): PHPStan\Command\AnalyseCommand->execute(Object(_PHPStan_1aef99d3c\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_1aef99d3c\Symfony\Component\Console\Output\ConsoleOutput))
#22 phar:///Users/crynobone/Projects/laravel/nova/aries/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(848): _PHPStan_1aef99d3c\Symfony\Component\Console\Command\Command->run(Object(_PHPStan_1aef99d3c\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_1aef99d3c\Symfony\Component\Console\Output\ConsoleOutput))
#23 phar:///Users/crynobone/Projects/laravel/nova/aries/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(259): _PHPStan_1aef99d3c\Symfony\Component\Console\Application->doRunCommand(Object(PHPStan\Command\AnalyseCommand), Object(_PHPStan_1aef99d3c\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_1aef99d3c\Symfony\Component\Console\Output\ConsoleOutput))
#24 phar:///Users/crynobone/Projects/laravel/nova/aries/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(157): _PHPStan_1aef99d3c\Symfony\Component\Console\Application->doRun(Object(_PHPStan_1aef99d3c\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_1aef99d3c\Symfony\Component\Console\Output\ConsoleOutput))
#25 phar:///Users/crynobone/Projects/laravel/nova/aries/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(94): _PHPStan_1aef99d3c\Symfony\Component\Console\Application->run()
#26 phar:///Users/crynobone/Projects/laravel/nova/aries/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(95): _PHPStan_1aef99d3c\{closure}()
#27 /Users/crynobone/Projects/laravel/nova/aries/vendor/phpstan/phpstan/phpstan(8): require('phar:///Users/c...')
#28 {main}
```

**Comment by szepeviktor** [comment]
@crynobone Thank you for your report!

Could you insert `dd($methodReflection->getName());` at `vendor/nunomaduro/larastan/src/ReturnTypes/CollectionGenericStaticMethodDynamicMethodReturnTypeExtension.php:63`?
It will show what `Collection` method was analyzed.

**Comment by szepeviktor** [comment]
When you find that object use `\PHPStan\dumpType($thatObject);` to display the object's type.

**Comment by crynobone** [comment]
> When you find that object use \PHPStan\dumpType($thatObject); to display the object's type.

What is `$thatObject`? I got `method name:map`

```php
        try {
            $classReflection = $calledOnType->getClassReflection();
        } catch (\Throwable $e) {
            dd([
                'method name:' . $methodReflection->getName(),
                $calledOnType,
            ]);
        }

^ array:2 [
  0 => "method name:map"
  1 => PHPStan\Type\IntersectionType^ {#158289
    -types: array:2 [
      0 => PHPStan\Type\IterableType^ {#158293
        -keyType: PHPStan\Type\IntegerType^ {#98663}
        -itemType: PHPStan\Type\ObjectType^ {#158295
          -subtractedType: null
          -cachedParent: null
          -cachedInterfaces: null
          -currentAncestors: []
          -className: "Laravel\Nova\Fields\Field"
          -classReflection: null
        }
      }
      1 => PHPStan\Type\ObjectType^ {#158296
        -subtractedType: null
        -cachedParent: null
        -cachedInterfaces: null
        -currentAncestors: []
        -className: "Laravel\Nova\Fields\FieldCollection"
        -classReflection: null
      }
    ]
  }
]
```

**Comment by szepeviktor** [comment]
I see. So you are calling `map` on `Field|FieldCollection`.

**Comment by crynobone** [comment]
No, I don't think I can. The class itself contains 470 LOC, and it extends `Field` which has 871 LOC.

However doing the following solved the bug:

```php
        try {
            $classReflection = $calledOnType->getClassReflection();
        } catch (\Throwable $e) {
            return $returnType;
        }
```

Clearly the code expect `$calledOnType` to instance of `ObjectType` but we getting `PHPStan\Type\IntersectionType`

**Comment by canvural** [comment]
Hi,

This is really interesting. I really don't understand how an `IntersectionType` can be there.  Also intersection of `Field` and `FieldCollection` should result in `NeverType`  Interesting.

Anyway 919f0e8 should fix this.
