### ISSUE TITLE
Internal error: Method newCollection() was not found in reflection of class Illuminate\Database\Eloquent\Builder

### ISSUE THREAD

**Issue by nzsakib** [nunomaduro/larastan#1103]
- Larastan Version: 1.0
- `--level` used: 5

### Description
Ran in an existing project with huge controller. Not sure what's causing this error. 

### Laravel code where the issue was found

```php
#0 /home/user/blog/vendor/nunomaduro/larastan/src/Methods/BuilderHelper.php(221): PHPStan\Reflection\ClassReflection->getNativeMethod()
#1 /home/user/blog/vendor/nunomaduro/larastan/src/ReturnTypes/ModelFindExtension.php(88): NunoMaduro\Larastan\Methods\BuilderHelper->determineCollectionClassName()
#2 phar:///home/user/blog/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(3631): NunoMaduro\Larastan\ReturnTypes\ModelFindExtension->getTypeFromStaticMethodCall()
#3 phar:///home/user/blog/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1734): PHPStan\Analyser\MutatingScope->methodCallReturnType()
#4 phar:///home/user/blog/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1740): PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}()
#5 phar:///home/user/blog/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(533): PHPStan\Analyser\MutatingScope->resolveType()
#6 phar:///home/user/blog/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(789): PHPStan\Analyser\MutatingScope->getType()
#7 phar:///home/user/blog/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(533): PHPStan\Analyser\MutatingScope->resolveType()
#8 phar:///home/user/blog/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1380): PHPStan\Analyser\MutatingScope->getType()
#9 phar:///home/user/blog/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(496): PHPStan\Analyser\NodeScopeResolver->findEarlyTerminatingExpr()
#10 phar:///home/user/blog/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(298): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#11 phar:///home/user/blog/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(586): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()
#12 phar:///home/user/blog/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(298): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#13 phar:///home/user/blog/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(656): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()
#14 phar:///home/user/blog/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(298): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#15 phar:///home/user/blog/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(586): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()
#16 phar:///home/user/blog/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(298): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#17 phar:///home/user/blog/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(460): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()
#18 phar:///home/user/blog/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(298): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#19 phar:///home/user/blog/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(544): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()
#20 phar:///home/user/blog/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(298): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#21 phar:///home/user/blog/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(510): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()
#22 phar:///home/user/blog/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(269): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#23 phar:///home/user/blog/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(181): PHPStan\Analyser\NodeScopeResolver->processNodes()
#24 phar:///home/user/blog/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/Analyser.php(69): PHPStan\Analyser\FileAnalyser->analyseFile()
#25 phar:///home/user/blog/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyserRunner.php(62): PHPStan\Analyser\Analyser->analyse()
#26 phar:///home/user/blog/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseApplication.php(163): PHPStan\Command\AnalyserRunner->runAnalyser()
#27 phar:///home/user/blog/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseApplication.php(95): PHPStan\Command\AnalyseApplication->runAnalyser()
#28 phar:///home/user/blog/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseCommand.php(175): PHPStan\Command\AnalyseApplication->analyse()
#29 phar:///home/user/blog/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(259): PHPStan\Command\AnalyseCommand->execute()
#30 phar:///home/user/blog/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(848): _PHPStan_70b6e53dc\Symfony\Component\Console\Command\Command->run()
#31 phar:///home/user/blog/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(259): _PHPStan_70b6e53dc\Symfony\Component\Console\Application->doRunCommand()
#32 phar:///home/user/blog/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(157): _PHPStan_70b6e53dc\Symfony\Component\Console\Application->doRun()
#33 phar:///home/user/blog/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(94): _PHPStan_70b6e53dc\Symfony\Component\Console\Application->run()
#34 phar:///home/user/blog/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(95): _PHPStan_70b6e53dc\{closure}()
#35 /home/user/blog/vendor/phpstan/phpstan/phpstan(7): require('phar:///home/sa...')
#36 /home/user/blog/vendor/bin/phpstan(102): include('/home/user/blo...')
#37 {main}
```

**Comment by szepeviktor** [comment]
https://github.com/nunomaduro/larastan/blob/9eb1ad99ecfce0ed0909e19ed1434f74e9893f03/src/Methods/BuilderHelper.php#L221

**Comment by nzsakib** [comment]
Hi, I have placed the try catch block. It gave me this: 

![image](https://user-images.githubusercontent.com/8240768/150777497-31815383-c6e6-4d20-bfdf-433aa3785b2c.png)

**Comment by canvural** [comment]
Hi,

Thanks for the report. I'll take a look.

**Comment by nzsakib** [comment]
Here how I was able to re-produce it. Added it on the post above.

**Comment by canvural** [comment]
Fixed in 9fa5822

Thank you.
