### ISSUE TITLE
Call to undefined method PHPStan\Type\UnionType::getClassReflection()

### ISSUE THREAD

**Issue by johanmolen** [nunomaduro/larastan#1171]
- Larastan Version: 2.1.2
- `--level` used: 8

Also reported [here](https://github.com/phpstan/phpstan/issues/6824).

### Description
Im getting the following error when running Larastan.
`Call to undefined method PHPStan\Type\UnionType::getClassReflection()`

This is the output of `vendor/bin/phpstan --debug`.

```
Uncaught Error: Call to undefined method PHPStan\Type\UnionType::getClassReflection() in /vendor/nunomaduro/larastan/src/Rules/ModelProperties/ModelPropertiesRuleHelper.php:48
#0 /vendor/nunomaduro/larastan/src/Rules/ModelProperties/ModelPropertyRule.php(81): NunoMaduro\Larastan\Rules\ModelProperties\ModelPropertiesRuleHelper->check(Object(PHPStan\Reflection\Type\UnionTypeMethodReflection), Object(PHPStan\Analyser\MutatingScope), Array, NULL)
#1 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(102): NunoMaduro\Larastan\Rules\ModelProperties\ModelPropertyRule->processNode(Object(PhpParser\Node\Expr\MethodCall), Object(PHPStan\Analyser\MutatingScope))
#2 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Node/ClassStatementsGatherer.php(95): PHPStan\Analyser\FileAnalyser->PHPStan\Analyser\{closure}(Object(PhpParser\Node\Expr\MethodCall), Object(PHPStan\Analyser\MutatingScope))
#3 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(451): PHPStan\Node\ClassStatementsGatherer->__invoke(Object(PhpParser\Node\Expr\MethodCall), Object(PHPStan\Analyser\MutatingScope))
#4 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(2340): PHPStan\Analyser\NodeScopeResolver::PHPStan\Analyser\{closure}(Object(PhpParser\Node\Expr\MethodCall), Object(PHPStan\Analyser\MutatingScope))
#5 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1421): PHPStan\Analyser\NodeScopeResolver->callNodeCallbackWithExpression(Object(Closure), Object(PhpParser\Node\Expr\MethodCall), Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Analyser\ExpressionContext))
#6 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(503): PHPStan\Analyser\NodeScopeResolver->processExprNode(Object(PhpParser\Node\Expr\MethodCall), Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\ExpressionContext))
#7 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(304): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Expression), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#8 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(466): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\ClassMethod), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#9 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(304): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\ClassMethod), Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer))
#10 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(550): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Class_), Array, Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer))
#11 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(304): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Class_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#12 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(516): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Namespace_), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#13 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(275): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Namespace_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#14 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(189): PHPStan\Analyser\NodeScopeResolver->processNodes(Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#15 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/Analyser.php(61): PHPStan\Analyser\FileAnalyser->analyseFile('/Users/username/Si...', Array, Object(PHPStan\Rules\Registry), NULL)
#16 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyserRunner.php(62): PHPStan\Analyser\Analyser->analyse(Array, Object(Closure), NULL, true, Array)
#17 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseApplication.php(133): PHPStan\Command\AnalyserRunner->runAnalyser(Array, Array, Object(Closure), NULL, true, true, '/Users/username/Si...', NULL, NULL, Object(_PHPStan_ae8980142\Symfony\Component\Console\Input\ArgvInput))
#18 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseApplication.php(64): PHPStan\Command\AnalyseApplication->runAnalyser(Array, Array, true, '/Users/username/Si...', Object(PHPStan\Command\Symfony\SymfonyOutput), Object(PHPStan\Command\Symfony\SymfonyOutput), Object(_PHPStan_ae8980142\Symfony\Component\Console\Input\ArgvInput))
#19 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseCommand.php(175): PHPStan\Command\AnalyseApplication->analyse(Array, false, Object(PHPStan\Command\Symfony\SymfonyOutput), Object(PHPStan\Command\Symfony\SymfonyOutput), false, true, '/Users/username/Si...', Array, Object(_PHPStan_ae8980142\Symfony\Component\Console\Input\ArgvInput))
#20 phar:///vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(259): PHPStan\Command\AnalyseCommand->execute(Object(_PHPStan_ae8980142\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_ae8980142\Symfony\Component\Console\Output\ConsoleOutput))
#21 phar:///vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(856): _PHPStan_ae8980142\Symfony\Component\Console\Command\Command->run(Object(_PHPStan_ae8980142\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_ae8980142\Symfony\Component\Console\Output\ConsoleOutput))
#22 phar:///vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(259): _PHPStan_ae8980142\Symfony\Component\Console\Application->doRunCommand(Object(PHPStan\Command\AnalyseCommand), Object(_PHPStan_ae8980142\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_ae8980142\Symfony\Component\Console\Output\ConsoleOutput))
#23 phar:///vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(157): _PHPStan_ae8980142\Symfony\Component\Console\Application->doRun(Object(_PHPStan_ae8980142\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_ae8980142\Symfony\Component\Console\Output\ConsoleOutput))
#24 phar:///vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(94): _PHPStan_ae8980142\Symfony\Component\Console\Application->run()
#25 phar:///vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(95): _PHPStan_ae8980142\{closure}()
#26 /vendor/phpstan/phpstan/phpstan(8): require('phar:///Users/j...')
#27 /vendor/bin/phpstan(117): include('/Users/username/Si...')
```

### Laravel code where the issue was found

```php
public function handle(Feed|SubFeed $feed): void
{
    ....
}

```

Both Feed and SubFeed are models.

**Comment by ondrejmirtes** [comment]
This is the problematic code in question: https://github.com/nunomaduro/larastan/blob/a547883e95cacfa558939bef5c699ea9d589f76b/src/Rules/ModelProperties/ModelPropertiesRuleHelper.php#L46-L48

It's not a good idea to use inline `@var` like that, it can be wrong and in this case it is wrong :)

**Comment by ondrejmirtes** [comment]
If this method had an array shape return type, the `@var`s at the call place aren't needed: https://github.com/nunomaduro/larastan/blob/a547883e95cacfa558939bef5c699ea9d589f76b/src/Rules/ModelProperties/ModelPropertiesRuleHelper.php#L142-L147

**Comment by johanmolen** [comment]
Is there something I can do? 🙂

**Comment by szepeviktor** [comment]
Maybe sending a PR with the above 👆 changes....
🤔
