### ISSUE TITLE
 Internal error: Method dynamicWhere() was not found in reflection of class Illuminate\Database\Query\Builder.

### ISSUE THREAD

**Issue by dianfishekqi** [nunomaduro/larastan#1309]
- Larastan Version: 2.1.4
- `--level` used: 8

### Description
 https://github.com/phpstan/phpstan/issues/7613, issue comes up after upgrading from phpstan 1.6.9 to 1.8

### Laravel code where the issue was found

```
 #0 /vendor/nunomaduro/larastan/src/Methods/BuilderHelper.php(109): PHPStan\Reflection\ClassReflection->getNativeMethod()                                    
 #1 /vendor/nunomaduro/larastan/src/Methods/BuilderHelper.php(189): NunoMaduro\Larastan\Methods\BuilderHelper->dynamicWhere()                                
 #2 /vendor/nunomaduro/larastan/src/Methods/EloquentBuilderForwardsCallsExtension.php(106):                                                                  
 NunoMaduro\Larastan\Methods\BuilderHelper->searchOnEloquentBuilder()                                                                                                            
 #3 /vendor/nunomaduro/larastan/src/Methods/EloquentBuilderForwardsCallsExtension.php(54):                                                                   
 NunoMaduro\Larastan\Methods\EloquentBuilderForwardsCallsExtension->findMethod()                                                                                                 
 #4 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ClassReflection.php(386):                                                                     
 NunoMaduro\Larastan\Methods\EloquentBuilderForwardsCallsExtension->hasMethod()             
```

**Comment by canvural** [comment]
Hi,

Can you provide some code where this error happens?

**Comment by dianfishekqi** [comment]
Hello,

```php
 public function get(Request $request): JsonResource
    {
        JsonResource::withoutWrapping();

        return JsonResource::make(['exists' => ExpoToken::where('token', $request->device_token)->exists()]);
    }

```

**Comment by dianfishekqi** [comment]
This is one instance of the  of the error.

```
 Reached internal errors count limit of 50, exiting...                                                                                    
     Internal error: Internal error: Method dynamicWhere() was not found in reflection of class Illuminate\Database\Query\Builder. in file    
     /app/Http/Requests/Customer/Guest/API/RegisterRequest.php                                                            
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method dynamicWhere() was not found in reflection of class Illuminate\Database\Query\Builder. in file    
     /app/Http/Requests/Customer/Guest/RegisterRequest.php                                                                
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method exists() was not found in reflection of class Illuminate\Database\Query\Builder. in file          
     /app/Http/Requests/Wishlist/AddItemRequest.php                                                                       
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method exists() was not found in reflection of class Illuminate\Database\Query\Builder. in file          
     /app/Http/Requests/Wishlist/AddItemsBatchRequest.php                                                                 
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method exists() was not found in reflection of class Illuminate\Database\Query\Builder. in file          
     /app/Http/Requests/Checkout/CreateRequest.php                                                                        
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method exists() was not found in reflection of class Illuminate\Database\Query\Builder. in file          
     /app/Http/Requests/Checkout/SkuRequest.php                                                                           
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method dynamicWhere() was not found in reflection of class Illuminate\Database\Query\Builder. in file    
     /app/Models/Sale/DiscountItemSet.php                                                                                 
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method dynamicWhere() was not found in reflection of class Illuminate\Database\Query\Builder. in file    
     /app/Models/User/User.php                                                                                            
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method dynamicWhere() was not found in reflection of class Illuminate\Database\Query\Builder. in file    
     /app/Models/Mapper/Map/ProductBrand.php                                                                              
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method dynamicWhere() was not found in reflection of class Illuminate\Database\Query\Builder. in file    
     /app/Models/Mapper/Mapper.php                                                                                        
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method dynamicWhere() was not found in reflection of class Illuminate\Database\Query\Builder. in file    
     /app/Models/Driver/DriverBalanceLedger.php                                                                           
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method dynamicWhere() was not found in reflection of class Illuminate\Database\Query\Builder. in file    
     /app/Models/DemandStatistic.php                                                                                      
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method dynamicWhere() was not found in reflection of class Illuminate\Database\Query\Builder. in file    
     /app/Models/Team/Team.php                                                                                            
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method dynamicWhere() was not found in reflection of class Illuminate\Database\Query\Builder. in file    
     /app/Models/Team/TeamSettings.php                                                                                    
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method dynamicWhere() was not found in reflection of class Illuminate\Database\Query\Builder. in file    
     /app/Models/Team/Location.php                                                                                        
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method dynamicWhere() was not found in reflection of class Illuminate\Database\Query\Builder. in file    
     /app/Models/Product/ProductSet.php                                                                                   
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method dynamicWhere() was not found in reflection of class Illuminate\Database\Query\Builder. in file    
     /app/Models/Product/ProductAttribute.php                                                                             
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method dynamicWhere() was not found in reflection of class Illuminate\Database\Query\Builder. in file    
     /app/Actions/Jetstream/RemoveTeamMember.php                                                                          
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method count() was not found in reflection of class Illuminate\Database\Query\Builder. in file           
     /app/Actions/Fortify/CreateNewUser.php                                                                               
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method dynamicWhere() was not found in reflection of class Illuminate\Database\Query\Builder. in file    
     /app/Models/Shipping/Balance.php                                                                                     
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method dynamicWhere() was not found in reflection of class Illuminate\Database\Query\Builder. in file    
     /app/Models/Shipping/ShippingRequest.php                                                                             
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method dynamicWhere() was not found in reflection of class Illuminate\Database\Query\Builder. in file    
     /app/Models/Sale/SalePrice.php                                                                                       
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method dynamicWhere() was not found in reflection of class Illuminate\Database\Query\Builder. in file    
     /app/Models/Sale/SaleSheet.php                                                                                       
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method dynamicWhere() was not found in reflection of class Illuminate\Database\Query\Builder. in file    
     /app/Services/ShippingService.php                                                                                    
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method dynamicWhere() was not found in reflection of class Illuminate\Database\Query\Builder. in file    
     /app/Services/ProductRecommendationService.php                                                                       
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method dynamicWhere() was not found in reflection of class Illuminate\Database\Query\Builder. in file    
     /app/Http/Controllers/User/InviteController.php                                                                      
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method exists() was not found in reflection of class Illuminate\Database\Query\Builder. in file          
     /app/Http/Controllers/Customer/Shop/CheckoutController.php                                                           
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method insertOrIgnore() was not found in reflection of class Illuminate\Database\Query\Builder. in file  
     /app/Http/Controllers/Customer/Shop/WishlistItemController.php                                                       
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method dynamicWhere() was not found in reflection of class Illuminate\Database\Query\Builder. in file    
     /app/Http/Controllers/Customer/CustomerController.php                                                                
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method exists() was not found in reflection of class Illuminate\Database\Query\Builder. in file          
     /app/Http/Controllers/ExpoTokenController.php                                                                        
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method exists() was not found in reflection of class Illuminate\Database\Query\Builder. in file          
     /app/Rules/EmailExistsRule.php                                                                                       
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method dynamicWhere() was not found in reflection of class Illuminate\Database\Query\Builder. in file    
     /app/Actions/Jetstream/InviteTeamMember.php                                                                          
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method dynamicWhere() was not found in reflection of class Illuminate\Database\Query\Builder. in file    
     /app/Models/Customer/Customer.php                                                                                    
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method dynamicWhere() was not found in reflection of class Illuminate\Database\Query\Builder. in file    
     /app/Models/Customer/WishlistItem.php                                                                                
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method dynamicWhere() was not found in reflection of class Illuminate\Database\Query\Builder. in file    
     /app/Models/ProductImage/ProductImageBatch.php                                                                       
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method dynamicWhere() was not found in reflection of class Illuminate\Database\Query\Builder. in file    
     /app/Models/ProductImage/ProductImage.php                                                                            
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method dynamicWhere() was not found in reflection of class Illuminate\Database\Query\Builder. in file    
     /app/Models/CashBack.php                                                                                             
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method dynamicWhere() was not found in reflection of class Illuminate\Database\Query\Builder. in file    
     /app/Models/Team/Membership.php                                                                                      
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method dynamicWhere() was not found in reflection of class Illuminate\Database\Query\Builder. in file    
     /app/Models/Team/TeamConfiguration.php                                                                               
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method dynamicWhere() was not found in reflection of class Illuminate\Database\Query\Builder. in file    
     /app/ShippingProviders/IntegraProvider.php                                                                           
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method dynamicWhere() was not found in reflection of class Illuminate\Database\Query\Builder. in file    
     /app/Models/Product/ProductInventory.php                                                                             
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method dynamicWhere() was not found in reflection of class Illuminate\Database\Query\Builder. in file    
     /app/Models/Product/Product.php                                                                                      
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method dynamicWhere() was not found in reflection of class Illuminate\Database\Query\Builder. in file    
     /app/Models/Product/ProductQueue.php                                                                                 
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method dynamicWhere() was not found in reflection of class Illuminate\Database\Query\Builder. in file    
     /app/Models/Order/Checkout.php                                                                                       
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method dynamicWhere() was not found in reflection of class Illuminate\Database\Query\Builder. in file    
     /app/Models/Order/Order.php                                                                                          
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method count() was not found in reflection of class Illuminate\Database\Query\Builder. in file           
     /app/Models/Purchase/Vendor/Catalog/Catalog.php                                                                      
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method dynamicWhere() was not found in reflection of class Illuminate\Database\Query\Builder. in file    
     /app/Models/Purchase/Vendor/Vendor.php                                                                               
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method count() was not found in reflection of class Illuminate\Database\Query\Builder. in file           
     /app/Models/Purchase/Budget/Budget.php                                                                               
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method count() was not found in reflection of class Illuminate\Database\Query\Builder. in file           
     /app/Models/Purchase/PurchaseOrder/PurchaseOrder.php                                                                 
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Internal error: Internal error: Method dynamicWhere() was not found in reflection of class Illuminate\Database\Query\Builder. in file    
     /app/View/Settings/ConnectorNonConfig.php                                                                            
     Run PHPStan with -v option and post the stack trace to:                                                                                  
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                     
     Child process error (exit code 1):                                                                                                       
     Child process error (exit code 1):                                                                                                       
     Child process error (exit code 1):                                                                                                       
     Child process error (exit code 1):                                                                                                       
     Child process error (exit code 1):                                                                                                       
     Child process error (exit code 1):                                                                                                       
     Child process error (exit code 1):                                                                                                       
     Child process error (exit code 1):                               
### Code snippet that reproduces the problem

**Comment by szepeviktor** [comment]
What happens if you remove `ExpoToken::where` from your code and run PHPStan again?

**Comment by dianfishekqi** [comment]
that particular error goes away, but other errors are still present

**Comment by szepeviktor** [comment]
> that particular error goes away

Thank you very much!
@canvural Now we are sure that the internal error is caused by `where`.

**Comment by dianfishekqi** [comment]
➜  app git:(develop) ✗ ./vendor/bin/phpstan analyse --memory-limit=2G -v app/Models/Events       

Note: Using configuration file /var/www/integra/app/phpstan.neon.
 18/18 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100% < 1 sec

 ------ ------------------------------------------------------------------------------------------------------- 
  Line   Event.php                                                                                              
 ------ ------------------------------------------------------------------------------------------------------- 
  127    Call to an undefined method Illuminate\Database\Eloquent\Builder<App\Models\Events\Event>::orderBy().  
 ------ ------------------------------------------------------------------------------------------------------- 

if I run it in a subdir it doesn't throw  internal errors, but still throws undefined orderBy

**Comment by MJTheOne** [comment]
I just added a stub for a Filament Resource and suddenly got this "dynamicWhere" error.
Why is this closed? I don't see a real resolution?

**Comment by AhmedHelalAhmed** [comment]
I faced the same issue.
Any solution for it?!

**Comment by hinimajesty** [comment]
I had same issue too and managed to fix it by using barryvdh/laravel-ide-helper to generate the necessary annotations for the model classes. You can follow this guide https://labrodev.substack.com/p/using-static-analysis-in-laravel for some ideas on how to set up the package. It seems phpstan is unable to locate ->whereNull() , ->whereUuid() , ->where{dynamicName} methods on eloquent models in some cases.

**Comment by canvural** [comment]
I'd appreciate a PR with a failing test case from anyone that experiences this issue 🙏🏽
