### ISSUE TITLE
Target class [facade] does not exist in package helpers.php file

### ISSUE THREAD

**Issue by tintnaingwinn** [nunomaduro/larastan#1387]
- Larastan Version: 2.2.2
- `--level` used: 4

### Description
```
Internal error: Target class [facade] does not exist. in file <package>/src/helpers.php
```
Returning facade does not exist. it's working well at **Larastan Version 2.1.12**

### Laravel code where the issue was found

```
 -- ----------------------------------------------------------------------------------------------------------------------------------------------------------------------
     Error
 -- ----------------------------------------------------------------------------------------------------------------------------------------------------------------------
     Internal error: Internal error: Target class [num] does not exist. in file <package>/src/helpers.php

     Post the following stack trace to https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md:
     #0 <package>/vendor/laravel/framework/src/Illuminate/Container/Container.php(756): Illuminate\Container\Container->build('num')
     #1 <package>/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(860): Illuminate\Container\Container->resolve('num',
     Array, true)
     #2 <package>/vendor/laravel/framework/src/Illuminate/Container/Container.php(692): Illuminate\Foundation\Application->resolve('num',
     Array)
     #3 <package>/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(845): Illuminate\Container\Container->make('num',
     Array)
     #4 <package>/vendor/laravel/framework/src/Illuminate/Container/Container.php(1419): Illuminate\Foundation\Application->make('num')
     #5 <package>/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(222): Illuminate\Container\Container->offsetGet('num')
     #6 <package>/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(193):
     Illuminate\Support\Facades\Facade::resolveFacadeInstance('num')
     #7 <package>/vendor/nunomaduro/larastan/src/Methods/Pipes/Facades.php(30): Illuminate\Support\Facades\Facade::getFacadeRoot()
     #8 <package>/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180):
     NunoMaduro\Larastan\Methods\Pipes\Facades->handle(Object(NunoMaduro\Larastan\Methods\Passable), Object(Closure))
     #9 <package>/vendor/nunomaduro/larastan/src/Methods/Pipes/Contracts.php(36):
     Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(NunoMaduro\Larastan\Methods\Passable))
     #10 <package>/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180):
     NunoMaduro\Larastan\Methods\Pipes\Contracts->handle(Object(NunoMaduro\Larastan\Methods\Passable), Object(Closure))
     #11 <package>/vendor/nunomaduro/larastan/src/Methods/Pipes/SelfClass.php(25):
     Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(NunoMaduro\Larastan\Methods\Passable))
     #12 <package>/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180):
     NunoMaduro\Larastan\Methods\Pipes\SelfClass->handle(Object(NunoMaduro\Larastan\Methods\Passable), Object(Closure))
     #13 <package>/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116):
     Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(NunoMaduro\Larastan\Methods\Passable))
     #14 <package>/vendor/nunomaduro/larastan/src/Methods/Kernel.php(66): Illuminate\Pipeline\Pipeline->then(Object(Closure))
     #15 <package>/vendor/nunomaduro/larastan/src/Methods/Extension.php(42):
     NunoMaduro\Larastan\Methods\Kernel->handle(Object(PHPStan\Reflection\ClassReflection), 'convert')
     #16 phar://<package>/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ClassReflection.php(413):
     NunoMaduro\Larastan\Methods\Extension->hasMethod(Object(PHPStan\Reflection\ClassReflection), 'convert')
     #17 phar://<package>/vendor/phpstan/phpstan/phpstan.phar/src/Type/ObjectType.php(477):
     PHPStan\Reflection\ClassReflection->hasMethod('convert')
     #18 phar://<package>/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(3531):
     PHPStan\Type\ObjectType->hasMethod('convert')
     #19 phar://<package>/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(3541):
     PHPStan\Analyser\MutatingScope->getMethodReflection(Object(PHPStan\Type\ObjectType), 'convert')
     #20 phar://<package>/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1444):
     PHPStan\Analyser\MutatingScope->methodCallReturnType(Object(PHPStan\Type\ObjectType), 'convert', Object(PhpParser\Node\Expr\StaticCall))
     #21 phar://<package>/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1450):
     PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}()
     #22 phar://<package>/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(572):
     PHPStan\Analyser\MutatingScope->resolveType(Object(PhpParser\Node\Expr\StaticCall))
     #23 phar://<package>/vendor/phpstan/phpstan/phpstan.phar/src/Rules/FunctionReturnTypeCheck.php(57):
     PHPStan\Analyser\MutatingScope->getType(Object(PhpParser\Node\Expr\StaticCall))
     #24 phar://<package>/vendor/phpstan/phpstan/phpstan.phar/src/Rules/Functions/ReturnTypeRule.php(44):
     PHPStan\Rules\FunctionReturnTypeCheck->checkReturnType(Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Type\StringType),
     Object(PhpParser\Node\Expr\StaticCall), Object(PhpParser\Node\Stmt\Return_), 'Function num_co...', 'Function num_co...', 'Function num_co...', 'Function num_co...',
     false)
     #25 phar://<package>/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(105):
     PHPStan\Rules\Functions\ReturnTypeRule->processNode(Object(PhpParser\Node\Stmt\Return_), Object(PHPStan\Analyser\MutatingScope))
     #26 phar://<package>/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(424):
     PHPStan\Analyser\FileAnalyser->PHPStan\Analyser\{closure}(Object(PhpParser\Node\Stmt\Return_), Object(PHPStan\Analyser\MutatingScope))
     #27 phar://<package>/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(391):
     PHPStan\Analyser\NodeScopeResolver::PHPStan\Analyser\{closure}(Object(PhpParser\Node\Stmt\Return_), Object(PHPStan\Analyser\MutatingScope))
     #28 phar://<package>/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(336):
     PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Return_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
     #29 phar://<package>/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(439):
     PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Function_), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
     #30 phar://<package>/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(336):
     PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Function_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
     #31 phar://<package>/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(609):
     PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\If_), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
     #32 phar://<package>/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(306):
     PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\If_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
     #33 phar://<package>/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(174):
     PHPStan\Analyser\NodeScopeResolver->processNodes(Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
     #34 phar://<package>/vendor/phpstan/phpstan/phpstan.phar/src/Command/WorkerCommand.php(147):
     PHPStan\Analyser\FileAnalyser->analyseFile('<user>...', Array, Object(PHPStan\Rules\Registry), Object(PHPStan\Collectors\Registry), NULL)
     #35 phar://<package>/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):
     PHPStan\Command\WorkerCommand->PHPStan\Command\{closure}(Array)
     #36 phar://<package>/vendor/phpstan/phpstan/phpstan.phar/vendor/clue/ndjson-react/src/Decoder.php(110):
     _PHPStan_3bfe2e67c\Evenement\EventEmitter->emit('data', Array)
     #37 phar://<package>/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):
     _PHPStan_3bfe2e67c\Clue\React\NDJson\Decoder->handleData(Array)
     #38 phar://<package>/vendor/phpstan/phpstan/phpstan.phar/vendor/react/stream/src/Util.php(62):
     _PHPStan_3bfe2e67c\Evenement\EventEmitter->emit('data', Array)
     #39 phar://<package>/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):
     _PHPStan_3bfe2e67c\React\Stream\Util::_PHPStan_3bfe2e67c\React\Stream\{closure}('{"action":"anal...')
     #40 phar://<package>/vendor/phpstan/phpstan/phpstan.phar/vendor/react/stream/src/DuplexResourceStream.php(154):
     _PHPStan_3bfe2e67c\Evenement\EventEmitter->emit('data', Array)
     #41 phar://<package>/vendor/phpstan/phpstan/phpstan.phar/vendor/react/event-loop/src/StreamSelectLoop.php(201):
     _PHPStan_3bfe2e67c\React\Stream\DuplexResourceStream->handleData(Resource id #3843)
     #42 phar://<package>/vendor/phpstan/phpstan/phpstan.phar/vendor/react/event-loop/src/StreamSelectLoop.php(173):
     _PHPStan_3bfe2e67c\React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)
     #43 phar://<package>/vendor/phpstan/phpstan/phpstan.phar/src/Command/WorkerCommand.php(107):
     _PHPStan_3bfe2e67c\React\EventLoop\StreamSelectLoop->run()
     #44 phar://<package>/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(259):
     PHPStan\Command\WorkerCommand->execute(Object(_PHPStan_3bfe2e67c\Symfony\Component\Console\Input\ArgvInput),
     Object(_PHPStan_3bfe2e67c\Symfony\Component\Console\Output\ConsoleOutput))
     #45 phar://<package>/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(865):
     _PHPStan_3bfe2e67c\Symfony\Component\Console\Command\Command->run(Object(_PHPStan_3bfe2e67c\Symfony\Component\Console\Input\ArgvInput),
     Object(_PHPStan_3bfe2e67c\Symfony\Component\Console\Output\ConsoleOutput))
     #46 phar://<package>/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(259):
     _PHPStan_3bfe2e67c\Symfony\Component\Console\Application->doRunCommand(Object(PHPStan\Command\WorkerCommand),
     Object(_PHPStan_3bfe2e67c\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_3bfe2e67c\Symfony\Component\Console\Output\ConsoleOutput))
     #47 phar://<package>/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(157):
     _PHPStan_3bfe2e67c\Symfony\Component\Console\Application->doRun(Object(_PHPStan_3bfe2e67c\Symfony\Component\Console\Input\ArgvInput),
     Object(_PHPStan_3bfe2e67c\Symfony\Component\Console\Output\ConsoleOutput))
     #48 phar://<package>/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(124):
     _PHPStan_3bfe2e67c\Symfony\Component\Console\Application->run()
     #49 phar://<package>/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(125): _PHPStan_3bfe2e67c\{closure}()
     #50 <package>/vendor/phpstan/phpstan/phpstan(8): require('phar:///Users/t...')
     #51 <package>/vendor/bin/phpstan(120): include('<user>...')
     #52 {main}
     Child process error (exit code 1):
 -- ----------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by tintnaingwinn** [comment]
Hi @szepeviktor 
It's from my laravel package.

**Comment by mad-briller** [comment]
@szepeviktor interestingly my issue is absent on 2.1.12, so something between 2.1.12 and 2.2 of larastan introduced this issue with the `ClassLoader` it seems.

**Comment by szepeviktor** [comment]
My PR with using `ClassLoader` was introduced in 2.0.2 I think ...
https://github.com/nunomaduro/larastan/commit/ef59ce6f7b218f9edaa632158c470830680c38db

**Comment by canvural** [comment]
I guess this was about the `laravel-num` package. Tested with Larastan 2.2.1 and 2.2.2 and it all works fine 🤷🏽‍♂️
