### ISSUE TITLE
Carbon::macro with argument cause phpstan to crash (Argument must be of type ReflectionParameter)

### ISSUE THREAD

**Issue by JonathanGawrych** [nunomaduro/larastan#1413]
- Larastan Version: 2.2.5
- `--level` used: 0
- Pull request with failing test: _Unable to get to reproduce in larastan's test suite. (See below)_

### Description
When creating a carbon macro in laravel with any argument, phpstan will crash when using laravel.

To reproduce:
```bash
composer create-project laravel/laravel example-app
cd example-app
composer require --dev phpstan/phpstan nunomaduro/larastan phpstan/extension-installer
```

Then add the following code to AppServiceProvider::boot():
```php
        \Illuminate\Support\Carbon::macro('foo', static function ($bar) {});
        \Illuminate\Support\Carbon::foo(123);
```

Running phpstan:
```bash
./vendor/bin/phpstan analyse -v app/Providers/AppServiceProvider.php 
```
will now crash with:
```
Internal error: Internal error: PHPStan\Reflection\Php\PhpMethodReflection::PHPStan\Reflection\Php\{closure}(): Argument #1 ($reflection) must be of type
PHPStan\BetterReflection\Reflection\Adapter\ReflectionParameter, ReflectionParameter given in file /example-app/app/Providers/AppServiceProvider.php

#0 [internal function]: PHPStan\Reflection\Php\PhpMethodReflection->PHPStan\Reflection\Php\{closure}(Object(ReflectionParameter))
#1 phar:///phpstan.phar/src/Reflection/Php/PhpMethodReflection.php(237): array_map(Object(Closure), Array)
#2 phar:///phpstan.phar/src/Reflection/Php/PhpMethodReflection.php(225): PHPStan\Reflection\Php\PhpMethodReflection->getParameters()
#3 phar:///phpstan.phar/src/Reflection/Type/CalledOnTypeUnresolvedMethodPrototypeReflection.php(80): PHPStan\Reflection\Php\PhpMethodReflection->getVariants()
#4 phar:///phpstan.phar/src/Reflection/Type/CalledOnTypeUnresolvedMethodPrototypeReflection.php(68): PHPStan\Reflection\Type\CalledOnTypeUnresolvedMethodPrototypeReflection->transformMethodWithStaticType(Object(PHPStan\Reflection\ClassReflection), Object(PHPStan\Reflection\Php\PhpMethodReflection))
#5 phar:///phpstan.phar/src/Type/ObjectType.php(468): PHPStan\Reflection\Type\CalledOnTypeUnresolvedMethodPrototypeReflection->getTransformedMethod()
#6 phar:///phpstan.phar/src/Analyser/MutatingScope.php(3434): PHPStan\Type\ObjectType->getMethod('foo', Object(PHPStan\Analyser\MutatingScope))
#7 phar:///phpstan.phar/src/Analyser/MutatingScope.php(3441): PHPStan\Analyser\MutatingScope->getMethodReflection(Object(PHPStan\Type\ObjectType), 'foo')
#8 phar:///phpstan.phar/src/Analyser/MutatingScope.php(1398): PHPStan\Analyser\MutatingScope->methodCallReturnType(Object(PHPStan\Type\ObjectType), 'foo', Object(PhpParser\Node\Expr\StaticCall))
#9 phar:///phpstan.phar/src/Analyser/MutatingScope.php(1404): PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}()
#10 phar:///phpstan.phar/src/Analyser/MutatingScope.php(551): PHPStan\Analyser\MutatingScope->resolveType(Object(PhpParser\Node\Expr\StaticCall))
#11 phar:///phpstan.phar/src/Analyser/NodeScopeResolver.php(1392): PHPStan\Analyser\MutatingScope->getType(Object(PhpParser\Node\Expr\StaticCall))
#12 phar:///phpstan.phar/src/Analyser/NodeScopeResolver.php(521): PHPStan\Analyser\NodeScopeResolver->findEarlyTerminatingExpr(Object(PhpParser\Node\Expr\StaticCall), Object(PHPStan\Analyser\MutatingScope))
#13 phar:///phpstan.phar/src/Analyser/NodeScopeResolver.php(323): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Expression), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#14 phar:///phpstan.phar/src/Analyser/NodeScopeResolver.php(485): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\ClassMethod), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#15 phar:///phpstan.phar/src/Analyser/NodeScopeResolver.php(323): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\ClassMethod), Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer))
#16 phar:///phpstan.phar/src/Analyser/NodeScopeResolver.php(569): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Class_), Array, Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer))
#17 phar:///phpstan.phar/src/Analyser/NodeScopeResolver.php(323): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Class_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#18 phar:///phpstan.phar/src/Analyser/NodeScopeResolver.php(535): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Namespace_), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#19 phar:///phpstan.phar/src/Analyser/NodeScopeResolver.php(294): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Namespace_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#20 phar:///phpstan.phar/src/Analyser/FileAnalyser.php(189): PHPStan\Analyser\NodeScopeResolver->processNodes(Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#21 phar:///phpstan.phar/src/Command/WorkerCommand.php(143): PHPStan\Analyser\FileAnalyser->analyseFile('/Volumes/code/w...', Array, Object(PHPStan\Rules\Registry), NULL)
#22 phar:///phpstan.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97): PHPStan\Command\WorkerCommand->PHPStan\Command\{closure}(Array)
#23 phar:///phpstan.phar/vendor/clue/ndjson-react/src/Decoder.php(110): _PHPStan_0a43b4828\Evenement\EventEmitter->emit('data', Array)
#24 phar:///phpstan.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97): _PHPStan_0a43b4828\Clue\React\NDJson\Decoder->handleData(Array)
#25 phar:///phpstan.phar/vendor/react/stream/src/Util.php(62): _PHPStan_0a43b4828\Evenement\EventEmitter->emit('data', Array)
#26 phar:///phpstan.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97): _PHPStan_0a43b4828\React\Stream\Util::_PHPStan_0a43b4828\React\Stream\{closure}('{"action":"anal...')
#27 phar:///phpstan.phar/vendor/react/stream/src/DuplexResourceStream.php(154): _PHPStan_0a43b4828\Evenement\EventEmitter->emit('data', Array)
#28 phar:///phpstan.phar/vendor/react/event-loop/src/StreamSelectLoop.php(201): _PHPStan_0a43b4828\React\Stream\DuplexResourceStream->handleData(Resource id #3821)
#29 phar:///phpstan.phar/vendor/react/event-loop/src/StreamSelectLoop.php(173): _PHPStan_0a43b4828\React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)
#30 phar:///phpstan.phar/src/Command/WorkerCommand.php(106): _PHPStan_0a43b4828\React\EventLoop\StreamSelectLoop->run()
#31 phar:///phpstan.phar/vendor/symfony/console/Command/Command.php(259): PHPStan\Command\WorkerCommand->execute(Object(_PHPStan_0a43b4828\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_0a43b4828\Symfony\Component\Console\Output\ConsoleOutput))
#32 phar:///phpstan.phar/vendor/symfony/console/Application.php(856): _PHPStan_0a43b4828\Symfony\Component\Console\Command\Command->run(Object(_PHPStan_0a43b4828\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_0a43b4828\Symfony\Component\Console\Output\ConsoleOutput))
#33 phar:///phpstan.phar/vendor/symfony/console/Application.php(259): _PHPStan_0a43b4828\Symfony\Component\Console\Application->doRunCommand(Object(PHPStan\Command\WorkerCommand), Object(_PHPStan_0a43b4828\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_0a43b4828\Symfony\Component\Console\Output\ConsoleOutput))
#34 phar:///phpstan.phar/vendor/symfony/console/Application.php(157): _PHPStan_0a43b4828\Symfony\Component\Console\Application->doRun(Object(_PHPStan_0a43b4828\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_0a43b4828\Symfony\Component\Console\Output\ConsoleOutput))
#35 phar:///phpstan.phar/bin/phpstan(96): _PHPStan_0a43b4828\Symfony\Component\Console\Application->run()
#36 phar:///phpstan.phar/bin/phpstan(97): _PHPStan_0a43b4828\{closure}()
#37 /phpstan(8): require('phar:///Volumes...')
#38 /example-app/vendor/bin/phpstan(120): include('/Volumes/code/w...')
#39 {main}
```

Looking at PHPStan releases, release 1.7.0 (https://github.com/phpstan/phpstan/releases/tag/1.7.0) has this item:
* Native reflection is always BetterReflection adapter (https://github.com/phpstan/phpstan-src/commit/ef603397df6036647f6b030407b3316159dc330f)

Which it looks like in the error above, it's looking for a BetterReflection version of ReflectionParameter, but only getting the base ReflectionParameter.

You can confirm it's the change in this version by downgrading to 1.6.9:
```bash
composer require --dev phpstan/phpstan:1.6.9 nunomaduro/larastan:v2.1.5 phpstan/extension-installer:1.1.0
```
And now phpstan works.

I attempt to clone larastan and add a parameter to the CarbonExtension test, but that did not cause it to fail. Sorry, I'm not sure why. I attempted to xdebug the issue, but couldn't figure out how to make the test fail. I'm not sure what differences there are between a real laravel app and the test code. That's why I added the steps to reproduce with the `example-app`.

Let me know if you have any questions! Thank you!

**Comment by canvural** [comment]
Hi,

This was interesting to debug. I'm still not 100% sure, but I think the issue comes from Carbon not Larastan. Carbon also has it's own [PHPStan extension](https://github.com/briannesbitt/Carbon/blob/d61ab7436faa6d811568937682e184ef8e740775/src/Carbon/PHPStan/MacroExtension.php). And if I test your scenario just with Larastan (remove `phpstan/extension-installer` so Carbon's extension is not automatically installed) it works.

Also I think that's the reason why you can't reproduce it in the tests. I also couldn't.

So please open an issue in Carbon repository.
