### ISSUE TITLE
undefined method PHPStan\Type\UnionType::getClassName() on MorphTo

### ISSUE THREAD

**Issue by AJenbo** [nunomaduro/larastan#1557]
- Larastan Version: 2.4.1
- `--level` used: 9

### Description
Got a crash when analyzing a morphto relation with multiple possible morphs

### Laravel code where the issue was found

```php
class Popular extends Model
{
    /**
     * @return MorphTo<Brand|Category|Subcategory, self>
     */
    public function popularized(): MorphTo
    {
        return $this->morphTo();
    }
}
```

PHPStan - PHP Static Analysis Tool 1.10.2

            "name": "nunomaduro/larastan",
            "version": "2.4.1",

**Comment by canvural** [comment]
Hi, the correct return type should be `MorphTo<Brand|Category|Subcategory, Popular>` Can you try it if it solves the issue?

**Comment by canvural** [comment]
Can you post the stack trace too? You can get it by running PHPStan with - -debug and - vvv

**Comment by AJenbo** [comment]
```
/home/ajenbo/code/luxplus/monorepo/packages/luxplus/shared/src/database/Model/Products/PopularInX.php
Uncaught Error: Call to undefined method PHPStan\Type\UnionType::getClassName() in /home/ajenbo/code/luxplus/monorepo/packages/luxplus/shared/vendor/nunomaduro/larastan/src/Properties/ModelRelationsExtension.php:86
#0 phar:///home/ajenbo/code/luxplus/monorepo/packages/luxplus/shared/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ClassReflection.php(550): NunoMaduro\Larastan\Properties\ModelRelationsExtension->getProperty()
#1 phar:///home/ajenbo/code/luxplus/monorepo/packages/luxplus/shared/vendor/phpstan/phpstan/phpstan.phar/src/Type/ObjectType.php(187): PHPStan\Reflection\ClassReflection->getProperty()
#2 phar:///home/ajenbo/code/luxplus/monorepo/packages/luxplus/shared/vendor/phpstan/phpstan/phpstan.phar/src/Type/StaticType.php(213): PHPStan\Type\ObjectType->getUnresolvedPropertyPrototype()
#3 phar:///home/ajenbo/code/luxplus/monorepo/packages/luxplus/shared/vendor/phpstan/phpstan/phpstan.phar/src/Type/StaticType.php(208): PHPStan\Type\StaticType->getUnresolvedPropertyPrototype()
#4 phar:///home/ajenbo/code/luxplus/monorepo/packages/luxplus/shared/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(3387): PHPStan\Type\StaticType->getProperty()
#5 phar:///home/ajenbo/code/luxplus/monorepo/packages/luxplus/shared/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(3394): PHPStan\Analyser\MutatingScope->getPropertyReflection()
#6 phar:///home/ajenbo/code/luxplus/monorepo/packages/luxplus/shared/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1399): PHPStan\Analyser\MutatingScope->propertyFetchType()
#7 phar:///home/ajenbo/code/luxplus/monorepo/packages/luxplus/shared/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1405): PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}()
#8 phar:///home/ajenbo/code/luxplus/monorepo/packages/luxplus/shared/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(556): PHPStan\Analyser\MutatingScope->resolveType()
#9 phar:///home/ajenbo/code/luxplus/monorepo/packages/luxplus/shared/vendor/phpstan/phpstan/phpstan.phar/src/Rules/FunctionCallParametersCheck.php(114): PHPStan\Analyser\MutatingScope->getType()
#10 phar:///home/ajenbo/code/luxplus/monorepo/packages/luxplus/shared/vendor/phpstan/phpstan/phpstan.phar/src/Rules/Functions/CallToFunctionParametersRule.php(46): PHPStan\Rules\FunctionCallParametersCheck->check()
#11 phar:///home/ajenbo/code/luxplus/monorepo/packages/luxplus/shared/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(106): PHPStan\Rules\Functions\CallToFunctionParametersRule->processNode()
#12 phar:///home/ajenbo/code/luxplus/monorepo/packages/luxplus/shared/vendor/phpstan/phpstan/phpstan.phar/src/Node/ClassStatementsGatherer.php(98): PHPStan\Analyser\FileAnalyser->PHPStan\Analyser\{closure}()
#13 phar:///home/ajenbo/code/luxplus/monorepo/packages/luxplus/shared/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(511): PHPStan\Node\ClassStatementsGatherer->__invoke()
#14 phar:///home/ajenbo/code/luxplus/monorepo/packages/luxplus/shared/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(2484): PHPStan\Analyser\NodeScopeResolver::PHPStan\Analyser\{closure}()
#15 phar:///home/ajenbo/code/luxplus/monorepo/packages/luxplus/shared/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1477): PHPStan\Analyser\NodeScopeResolver->callNodeCallbackWithExpression()
#16 phar:///home/ajenbo/code/luxplus/monorepo/packages/luxplus/shared/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(995): PHPStan\Analyser\NodeScopeResolver->processExprNode()
#17 phar:///home/ajenbo/code/luxplus/monorepo/packages/luxplus/shared/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(365): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#18 phar:///home/ajenbo/code/luxplus/monorepo/packages/luxplus/shared/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(526): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()
#19 phar:///home/ajenbo/code/luxplus/monorepo/packages/luxplus/shared/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(365): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#20 phar:///home/ajenbo/code/luxplus/monorepo/packages/luxplus/shared/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(604): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()
#21 phar:///home/ajenbo/code/luxplus/monorepo/packages/luxplus/shared/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(365): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#22 phar:///home/ajenbo/code/luxplus/monorepo/packages/luxplus/shared/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(576): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()
#23 phar:///home/ajenbo/code/luxplus/monorepo/packages/luxplus/shared/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(332): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#24 phar:///home/ajenbo/code/luxplus/monorepo/packages/luxplus/shared/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(175): PHPStan\Analyser\NodeScopeResolver->processNodes()
#25 phar:///home/ajenbo/code/luxplus/monorepo/packages/luxplus/shared/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/Analyser.php(72): PHPStan\Analyser\FileAnalyser->analyseFile()
#26 phar:///home/ajenbo/code/luxplus/monorepo/packages/luxplus/shared/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyserRunner.php(62): PHPStan\Analyser\Analyser->analyse()
#27 phar:///home/ajenbo/code/luxplus/monorepo/packages/luxplus/shared/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseApplication.php(209): PHPStan\Command\AnalyserRunner->runAnalyser()
#28 phar:///home/ajenbo/code/luxplus/monorepo/packages/luxplus/shared/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseApplication.php(102): PHPStan\Command\AnalyseApplication->runAnalyser()
#29 phar:///home/ajenbo/code/luxplus/monorepo/packages/luxplus/shared/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseCommand.php(174): PHPStan\Command\AnalyseApplication->analyse()
#30 phar:///home/ajenbo/code/luxplus/monorepo/packages/luxplus/shared/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(259): PHPStan\Command\AnalyseCommand->execute()
#31 phar:///home/ajenbo/code/luxplus/monorepo/packages/luxplus/shared/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(870): _PHPStan_eb00fd21c\Symfony\Component\Console\Command\Command->run()
#32 phar:///home/ajenbo/code/luxplus/monorepo/packages/luxplus/shared/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(261): _PHPStan_eb00fd21c\Symfony\Component\Console\Application->doRunCommand()
#33 phar:///home/ajenbo/code/luxplus/monorepo/packages/luxplus/shared/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(157): _PHPStan_eb00fd21c\Symfony\Component\Console\Application->doRun()
#34 phar:///home/ajenbo/code/luxplus/monorepo/packages/luxplus/shared/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(124): _PHPStan_eb00fd21c\Symfony\Component\Console\Application->run()
#35 phar:///home/ajenbo/code/luxplus/monorepo/packages/luxplus/shared/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(125): _PHPStan_eb00fd21c\{closure}()
#36 /home/ajenbo/code/luxplus/monorepo/packages/luxplus/shared/vendor/phpstan/phpstan/phpstan(8): require('...')
#37 /home/ajenbo/code/luxplus/monorepo/packages/luxplus/shared/vendor/bin/phpstan(120): include('...')
#38 {main}

```

**Comment by szepeviktor** [comment]
@canvural Great work.

# 🚀

**Comment by pindab0ter** [comment]
For me it doesn’t crash, but tells me it returns `MorphTo<Model, User>` instead of what I specified (e.g. `MorphTo<Foo|Bar, User>`. Should I open a new issue, or am I missing something?

PHPStan 1.10.55, Larastan 2.8.0.

**Comment by canvural** [comment]
@pindab0ter Please open a new issue and show as much code as possible.
