### ISSUE TITLE
Call to undefined function NunoMaduro\Larastan\ReturnTypes\now() 

### ISSUE THREAD

**Issue by mittt** [nunomaduro/larastan#1637]
- Larastan Version: ^2.6
- "phpstan/phpstan": "^1.10.14",
- "laravel/lumen-framework": "^10.0.0"
- `--level` used: 8

### Description
Getting two similar internal errors.

**The first:** 

```
Internal error: Internal error: Call to undefined function NunoMaduro\Larastan\ReturnTypes\now() in file /app/app/Util/DiscountManager.php
     Post the following stack trace to https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md:
     #0 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(3378): NunoMaduro\Larastan\ReturnTypes\DateExtension->getTypeFromStaticMethodCall(Object(PHPStan\Reflection\ResolvedMethodReflection), Object(PhpParser\Node\Expr\StaticCall), Object(PHPStan\Analyser\MutatingScope))
     #1 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1397): PHPStan\Analyser\MutatingScope->methodCallReturnType(Object(PHPStan\Type\ObjectType), 'now', Object(PhpParser\Node\Expr\StaticCall))
```

In /app/app/Util/DiscountManager.php we have a call like this:
```php
use Illuminate\Support\Facades\{Date, Log};
...
Date::now()->toDateTimeString()
```

**And the second:**

```
Internal error: Internal error: Call to undefined function NunoMaduro\Larastan\ReturnTypes\now() in file /app/app/Util/Date.php
     Post the following stack trace to https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md:
     #0 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(3378): NunoMaduro\Larastan\ReturnTypes\DateExtension->getTypeFromStaticMethodCall(Object(PHPStan\Reflection\ResolvedMethodReflection), Object(PhpParser\Node\Expr\StaticCall), Object(PHPStan\Analyser\MutatingScope))
     #1 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1397): PHPStan\Analyser\MutatingScope->methodCallReturnType(Object(PHPStan\Type\ObjectType), 'createFromTimes...', Object(PhpParser\Node\Expr\StaticCall))
```

In /app/app/Util/Date.php:
```php
use Illuminate\Support\Facades\Date as DateFacade;
...
DateFacade::createFromTimestamp($timestamp)
```

**Comment by szepeviktor** [comment]
Could originate from here
https://github.com/nunomaduro/larastan/blob/ccac5b25949576807862cf32ba1fce1769c06c42/src/ReturnTypes/DateExtension.php#L45

**Comment by szepeviktor** [comment]
Thank you for your report!

Could it be that your setup does not have the `now()` global function?

**Comment by canvural** [comment]
Hi, 

Lumen is not supported by Larastan.
