### ISSUE TITLE
Undefined constant LARAVEL_VERSION when loading PHPStan/Larastan in Rector

### ISSUE THREAD

**Issue by stefandoorn** [nunomaduro/larastan#1664]
- Larastan Version: v2.6.2
- Rector Version: v0.17.0

Running PHPStan works fine, but running it through `Rector` I get this error.

Rector config loads PHPStan config:

```php
$config->phpstanConfig(__DIR__ . '/phpstan.neon.dist');
```

PHPStan loads Larastan:

```neon
includes:
    - ./vendor/nunomaduro/larastan/extension.neon
```

Works fine: `./vendor/bin/phpstan analyse`

Error: `./vendor/bin/rector process`

Error output below. I do see that in `bootstrap.php` a LARAVEL_VERSION is set derived from `$app->version()`. Somehow loading this config through Rector does something where - I assume - bootstrap is not being processed.

Tried to debug this a bit, but I'm a bit stuck on how this works.

I'm slightly in doubt whether this is more of a Rector issue or a Larastan issue.. removing the config does make Rector work again, but with less rules of course. I'll file the issue as well in there.

```
[ERROR] Could not process "/var/www/html/app/Filters/Single/BelongsToFilter.php" file, due to:                 
         "System error: "Undefined constant "NunoMaduro\Larastan\ReturnTypes\LARAVEL_VERSION""                          
                                                                                                                        
Stack trace:                                                                                                   
#0 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(3364):       
NunoMaduro\Larastan\ReturnTypes\CollectionGenericStaticMethodDynamicMethodReturnTypeExtension->isMethodSupported()                                                                                                           
#1 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1356):       
PHPStan\Analyser\MutatingScope->methodCallReturnType()                                                         
#2 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1362):       
PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}()                                                   
#3 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(558):        
PHPStan\Analyser\MutatingScope->resolveType()                                                                  
#4 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(2412):   
PHPStan\Analyser\MutatingScope->getType()                                                                      
#5 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1711):   
PHPStan\Analyser\NodeScopeResolver->getMethodThrowPoint()                                                      
#6 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(546):    
PHPStan\Analyser\NodeScopeResolver->processExprNode()                                                          
#7 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(362):    
PHPStan\Analyser\NodeScopeResolver->processStmtNode()                                                          
#8 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(531):    
PHPStan\Analyser\NodeScopeResolver->processStmtNodes()                                                         
#9 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(362):    
PHPStan\Analyser\NodeScopeResolver->processStmtNode()                                                          
#10 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(609):   
PHPStan\Analyser\NodeScopeResolver->processStmtNodes()                                                         
#11 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(362):   
PHPStan\Analyser\NodeScopeResolver->processStmtNode()                                                          
#12 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(581):   
PHPStan\Analyser\NodeScopeResolver->processStmtNodes()                                                         
#13 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(331):   
PHPStan\Analyser\NodeScopeResolver->processStmtNode()                                                          
#14 vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php(332):            
PHPStan\Analyser\NodeScopeResolver->processNodes()                                                             
#15 vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php(215):            
Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->processNodesWithDependentFiles()               
#16 vendor/rector/rector/packages/NodeTypeResolver/NodeScopeAndMetadataDecorator.php(41):                      
Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->processNodes()                                 
#17 vendor/rector/rector/src/Application/FileProcessor.php(54):                                                
Rector\NodeTypeResolver\NodeScopeAndMetadataDecorator->decorateNodesFromFile()                                 
#18 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(165):                              
Rector\Core\Application\FileProcessor->parseFileInfoToLocalCache()                                             
#19 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(104):                              
Rector\Core\Application\FileProcessor\PhpFileProcessor->parseFileAndDecorateNodes()                            
#20 vendor/rector/rector/packages/Parallel/WorkerRunner.php(144):                                              
Rector\Core\Application\FileProcessor\PhpFileProcessor->process()                                              
#21 vendor/rector/rector/packages/Parallel/WorkerRunner.php(114): Rector\Parallel\WorkerRunner->processFile()  
#22 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                   
Rector\Parallel\WorkerRunner->Rector\Parallel\{closure}()                                                      
#23 vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(117):                                        
RectorPrefix202306\Evenement\EventEmitter->emit()                                                              
#24 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                   
RectorPrefix202306\Clue\React\NDJson\Decoder->handleData()                                                     
#25 vendor/rector/rector/vendor/react/stream/src/Util.php(62):                                                 
RectorPrefix202306\Evenement\EventEmitter->emit()                                                              
#26 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                   
RectorPrefix202306\React\Stream\Util::RectorPrefix202306\React\Stream\{closure}()                              
#27 vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(154):                                
RectorPrefix202306\Evenement\EventEmitter->emit()                                                              
#28 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201):                                
RectorPrefix202306\React\Stream\DuplexResourceStream->handleData()                                             
#29 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173):                                
RectorPrefix202306\React\EventLoop\StreamSelectLoop->waitForStreamActivity()                                   
#30 vendor/rector/rector/src/Console/Command/WorkerCommand.php(63):                                            
RectorPrefix202306\React\EventLoop\StreamSelectLoop->run()                                                     
#31 vendor/rector/rector/vendor/symfony/console/Command/Command.php(325):                                      
Rector\Core\Console\Command\WorkerCommand->execute()                                                           
#32 vendor/rector/rector/vendor/symfony/console/Application.php(944):                                          
RectorPrefix202306\Symfony\Component\Console\Command\Command->run()                                            
#33 vendor/rector/rector/vendor/symfony/console/Application.php(326):                                          
RectorPrefix202306\Symfony\Component\Console\Application->doRunCommand()                                       
#34 vendor/rector/rector/src/Console/ConsoleApplication.php(49):                                               
RectorPrefix202306\Symfony\Component\Console\Application->doRun()                                              
#35 vendor/rector/rector/vendor/symfony/console/Application.php(212):                                          
Rector\Core\Console\ConsoleApplication->doRun()                                                                
#36 vendor/rector/rector/bin/rector.php(132): RectorPrefix202306\Symfony\Component\Console\Application->run()  
#37 vendor/rector/rector/bin/rector(5): require_once('...')                                                    
#38 vendor/bin/rector(120): include('...')                                                                     
#39 {main}". On line: 47                                                                                      
```

**Comment by stefandoorn** [comment]
To add, this started in an upgrade where this happens. Before that it did work without error.

```
laravel/framework ^v9.0 -> ^v10.0
rector/rector ^0.14 -> ^0.17
Installed driftingly/rector-laravel at ^0.20
```

**Comment by stefandoorn** [comment]
The change in #1665 looked promising, but:

```
"System error: "Undefined constant "LARAVEL_VERSION""
```

So I'm kind of afraid that the `bootstrap.php` somehow is not loaded..

**Comment by szepeviktor** [comment]
Hello 👋🏻 

We have bootstrap.php in extension.neon:

https://github.com/nunomaduro/larastan/blob/73e5be5f5c732212ce6ca77ffd2753a136f36a23/extension.neon#L12-L13

**Comment by szepeviktor** [comment]
What if you temporarily move this to the top of the file?

https://github.com/nunomaduro/larastan/blob/73e5be5f5c732212ce6ca77ffd2753a136f36a23/bootstrap.php#L31-L33

**Comment by stefandoorn** [comment]
Indeed... and I'm loading the `extension.neon`:

```
includes:
    - phpstan-baseline-laravel9.neon
    - phpstan-baseline-laravel10.neon
    - ./vendor/nunomaduro/larastan/extension.neon
    - ./vendor/phpstan/phpstan-webmozart-assert/extension.neon
```

I checked, but none of these have parameters or other bootstrapFiles..

**Comment by stefandoorn** [comment]
> What if you temporarily add this to the top of bootstrap.php?
> 
> `define('LARAVEL_VERSION', '9.0');`

This does not make a difference :-(

**Comment by szepeviktor** [comment]
Oh no!
So bootstrap.php is not executed :(

**Comment by szepeviktor** [comment]
Rector must have _rectored_ it out!

**Comment by stefandoorn** [comment]
Hahahah :-) Yep.

**Comment by szepeviktor** [comment]
@tomasvotruba Could you hop in?

**Comment by TomasVotruba** [comment]
@szepeviktor Not really sure how Laravel extension work. It would be helpful to have the breaking Rector commit :)

**Comment by canvural** [comment]
I've never had this problem with Rector.

Maybe you need to give Rector the bootstrap path instead of PHPStan config: `$config->bootstrapFile([__DIR__ . '/vendor/nunomaduro/larastan/bootstrap.php']);`
