### ISSUE TITLE
Method newEloquentBuilder() was not found in reflection

### ISSUE THREAD

**Issue by ya-cha** [nunomaduro/larastan#1686]
- Larastan Version: 2.6.3
- `--level` used: `max`

### Description

When updating from 2.6.2 to 2.6.3 this error message suddenly occured: 
```
Internal error: Internal error: Method newEloquentBuilder() was not found in reflection of class App\Models\Contracts\SearchableInterface. in file /var/www/html/app/Service/Search/ModelSearch.php
```

### Laravel code where the issue was found

```php
public function search(string $search): Collection
{
    $models = $this->modelClassFinder->implementing(SearchableInterface::class);

    $searchResult = collect();

    /** @var SearchableInterface&Model $model */
    foreach ($models as $model) {
        $searchResult = $searchResult->merge(
            $this->whereLikeEngine->search($model::query(), $model::searchInFields(), $search)->limit(10)->get()
        );
    }

    return $searchResult;
}
```

The `SearchableInterface` looks like this:

```php
interface SearchableInterface
{
    /** @return array<string> */
    public static function searchInFields(): array;

    public function getSearchResultDescription(): string;
}
```

**Comment by szepeviktor** [comment]
Maybe related to #1663

**Comment by szepeviktor** [comment]
What if you write `/** @var Model&SearchableInterface $model */` ?

**Comment by ya-cha** [comment]
Still the same with `Model&SearchableInterface`

**Comment by ya-cha** [comment]
If it helps, this is the stack trace: 
```
#0 /var/www/html/vendor/nunomaduro/larastan/src/Methods/BuilderHelper.php(199): PHPStan\Reflection\ClassReflection->getNativeMethod()                                                                         
     #1 /var/www/html/vendor/nunomaduro/larastan/src/ReturnTypes/ModelDynamicStaticMethodReturnTypeExtension.php(107): NunoMaduro\Larastan\Methods\BuilderHelper->determineBuilderName()                           
     #2 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(3450): NunoMaduro\Larastan\ReturnTypes\ModelDynamicStaticMethodReturnTypeExtension->getTypeFromStaticMethodCall()  
     #3 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1406): PHPStan\Analyser\MutatingScope->methodCallReturnType()                                                      
     #4 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1412): PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}()                                                
     #5 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(561): PHPStan\Analyser\MutatingScope->resolveType()                                                                
     #6 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Rules/FunctionCallParametersCheck.php(114): PHPStan\Analyser\MutatingScope->getType()                                                         
     #7 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Rules/Methods/CallMethodsRule.php(48): PHPStan\Rules\FunctionCallParametersCheck->check()                                                     
     #8 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(104): PHPStan\Rules\Methods\CallMethodsRule->processNode()                                                          
     #9 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Node/ClassStatementsGatherer.php(108): PHPStan\Analyser\FileAnalyser->PHPStan\Analyser\{closure}()                                            
     #10 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(538): PHPStan\Node\ClassStatementsGatherer->__invoke()                                                        
     #11 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(2625): PHPStan\Analyser\NodeScopeResolver::PHPStan\Analyser\{closure}()                                       
     #12 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1564): PHPStan\Analyser\NodeScopeResolver->callNodeCallbackWithExpression()                                   
     #13 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1725): PHPStan\Analyser\NodeScopeResolver->processExprNode()                                                  
     #14 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1725): PHPStan\Analyser\NodeScopeResolver->processExprNode()                                                  
     #15 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(2898): PHPStan\Analyser\NodeScopeResolver->processExprNode()                                                  
     #16 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1753): PHPStan\Analyser\NodeScopeResolver->processArgs()                                                      
     #17 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1579): PHPStan\Analyser\NodeScopeResolver->processExprNode()                                                  
     #18 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(2924): PHPStan\Analyser\NodeScopeResolver->PHPStan\Analyser\{closure}()                                       
     #19 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1572): PHPStan\Analyser\NodeScopeResolver->processAssignVar()                                                 
     #20 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(593): PHPStan\Analyser\NodeScopeResolver->processExprNode()                                                   
     #21 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(383): PHPStan\Analyser\NodeScopeResolver->processStmtNode()                                                   
     #22 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(776): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()                                                  
     #23 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(383): PHPStan\Analyser\NodeScopeResolver->processStmtNode()                                                   
     #24 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(537): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()                                                  
     #25 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(383): PHPStan\Analyser\NodeScopeResolver->processStmtNode()                                                   
     #26 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(634): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()                                                  
     #27 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(383): PHPStan\Analyser\NodeScopeResolver->processStmtNode()                                                   
     #28 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(606): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()                                                  
     #29 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(352): PHPStan\Analyser\NodeScopeResolver->processStmtNode()                                                   
     #30 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(173): PHPStan\Analyser\NodeScopeResolver->processNodes()                                                           
     #31 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Command/WorkerCommand.php(130): PHPStan\Analyser\FileAnalyser->analyseFile()                                                                 
     #32 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97): PHPStan\Command\WorkerCommand->PHPStan\Command\{closure}()                   
     #33 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/clue/ndjson-react/src/Decoder.php(117): _PHPStan_690619d82\Evenement\EventEmitter->emit()                                                 
     #34 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97): _PHPStan_690619d82\Clue\React\NDJson\Decoder->handleData()                   
     #35 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/react/stream/src/Util.php(62): _PHPStan_690619d82\Evenement\EventEmitter->emit()                                                          
     #36 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                                                                              
     _PHPStan_690619d82\React\Stream\Util::_PHPStan_690619d82\React\Stream\{closure}()                                                                                                                             
     #37 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/react/stream/src/DuplexResourceStream.php(154): _PHPStan_690619d82\Evenement\EventEmitter->emit()                                         
     #38 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/react/event-loop/src/StreamSelectLoop.php(201): _PHPStan_690619d82\React\Stream\DuplexResourceStream->handleData()                        
     #39 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/react/event-loop/src/StreamSelectLoop.php(173): _PHPStan_690619d82\React\EventLoop\StreamSelectLoop->waitForStreamActivity()              
     #40 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Command/WorkerCommand.php(96): _PHPStan_690619d82\React\EventLoop\StreamSelectLoop->run()                                                    
     #41 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(259): PHPStan\Command\WorkerCommand->execute()                                                        
     #42 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(870): _PHPStan_690619d82\Symfony\Component\Console\Command\Command->run()                                 
     #43 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(261): _PHPStan_690619d82\Symfony\Component\Console\Application->doRunCommand()                            
     #44 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(157): _PHPStan_690619d82\Symfony\Component\Console\Application->doRun()                                   
     #45 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(122): _PHPStan_690619d82\Symfony\Component\Console\Application->run()                                                                
     #46 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(123): _PHPStan_690619d82\{closure}()                                                                                                 
     #47 /var/www/html/vendor/phpstan/phpstan/phpstan(8): require('...')                                                                                                                                           
     #48 /var/www/html/vendor/bin/phpstan(119): include('...')                                                                                                                                                     
     #49 {main}                                                                                                                                          
```

**Comment by ya-cha** [comment]
`[OK] No errors` 🥳

**Comment by ya-cha** [comment]
Thanks a lot for your support ❤️

**Comment by szepeviktor** [comment]
Glad to help.
