### ISSUE TITLE
Internal error: Dynamic model properties with underscores cannot be used

### ISSUE THREAD

**Issue by Brenneisen** [nunomaduro/larastan#1790]
- Larastan Version: 2.6.5
- `--level` used: 0
- Pull request with failing test: https://github.com/larastan/larastan/pull/1792

### Description

After updating to 2.6.5, the analysis fails with an internal error:

Internal error: Internal error: Method __test() was not found in reflection of class App\Models\Model. while analysing file /app/Test.php  

### Laravel code where the issue was found

```php

$foo = new App\Models\Model;

$foo->__test = 'bar';

```

**Comment by canvural** [comment]
Hi,

Can you give more examples? How is the actual attribute is defined?

**Comment by Brenneisen** [comment]
Hi,

the attribute "__test" is not defined in the model and is set as a dynamic property. It works without the underscores:

```php

$foo = new App\Models\Model;

$foo->test = 'bar';

```

**Comment by canvural** [comment]
Can you run `phpstan` with `--debug` flag and post the stacktrace?

**Comment by Brenneisen** [comment]
Yes, of course:

```
/app/Test.php
Uncaught PHPStan\Reflection\MissingMethodFromReflectionException: Method __test() was not found in reflection of class App\Models\Model. in phar:///vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ClassReflection.php:495
#0 /vendor/nunomaduro/larastan/src/Properties/ModelRelationsExtension.php(81): PHPStan\Reflection\ClassReflection->getMethod()
#1 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ClassReflection.php(591): NunoMaduro\Larastan\Properties\ModelRelationsExtension->getProperty()
#2 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Type/ObjectType.php(185): PHPStan\Reflection\ClassReflection->getProperty()
#3 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Type/ObjectType.php(148): PHPStan\Type\ObjectType->getUnresolvedPropertyPrototype()
#4 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(3588): PHPStan\Type\ObjectType->getProperty()
#5 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(3595): PHPStan\Analyser\MutatingScope->getPropertyReflection()
#6 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1461): PHPStan\Analyser\MutatingScope->propertyFetchType()
#7 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1467): PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}()
#8 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(574): PHPStan\Analyser\MutatingScope->resolveType()
#9 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Dependency/DependencyResolver.php(252): PHPStan\Analyser\MutatingScope->getType()
#10 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(149): PHPStan\Dependency\DependencyResolver->resolveDependencies()
#11 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Node/ClassStatementsGatherer.php(108): PHPStan\Analyser\FileAnalyser->PHPStan\Analyser\{closure}()
#12 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(568): PHPStan\Node\ClassStatementsGatherer->__invoke()
#13 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(2996): PHPStan\Analyser\NodeScopeResolver::PHPStan\Analyser\{closure}()
#14 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1628): PHPStan\Analyser\NodeScopeResolver->processAssignVar()
#15 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(628): PHPStan\Analyser\NodeScopeResolver->processExprNode()
#16 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(402): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#17 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(586): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()
#18 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(402): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#19 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(669): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()
#20 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(402): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#21 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(641): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()
#22 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(371): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#23 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(166): PHPStan\Analyser\NodeScopeResolver->processNodes()
#24 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/Analyser.php(72): PHPStan\Analyser\FileAnalyser->analyseFile()
#25 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyserRunner.php(62): PHPStan\Analyser\Analyser->analyse()
#26 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseApplication.php(209): PHPStan\Command\AnalyserRunner->runAnalyser()
#27 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseApplication.php(101): PHPStan\Command\AnalyseApplication->runAnalyser()
#28 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseCommand.php(198): PHPStan\Command\AnalyseApplication->analyse()
#29 phar:///vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(259): PHPStan\Command\AnalyseCommand->execute()
#30 phar:///vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(870): _PHPStan_4c4f22f13\Symfony\Component\Console\Command\Command->run()
#31 phar:///vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(261): _PHPStan_4c4f22f13\Symfony\Component\Console\Application->doRunCommand()
#32 phar:///vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(157): _PHPStan_4c4f22f13\Symfony\Component\Console\Application->doRun()
#33 phar:///vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(124): _PHPStan_4c4f22f13\Symfony\Component\Console\Application->run()
#34 phar:///vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(125): _PHPStan_4c4f22f13\{closure}()
#35 /vendor/phpstan/phpstan/phpstan(8): require('...')
#36 /vendor/bin/phpstan(119): include('...')
#37 {main}
```

**Comment by Brenneisen** [comment]
@canvural I have added a PR that fixes the issue.

**Comment by Brenneisen** [comment]
@canvural Is there anything else I can do? I don't think the failed tests have anything to do with my PR.
