### ISSUE TITLE
Exception in CollectionFilterDynamicReturnTypeExtension

### ISSUE THREAD

**Issue by DumbergerL** [nunomaduro/larastan#1818]
- Larastan Version: 2.0.
- `--level` used: 5

### Description

I get an ` Internal error` while i execute larastan.

### Laravel code where the issue was found

I get an internal error while testing this code:

```php
class AttachableService
{
    public static function getFilesMissingOnDisk(): Collection
    {
        return File::all()->filter(function (File $file) {
            return !Storage::exists($file->file_path);
        });
    }
}
```

Stacktrace:
```
## phar://C:/project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(2468)
#0 C:\project\vendor\larastan\larastan\src\ReturnTypes\CollectionFilterDynamicReturnTypeExtension.php(90): PHPStan\Analyser\MutatingScope->assignVariable('file', Object(PHPStan\Type\ObjectType))
#1 phar://C:/project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(3598):
NunoMaduro\Larastan\ReturnTypes\CollectionFilterDynamicReturnTypeExtension->getTypeFromMethodCall(Object(PHPStan\Reflection\ResolvedMethodReflection), Object(PhpParser\Node\Expr\MethodCall),
Object(PHPStan\Analyser\MutatingScope))
#2 phar://C:/project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1404): PHPStan\Analyser\MutatingScope->methodCallReturnType(Object(PHPStan\Type\Generic\GenericObjectType), 'filter',
Object(PhpParser\Node\Expr\MethodCall))
#3 phar://C:/project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1410): PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}()
#4 phar://C:/project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(575): PHPStan\Analyser\MutatingScope->resolveType('\\App\\File::all(...', Object(PhpParser\Node\Expr\MethodCall))
#5 phar://C:/project/vendor/phpstan/phpstan/phpstan.phar/src/Rules/FunctionReturnTypeCheck.php(52): PHPStan\Analyser\MutatingScope->getType(Object(PhpParser\Node\Expr\MethodCall))
#6 phar://C:/project/vendor/phpstan/phpstan/phpstan.phar/src/Rules/Methods/ReturnTypeRule.php(43): PHPStan\Rules\FunctionReturnTypeCheck->checkReturnType(Object(PHPStan\Analyser\MutatingScope),
Object(PHPStan\Type\ObjectType), Object(PhpParser\Node\Expr\MethodCall), Object(PhpParser\Node\Stmt\Return_), 'Method App\\Serv...', 'Method App\\Serv...', 'Method App\\Serv...', 'Method App\\Serv...', false)
#7 phar://C:/project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(107): PHPStan\Rules\Methods\ReturnTypeRule->processNode(Object(PhpParser\Node\Stmt\Return_), Object(PHPStan\Analyser\MutatingScope))   
#8 phar://C:/project/vendor/phpstan/phpstan/phpstan.phar/src/Node/ClassStatementsGatherer.php(108): PHPStan\Analyser\FileAnalyser->PHPStan\Analyser\{closure}(Object(PhpParser\Node\Stmt\Return_),
Object(PHPStan\Analyser\MutatingScope))
#9 phar://C:/project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(567): PHPStan\Node\ClassStatementsGatherer->__invoke(Object(PhpParser\Node\Stmt\Return_),
Object(PHPStan\Analyser\MutatingScope))
#10 phar://C:/project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(458): PHPStan\Analyser\NodeScopeResolver::PHPStan\Analyser\{closure}(Object(PhpParser\Node\Stmt\Return_),
Object(PHPStan\Analyser\MutatingScope))
#11 phar://C:/project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(401): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Return_),
Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\StatementContext))
#12 phar://C:/project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(585): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\ClassMethod), Array,
Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\StatementContext))
#13 phar://C:/project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(401): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\ClassMethod),
Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer), Object(PHPStan\Analyser\StatementContext))
#14 phar://C:/project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(668): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Class_), Array,
Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer), Object(PHPStan\Analyser\StatementContext))
#15 phar://C:/project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(401): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Class_),
Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\StatementContext))
#16 phar://C:/project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(640): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Namespace_), Array,
Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\StatementContext))
#17 phar://C:/project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(370): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Namespace_),
Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\StatementContext))
#18 phar://C:/project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(166): PHPStan\Analyser\NodeScopeResolver->processNodes(Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#19 phar://C:/project/vendor/phpstan/phpstan/phpstan.phar/src/Command/WorkerCommand.php(132): PHPStan\Analyser\FileAnalyser->analyseFile('C:\\project\\app...', Array, Object(PHPStan\Rules\LazyRegistry),
Object(PHPStan\Collectors\Registry), NULL)
#20 phar://C:/project/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97): PHPStan\Command\WorkerCommand->PHPStan\Command\{closure}(Array)
#21 phar://C:/project/vendor/phpstan/phpstan/phpstan.phar/vendor/clue/ndjson-react/src/Decoder.php(117): _PHPStan_3d4486d07\Evenement\EventEmitter->emit('data', Array)
#22 phar://C:/project/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97): _PHPStan_3d4486d07\Clue\React\NDJson\Decoder->handleData(Array)
#23 phar://C:/project/vendor/phpstan/phpstan/phpstan.phar/vendor/react/stream/src/Util.php(62): _PHPStan_3d4486d07\Evenement\EventEmitter->emit('data', Array)
#24 phar://C:/project/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):
_PHPStan_3d4486d07\React\Stream\Util::_PHPStan_3d4486d07\React\Stream\{closure}('{"action":"anal...')
#25 phar://C:/project/vendor/phpstan/phpstan/phpstan.phar/vendor/react/stream/src/DuplexResourceStream.php(154): _PHPStan_3d4486d07\Evenement\EventEmitter->emit('data', Array)
#26 phar://C:/project/vendor/phpstan/phpstan/phpstan.phar/vendor/react/event-loop/src/StreamSelectLoop.php(201): _PHPStan_3d4486d07\React\Stream\DuplexResourceStream->handleData(Resource id #5434)
#27 phar://C:/project/vendor/phpstan/phpstan/phpstan.phar/vendor/react/event-loop/src/StreamSelectLoop.php(173): _PHPStan_3d4486d07\React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)
#28 phar://C:/project/vendor/phpstan/phpstan/phpstan.phar/src/Command/WorkerCommand.php(98): _PHPStan_3d4486d07\React\EventLoop\StreamSelectLoop->run()
#29 phar://C:/project/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(259): PHPStan\Command\WorkerCommand->execute(Object(_PHPStan_3d4486d07\Symfony\Component\Console\Input\ArgvInput),       
Object(_PHPStan_3d4486d07\Symfony\Component\Console\Output\ConsoleOutput))
#30 phar://C:/project/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(870):
_PHPStan_3d4486d07\Symfony\Component\Console\Command\Command->run(Object(_PHPStan_3d4486d07\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_3d4486d07\Symfony\Component\Console\Output\ConsoleOutput))
#31 phar://C:/project/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(261): _PHPStan_3d4486d07\Symfony\Component\Console\Application->doRunCommand(Object(PHPStan\Command\WorkerCommand),
Object(_PHPStan_3d4486d07\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_3d4486d07\Symfony\Component\Console\Output\ConsoleOutput))
#32 phar://C:/project/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(157):
_PHPStan_3d4486d07\Symfony\Component\Console\Application->doRun(Object(_PHPStan_3d4486d07\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_3d4486d07\Symfony\Component\Console\Output\ConsoleOutput))
#33 phar://C:/project/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(124): _PHPStan_3d4486d07\Symfony\Component\Console\Application->run()
#34 phar://C:/project/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(125): _PHPStan_3d4486d07\{closure}()
#35 C:\project\vendor\phpstan\phpstan\phpstan(8): require('phar://C:/masti...')
#36 C:\project\vendor\bin\phpstan(119): include('C:\\project\\ven...')
#37 {main}

```

**Comment by szepeviktor** [comment]
Thank you for your report.
What is your Larastan version?

**Comment by DumbergerL** [comment]
larastan 2.0

**Comment by calebdw** [comment]
What is the output of `--debug -vvv`?

**Comment by DumbergerL** [comment]
I found the problem. I have installed larastan 2.0. With larastan 2.8 everything works fine.

Thanks @szepeviktor and @calebdw for your quick responses!
