### ISSUE TITLE
LoadsAuthModel - Illegal offset type

### ISSUE THREAD

**Issue by verkerk20** [nunomaduro/larastan#1887]
- Laravel 10
- Larastan Version: 2.9.2
- `--level` used: 8
- Pull request with failing test:
https://github.com/larastan/larastan/pull/1848
### Description

```
Internal error: Internal error: Illegal offset type while analysing file /home/bob/git/gitlab.textinfo.nl/laravel/application/app/Providers/RouteServiceProvider.php
     Run PHPStan with -v option and post the stack trace to:
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.yaml
     Child process error (exit code 1):
```

```
## vendor/larastan/larastan/src/Concerns/LoadsAuthModel.php(30)
#0 [internal function]: Larastan\Larastan\ReturnTypes\RequestUserExtension::Larastan\Larastan\Concerns\{closure}()
#1 vendor/larastan/larastan/src/Concerns/LoadsAuthModel.php(26): array_reduce()
#2 vendor/larastan/larastan/src/ReturnTypes/RequestUserExtension.php(48): Larastan\Larastan\ReturnTypes\RequestUserExtension->getAuthModels()
#3 phar://resources/tools/phpstan/src/Analyser/MutatingScope.php(3591): Larastan\Larastan\ReturnTypes\RequestUserExtension->getTypeFromMethodCall()
#4 phar://resources/tools/phpstan/src/Analyser/MutatingScope.php(1403): PHPStan\Analyser\MutatingScope->methodCallReturnType()
#5 phar://resources/tools/phpstan/src/Analyser/MutatingScope.php(1409): PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}()
#6 phar://resources/tools/phpstan/src/Analyser/MutatingScope.php(575): PHPStan\Analyser\MutatingScope->resolveType()
#7 phar://resources/tools/phpstan/src/Reflection/ParametersAcceptorSelector.php(132): PHPStan\Analyser\MutatingScope->getType()
#8 phar://resources/tools/phpstan/src/Analyser/NodeScopeResolver.php(1664): PHPStan\Reflection\ParametersAcceptorSelector::selectFromArgs()
#9 phar://resources/tools/phpstan/src/Analyser/NodeScopeResolver.php(1923): PHPStan\Analyser\NodeScopeResolver->processExprNode()
#10 phar://resources/tools/phpstan/src/Analyser/NodeScopeResolver.php(2223): PHPStan\Analyser\NodeScopeResolver->processExprNode()
#11 phar://resources/tools/phpstan/src/Analyser/NodeScopeResolver.php(2915): PHPStan\Analyser\NodeScopeResolver->processExprNode()
#12 phar://resources/tools/phpstan/src/Analyser/NodeScopeResolver.php(1792): PHPStan\Analyser\NodeScopeResolver->processArgs()
#13 phar://resources/tools/phpstan/src/Analyser/NodeScopeResolver.php(1764): PHPStan\Analyser\NodeScopeResolver->processExprNode()
#14 phar://resources/tools/phpstan/src/Analyser/NodeScopeResolver.php(605): PHPStan\Analyser\NodeScopeResolver->processExprNode()
#15 phar://resources/tools/phpstan/src/Analyser/NodeScopeResolver.php(401): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#16 phar://resources/tools/phpstan/src/Analyser/MutatingScope.php(1042): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()
#17 phar://resources/tools/phpstan/src/Analyser/MutatingScope.php(575): PHPStan\Analyser\MutatingScope->resolveType()
#18 phar://resources/tools/phpstan/src/Analyser/MutatingScope.php(2149): PHPStan\Analyser\MutatingScope->getType()
#19 phar://resources/tools/phpstan/src/Analyser/NodeScopeResolver.php(2727): PHPStan\Analyser\MutatingScope->enterAnonymousFunction()
#20 phar://resources/tools/phpstan/src/Analyser/NodeScopeResolver.php(2910): PHPStan\Analyser\NodeScopeResolver->processClosureNode()
#21 phar://resources/tools/phpstan/src/Analyser/NodeScopeResolver.php(1914): PHPStan\Analyser\NodeScopeResolver->processArgs()
#22 phar://resources/tools/phpstan/src/Analyser/NodeScopeResolver.php(627): PHPStan\Analyser\NodeScopeResolver->processExprNode()
#23 phar://resources/tools/phpstan/src/Analyser/NodeScopeResolver.php(401): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#24 phar://resources/tools/phpstan/src/Analyser/NodeScopeResolver.php(566): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()
#25 phar://resources/tools/phpstan/src/Analyser/NodeScopeResolver.php(3679): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#26 phar://resources/tools/phpstan/src/Analyser/NodeScopeResolver.php(3695): PHPStan\Analyser\NodeScopeResolver->processNodesForCalledMethod()
#27 phar://resources/tools/phpstan/src/Analyser/NodeScopeResolver.php(3691): PHPStan\Analyser\NodeScopeResolver->processNodesForCalledMethod()
#28 phar://resources/tools/phpstan/src/Analyser/NodeScopeResolver.php(3695): PHPStan\Analyser\NodeScopeResolver->processNodesForCalledMethod()
#29 phar://resources/tools/phpstan/src/Analyser/NodeScopeResolver.php(3614): PHPStan\Analyser\NodeScopeResolver->processNodesForCalledMethod()
#30 phar://resources/tools/phpstan/src/Analyser/NodeScopeResolver.php(1806): PHPStan\Analyser\NodeScopeResolver->processCalledMethod()
#31 phar://resources/tools/phpstan/src/Analyser/NodeScopeResolver.php(627): PHPStan\Analyser\NodeScopeResolver->processExprNode()
#32 phar://resources/tools/phpstan/src/Analyser/NodeScopeResolver.php(401): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#33 phar://resources/tools/phpstan/src/Analyser/NodeScopeResolver.php(566): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()
#34 phar://resources/tools/phpstan/src/Analyser/NodeScopeResolver.php(401): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#35 phar://resources/tools/phpstan/src/Analyser/NodeScopeResolver.php(668): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()
#36 phar://resources/tools/phpstan/src/Analyser/NodeScopeResolver.php(401): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#37 phar://resources/tools/phpstan/src/Analyser/NodeScopeResolver.php(640): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()
#38 phar://resources/tools/phpstan/src/Analyser/NodeScopeResolver.php(370): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#39 phar://resources/tools/phpstan/src/Analyser/FileAnalyser.php(166): PHPStan\Analyser\NodeScopeResolver->processNodes()
#40 phar://resources/tools/phpstan/src/Command/WorkerCommand.php(132): PHPStan\Analyser\FileAnalyser->analyseFile()
#41 phar://resources/tools/phpstan/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97): PHPStan\Command\WorkerCommand->PHPStan\Command\{closure}()
#42 phar://resources/tools/phpstan/vendor/clue/ndjson-react/src/Decoder.php(117): _PHPStan_8b6260c21\Evenement\EventEmitter->emit()
#43 phar://resources/tools/phpstan/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97): _PHPStan_8b6260c21\Clue\React\NDJson\Decoder->handleData()
#44 phar://resources/tools/phpstan/vendor/react/stream/src/Util.php(62): _PHPStan_8b6260c21\Evenement\EventEmitter->emit()
#45 phar://resources/tools/phpstan/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97): _PHPStan_8b6260c21\React\Stream\Util::_PHPStan_8b6260c21\React\Stream\{closure}()
#46 phar://resources/tools/phpstan/vendor/react/stream/src/DuplexResourceStream.php(154): _PHPStan_8b6260c21\Evenement\EventEmitter->emit()
#47 phar://resources/tools/phpstan/vendor/react/event-loop/src/StreamSelectLoop.php(201): _PHPStan_8b6260c21\React\Stream\DuplexResourceStream->handleData()
#48 phar://resources/tools/phpstan/vendor/react/event-loop/src/StreamSelectLoop.php(173): _PHPStan_8b6260c21\React\EventLoop\StreamSelectLoop->waitForStreamActivity()
#49 phar://resources/tools/phpstan/src/Command/WorkerCommand.php(98): _PHPStan_8b6260c21\React\EventLoop\StreamSelectLoop->run()
#50 phar://resources/tools/phpstan/vendor/symfony/console/Command/Command.php(259): PHPStan\Command\WorkerCommand->execute()
#51 phar://resources/tools/phpstan/vendor/symfony/console/Application.php(870): _PHPStan_8b6260c21\Symfony\Component\Console\Command\Command->run()
#52 phar://resources/tools/phpstan/vendor/symfony/console/Application.php(261): _PHPStan_8b6260c21\Symfony\Component\Console\Application->doRunCommand()
#53 phar://resources/tools/phpstan/vendor/symfony/console/Application.php(157): _PHPStan_8b6260c21\Symfony\Component\Console\Application->doRun()
#54 phar://resources/tools/phpstan/bin/phpstan(124): _PHPStan_8b6260c21\Symfony\Component\Console\Application->run()
#55 phar://resources/tools/phpstan/bin/phpstan(125): _PHPStan_8b6260c21\{closure}()
#56 resources/tools/phpstan(6): require('...')
#57 {main}
Child process error (exit code 1):
```

### Laravel code where the issue was found

This code is used within the RouteServiceProvider and gives the error.

```php
    /**
     * Configure the rate limiters for the application.
     */
    protected function configureRateLimiting(): void
    {
        RateLimiter::for('api', function(Request $request) {
            return Limit::perMinute(config('http.rate-limiter.limit', 80))
                // The next line fails, if we comment this line there is no error.
                ->by(optional($request->user())->id ?: $request->ip())
                ->response(function(Request $request, array $headers) {
                    return new JsonResponse(status: 429, headers: $headers);
                });
        });
    }
```

**Comment by szepeviktor** [comment]
https://github.com/larastan/larastan/blob/4b7fd694b9d73731baebe0299024232213f15333/src/Concerns/LoadsAuthModel.php#L30

**Comment by calebdw** [comment]
What Laravel version are you using, and what does your auth config look like? If using L11, then please show what your auth config is *and* what the merged config is

**Comment by verkerk20** [comment]
@calebdw I'm using Laravel 10, not 11.

I did some more debugging and found my error. There was a package I included which provided a `config/auth.php` which got merged with the `config/auth.php` from the project itself. This resulted in the following guard configured. After I fixed my config there was no error.
``` 
     (
         [api] => Array
             (
                 [driver] => Array
                     (
                         [0] => token
                         [1] => token
                     )

                 [provider] => Array
                     (
                         [0] => users
                         [1] => users
                     )

                 [hash] => Array
                     (
                         [0] =>
                         [1] =>
                     )

             )

         [users] => Array
             (
                 [driver] => sanctum
                 [provider] => users
             )

         [web] => Array
             (
                 [driver] => session
                 [provider] => users
             )

         [sanctum] => Array
             (
                 [driver] => sanctum
                 [provider] =>
             )

     )
```
