### ISSUE TITLE
Call to undefined method PHPStan\Type\ErrorType::getValue()

### ISSUE THREAD

**Issue by adamgyongyosi** [nunomaduro/larastan#1946]
- Larastan Version: 2.9.6
- Laravel Version: 11

### Description

run 
```
 ./vendor/bin/phpstan analyse --configuration phpstan.neon --memory-limit=1G -v
```
get:
```
Internal error: Internal error: Call to undefined method PHPStan\Type\ErrorType::getValue() while analysing file /app/app/Http/Resources/Setting/SettingListResource.php

     Post the following stack trace to https://github.com/phpstan/phpstan/issues/new?template=Bug_report.yaml:
     ## /app/vendor/larastan/larastan/src/Properties/ModelCastHelper.php(262)
     #0 [internal function]: Larastan\Larastan\Properties\ModelCastHelper::Larastan\Larastan\Properties\{closure}(Object(PHPStan\Type\ErrorType))
     #1 /app/vendor/larastan/larastan/src/Properties/ModelCastHelper.php(262): array_map(Object(Closure), Array)
     #2 /app/vendor/larastan/larastan/src/Properties/ModelCastHelper.php(226): Larastan\Larastan\Properties\ModelCastHelper->getModelCasts(Object(PHPStan\Reflection\ClassReflection))
     #3 /app/vendor/larastan/larastan/src/Properties/ModelPropertyHelper.php(110): Larastan\Larastan\Properties\ModelCastHelper->getCastForProperty(Object(PHPStan\Reflection\ClassReflection), 'setting_value')
     #4 /app/vendor/larastan/larastan/src/Properties/ModelPropertyExtension.php(30): Larastan\Larastan\Properties\ModelPropertyHelper->getDatabaseProperty(Object(PHPStan\Reflection\ClassReflection), 'setting_value')
     #5 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ClassReflection.php(636): Larastan\Larastan\Properties\ModelPropertyExtension->getProperty(Object(PHPStan\Reflection\ClassReflection), 'setting_value')
     #6 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Type/ObjectType.php(185): PHPStan\Reflection\ClassReflection->getProperty('setting_value', Object(PHPStan\Analyser\OutOfClassScope))
     #7 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Type/ObjectType.php(148): PHPStan\Type\ObjectType->getUnresolvedPropertyPrototype('setting_value', Object(PHPStan\Analyser\OutOfClassScope))
     #8 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/Mixin/MixinPropertiesClassReflectionExtension.php(57): PHPStan\Type\ObjectType->getProperty('setting_value', Object(PHPStan\Analyser\OutOfClassScope))
     #9 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/Mixin/MixinPropertiesClassReflectionExtension.php(31): PHPStan\Reflection\Mixin\MixinPropertiesClassReflectionExtension->findProperty(Object(PHPStan\Reflection\ClassReflection), 'setting_value')
     #10 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ClassReflection.php(494): PHPStan\Reflection\Mixin\MixinPropertiesClassReflectionExtension->hasProperty(Object(PHPStan\Reflection\ClassReflection), 'setting_value')
     #11 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Type/ObjectType.php(135): PHPStan\Reflection\ClassReflection->hasProperty('setting_value')
     #12 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Type/StaticType.php(189): PHPStan\Type\ObjectType->hasProperty('setting_value')
     #13 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(3670): PHPStan\Type\StaticType->hasProperty('setting_value')
     #14 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(3680): PHPStan\Analyser\MutatingScope->getPropertyReflection(Object(PHPStan\Type\ThisType), 'setting_value')
     #15 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1489): PHPStan\Analyser\MutatingScope->propertyFetchType(Object(PHPStan\Type\ThisType), 'setting_value', Object(PhpParser\Node\Expr\PropertyFetch))
     #16 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1495): PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}()
     #17 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(589): PHPStan\Analyser\MutatingScope->resolveType('$this->setting_...', Object(PhpParser\Node\Expr\PropertyFetch))
     #18 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1160): PHPStan\Analyser\MutatingScope->getType(Object(PhpParser\Node\Expr\PropertyFetch))
     #19 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/InitializerExprTypeResolver.php(454): PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}(Object(PhpParser\Node\Expr\PropertyFetch))
     #20 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1159): PHPStan\Reflection\InitializerExprTypeResolver->getArrayType(Object(PhpParser\Node\Expr\Array_), Object(Closure))
     #21 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(589): PHPStan\Analyser\MutatingScope->resolveType('['id' => $this-...', Object(PhpParser\Node\Expr\Array_))
     #22 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Rules/FunctionReturnTypeCheck.php(52): PHPStan\Analyser\MutatingScope->getType(Object(PhpParser\Node\Expr\Array_))
     #23 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Rules/Methods/ReturnTypeRule.php(43): PHPStan\Rules\FunctionReturnTypeCheck->checkReturnType(Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Type\ArrayType), Object(PhpParser\Node\Expr\Array_),
     Object(PhpParser\Node\Stmt\Return_), 'Method App\\Http...', 'Method App\\Http...', 'Method App\\Http...', 'Method App\\Http...', false)
     #24 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(107): PHPStan\Rules\Methods\ReturnTypeRule->processNode(Object(PhpParser\Node\Stmt\Return_), Object(PHPStan\Analyser\MutatingScope))
     #25 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Node/ClassStatementsGatherer.php(108): PHPStan\Analyser\FileAnalyser->PHPStan\Analyser\{closure}(Object(PhpParser\Node\Stmt\Return_), Object(PHPStan\Analyser\MutatingScope))
     #26 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(586): PHPStan\Node\ClassStatementsGatherer->__invoke(Object(PhpParser\Node\Stmt\Return_), Object(PHPStan\Analyser\MutatingScope))
     #27 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(477): PHPStan\Analyser\NodeScopeResolver::PHPStan\Analyser\{closure}(Object(PhpParser\Node\Stmt\Return_), Object(PHPStan\Analyser\MutatingScope))
     #28 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(420): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Return_), Object(PHPStan\Analyser\MutatingScope), Object(Closure),
     Object(PHPStan\Analyser\StatementContext))
     #29 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(585): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\ClassMethod), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure),
     Object(PHPStan\Analyser\StatementContext))
     #30 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(420): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\ClassMethod), Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer),
     Object(PHPStan\Analyser\StatementContext))
     #31 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(687): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Class_), Array, Object(PHPStan\Analyser\MutatingScope),
     Object(PHPStan\Node\ClassStatementsGatherer), Object(PHPStan\Analyser\StatementContext))
     #32 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(420): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Class_), Object(PHPStan\Analyser\MutatingScope), Object(Closure),
     Object(PHPStan\Analyser\StatementContext))
     #33 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(659): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Namespace_), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure),
     Object(PHPStan\Analyser\StatementContext))
     #34 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(389): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Namespace_), Object(PHPStan\Analyser\MutatingScope), Object(Closure),
     Object(PHPStan\Analyser\StatementContext))
     #35 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(166): PHPStan\Analyser\NodeScopeResolver->processNodes(Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
     #36 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Command/WorkerCommand.php(132): PHPStan\Analyser\FileAnalyser->analyseFile('/app/app/Http/R...', Array, Object(PHPStan\Rules\LazyRegistry), Object(PHPStan\Collectors\Registry), NULL)
     #37 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97): PHPStan\Command\WorkerCommand->PHPStan\Command\{closure}(Array)
     #38 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/clue/ndjson-react/src/Decoder.php(117): _PHPStan_7961f7ae1\Evenement\EventEmitter->emit('data', Array)
     #39 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97): _PHPStan_7961f7ae1\Clue\React\NDJson\Decoder->handleData(Array)
     #40 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/react/stream/src/Util.php(62): _PHPStan_7961f7ae1\Evenement\EventEmitter->emit('data', Array)
     #41 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97): _PHPStan_7961f7ae1\React\Stream\Util::_PHPStan_7961f7ae1\React\Stream\{closure}('{"action":"anal...')
     #42 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/react/stream/src/DuplexResourceStream.php(154): _PHPStan_7961f7ae1\Evenement\EventEmitter->emit('data', Array)
     #43 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/react/event-loop/src/StreamSelectLoop.php(201): _PHPStan_7961f7ae1\React\Stream\DuplexResourceStream->handleData(Resource id #6912)
     #44 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/react/event-loop/src/StreamSelectLoop.php(173): _PHPStan_7961f7ae1\React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)
     #45 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Command/WorkerCommand.php(98): _PHPStan_7961f7ae1\React\EventLoop\StreamSelectLoop->run()
     #46 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(259): PHPStan\Command\WorkerCommand->execute(Object(_PHPStan_7961f7ae1\Symfony\Component\Console\Input\ArgvInput),
     Object(_PHPStan_7961f7ae1\Symfony\Component\Console\Output\ConsoleOutput))
     #47 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(870): _PHPStan_7961f7ae1\Symfony\Component\Console\Command\Command->run(Object(_PHPStan_7961f7ae1\Symfony\Component\Console\Input\ArgvInput),
     Object(_PHPStan_7961f7ae1\Symfony\Component\Console\Output\ConsoleOutput))
     #48 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(261): _PHPStan_7961f7ae1\Symfony\Component\Console\Application->doRunCommand(Object(PHPStan\Command\WorkerCommand),
     Object(_PHPStan_7961f7ae1\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_7961f7ae1\Symfony\Component\Console\Output\ConsoleOutput))
     #49 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(157): _PHPStan_7961f7ae1\Symfony\Component\Console\Application->doRun(Object(_PHPStan_7961f7ae1\Symfony\Component\Console\Input\ArgvInput),
     Object(_PHPStan_7961f7ae1\Symfony\Component\Console\Output\ConsoleOutput))
     #50 phar:///app/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(124): _PHPStan_7961f7ae1\Symfony\Component\Console\Application->run()
     #51 phar:///app/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(125): _PHPStan_7961f7ae1\{closure}()
     #52 /app/vendor/phpstan/phpstan/phpstan(8): require('phar:///app/ven...')
     #53 /app/vendor/bin/phpstan(119): include('/app/vendor/php...')
     #54 {main}
```

/app/app/Http/Resources/Setting/SettingListResource.php

```php
<?php

namespace App\Http\Resources\Setting;

use App\Models\Setting;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

/**
 * @mixin Setting
 */
class SettingListResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     */
    public function toArray(Request $request): array
    {
        return [
            'id' => $this->id,
            'setting_key' => $this->setting_key,
            'setting_value' => $this->setting_value,
            'setting_label' => $this->setting_label,
        ];
    }
}
```
Setting.php
```php
<?php

namespace App\Models;

use App\Casts\SettingValue;
use App\Traits\RecordsUserMeta;
use Illuminate\Database\Eloquent\Model;
use Spatie\Translatable\HasTranslations;

class Setting extends Model
{
    use HasTranslations;
    use RecordsUserMeta;

    /**
     * @var string[]
     */
    public array $translatable = ['setting_label'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'setting_key',
        'setting_value',
        'setting_label',
        'setting_type_cast',
        'validation',
        'created_by',
        'updated_by',
    ];

    /**
     * The attributes that should be cast.
     *
     * @return array{setting_value: SettingValue::class}
     */
    protected function casts(): array
    {
        return [
            'setting_value' => SettingValue::class,
        ];
    }
}
```

**Comment by szepeviktor** [comment]
Have you tried `@return array{setting_value: 'App\\Casts\\SettingValue'}` ?

https://github.com/larastan/larastan/blob/555119c855b431c7cb15182517e6308deb6d6316/tests/Type/data/model-properties-l11.php#L22-L25

**Comment by adamgyongyosi** [comment]
thx for help

![image](https://github.com/larastan/larastan/assets/5511526/91b40211-ea27-4973-8c6f-7edbaca31adf)

solution
```php
    /**
     * The attributes that should be cast.
     *
     * @return array{setting_value: 'App\Casts\SettingValue'}
     */
    protected function casts(): array
    {
        return [
            'setting_value' => SettingValue::class,
        ];
    }
```

**Comment by ZejdCicak** [comment]
@adamgyongyosi Did this fix your enum casts across code as well? When I try to cast field to enum it treats it as string so I get errors like 
`Match arm comparison between string and App\Enums\Order\OrderStatus::APPROVED is always false`

```
/**
     * @return array{status: 'App\Enums\Offer\OfferStatus'}
     */
    protected function casts(): array
    {
        return [
            'status'      => OfferStatus::class,
        ];
    }
```
