### ISSUE TITLE
Internal error: Call to undefined method PHPStan\Type\ErrorType::getValue()

### ISSUE THREAD

**Issue by DSpeichert** [nunomaduro/larastan#1964]
- Larastan Version: v2.9.7 
- Laravel Version: v11.9.2 

### Description

`phpstan analyze` crashes with internal error:
```
     Internal error: Internal error: Call to undefined method PHPStan\Type\ErrorType::getValue() while analysing file
     /app/app/Jobs/Test.php

     Post the following stack trace to https://github.com/phpstan/phpstan/issues/new?template=Bug_report.yaml:
     ## /app/vendor/larastan/larastan/src/Properties/ModelCastHelper.php(262)
     #0 [internal function]: Larastan\Larastan\Properties\ModelCastHelper::Larastan\Larastan\Properties\{closure}()
     #1 /app/vendor/larastan/larastan/src/Properties/ModelCastHelper.php(262): array_map()
     #2 /app/vendor/larastan/larastan/src/Properties/ModelCastHelper.php(226): Larastan\Larastan\Properties\ModelCastHelper->getModelCasts()
     #3 /app/vendor/larastan/larastan/src/Properties/ModelPropertyHelper.php(110): Larastan\Larastan\Properties\ModelCastHelper->getCastForProperty()
     #4 /app/vendor/larastan/larastan/src/Properties/ModelPropertyExtension.php(30):
     Larastan\Larastan\Properties\ModelPropertyHelper->getDatabaseProperty()
     #5 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ClassReflection.php(638):
     Larastan\Larastan\Properties\ModelPropertyExtension->getProperty()
     #6 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Type/ObjectType.php(189): PHPStan\Reflection\ClassReflection->getProperty()
     #7 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Type/ObjectType.php(152): PHPStan\Type\ObjectType->getUnresolvedPropertyPrototype()
     #8 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(3825): PHPStan\Type\ObjectType->getProperty()
     #9 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(3832): PHPStan\Analyser\MutatingScope->getPropertyReflection()
     #10 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1558): PHPStan\Analyser\MutatingScope->propertyFetchType()
     #11 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1564): PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}()   
     #12 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(594): PHPStan\Analyser\MutatingScope->resolveType()
     #13 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Rules/FunctionCallParametersCheck.php(118): PHPStan\Analyser\MutatingScope->getType()
     #14 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Rules/Methods/CallMethodsRule.php(48): PHPStan\Rules\FunctionCallParametersCheck->check()        
     #15 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(120): PHPStan\Rules\Methods\CallMethodsRule->processNode()
     #16 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Node/ClassStatementsGatherer.php(109):
     PHPStan\Analyser\FileAnalyser->PHPStan\Analyser\{closure}()
     #17 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(616): PHPStan\Node\ClassStatementsGatherer->__invoke()
     #18 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(691):
     PHPStan\Analyser\NodeScopeResolver::PHPStan\Analyser\{closure}()
     #19 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(3070):
     PHPStan\Analyser\NodeScopeResolver::PHPStan\Analyser\{closure}()
     #20 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1756):
     PHPStan\Analyser\NodeScopeResolver->callNodeCallbackWithExpression()
     #21 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1782): PHPStan\Analyser\NodeScopeResolver->processExprNode()      
     #22 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(3586):
     PHPStan\Analyser\NodeScopeResolver->PHPStan\Analyser\{closure}()
     #23 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1767): PHPStan\Analyser\NodeScopeResolver->processAssignVar()     
     #24 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(690): PHPStan\Analyser\NodeScopeResolver->processExprNode()       
     #25 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(439): PHPStan\Analyser\NodeScopeResolver->processStmtNode()       
     #26 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(615): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()      
     #27 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(439): PHPStan\Analyser\NodeScopeResolver->processStmtNode()       
     #28 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(752): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()      
     #29 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(439): PHPStan\Analyser\NodeScopeResolver->processStmtNode()       
     #30 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(722): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()      
     #31 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(407): PHPStan\Analyser\NodeScopeResolver->processStmtNode()       
     #32 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(179): PHPStan\Analyser\NodeScopeResolver->processNodes()
     #33 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Command/WorkerCommand.php(137): PHPStan\Analyser\FileAnalyser->analyseFile()
     #34 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):
     PHPStan\Command\WorkerCommand->PHPStan\Command\{closure}()
     #35 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/clue/ndjson-react/src/Decoder.php(117): _PHPStan_1310ce93b\Evenement\EventEmitter->emit()     
     #36 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):
     _PHPStan_1310ce93b\Clue\React\NDJson\Decoder->handleData()
     #37 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/react/stream/src/Util.php(62): _PHPStan_1310ce93b\Evenement\EventEmitter->emit()
     #38 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):
     _PHPStan_1310ce93b\React\Stream\Util::_PHPStan_1310ce93b\React\Stream\{closure}()
     #39 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/react/stream/src/DuplexResourceStream.php(154):
     _PHPStan_1310ce93b\Evenement\EventEmitter->emit()
     #40 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/react/event-loop/src/StreamSelectLoop.php(201):
     _PHPStan_1310ce93b\React\Stream\DuplexResourceStream->handleData()
     #41 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/react/event-loop/src/StreamSelectLoop.php(173):
     _PHPStan_1310ce93b\React\EventLoop\StreamSelectLoop->waitForStreamActivity()
     #42 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Command/WorkerCommand.php(98): _PHPStan_1310ce93b\React\EventLoop\StreamSelectLoop->run()        
     #43 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(259): PHPStan\Command\WorkerCommand->execute()
     #44 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(870):
     _PHPStan_1310ce93b\Symfony\Component\Console\Command\Command->run()
     #45 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(261):
     _PHPStan_1310ce93b\Symfony\Component\Console\Application->doRunCommand()
     #46 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(157):
     _PHPStan_1310ce93b\Symfony\Component\Console\Application->doRun()
     #47 phar:///app/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(124): _PHPStan_1310ce93b\Symfony\Component\Console\Application->run()
     #48 phar:///app/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(125): _PHPStan_1310ce93b\{closure}()
     #49 /app/vendor/phpstan/phpstan/phpstan(8): require('...')
     #50 /app/vendor/bin/phpstan(117): include('...')
     #51 {main}
```

### Laravel code where the issue was found

unclear

**Comment by calebdw** [comment]
What does your `/app/app/Jobs/Test.php` file look like?

**Comment by szepeviktor** [comment]
https://github.com/larastan/larastan/blob/5948c964d711fee7859275713e906f172c9d2ca6/src/Properties/ModelCastHelper.php#L262

**Comment by DSpeichert** [comment]
> What does your `/app/app/Jobs/Test.php` file look like?

I tried to find minimum reproducible snippet and determined that it really doesn't matter what the Job or the Model looks like, the error is thrown when processing model casts AND model has an existing table defined. When setting `protected $table = 'random_name_that_does_not_exist';`, error isn't occurring.

ErrorType indeed does not have have `getValue()`: https://github.com/phpstan/phpstan-src/blob/1.11.x/src/Type/ErrorType.php

I'm not yet sure why a cast value would evaluate to `PHPStan\Type\ErrorType`

**Comment by calebdw** [comment]
It still would be helpful to see how your casts are set up, can you show the whole model?
