### ISSUE TITLE
PHPStan failure in neovim when 

### ISSUE THREAD

**Issue by scippio** [nunomaduro/larastan#1978]
- Larastan Version: 2.9.7
- Laravel Version: 11.10.0

### Description
When I add:
```
includes:
	- vendor/larastan/larastan/extension.neon
```
my diagnostic server in neovim throw error (see picture) and whole PHPStan shuw down.

![image](https://github.com/larastan/larastan/assets/672903/2abee07b-76fe-4d0f-b3d6-20a56c865419)

**Comment by scippio** [comment]
More info:
![image](https://github.com/larastan/larastan/assets/672903/7681d4e7-22df-4e30-96c4-913560c7eb0e)

**Comment by calebdw** [comment]
Try running PHPStan outside of Neovim and see if you get any errors

**Comment by scippio** [comment]
> Try running PHPStan outside of Neovim and see if you get any errors

When I run it in terminal it's look ok.

**Comment by calebdw** [comment]
Not sure without more information, it works fine in Neovim for me (although I have encountered the same error for various reasons). You can try increasing the log level for lsp / phpactor to see what it's failing on

**Comment by scippio** [comment]
ok, I added debug into phpactor and found this:
```
[2024-06-24 13:17:24] phpactor.ERROR: Diagnostic provider "phpstan" errored with "Could not decode expected PHPStan JSON string """, removing from pool {"channel":"LSPDIAG","stack":"#0 [internal function]: Phpactor\\LanguageServer\\Core\\Diagnostics\\DiagnosticsEngine->Phpactor\\LanguageServer\\Core\\Diagnostics\\{closure}()
#1 /home/scippio/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Coroutine.php(115): Generator->throw(Object(RuntimeException))
#2 /home/scippio/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Failure.php(33): Amp\\Coroutine->Amp\\{closure}(Object(RuntimeException), NULL)
#3 /home/scippio/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Internal/Placeholder.php(143): Amp\\Failure->onResolve(Object(Closure))
#4 /home/scippio/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Internal/Placeholder.php(177): Amp\\Coroutine->resolve(Object(Amp\\Failure))
#5 /home/scippio/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Coroutine.php(137): Amp\\Coroutine->fail(Object(RuntimeException))
#6 /home/scippio/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Failure.php(33): Amp\\Coroutine->Amp\\{closure}(Object(RuntimeException), NULL)
#7 /home/scippio/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Internal/Placeholder.php(143): Amp\\Failure->onResolve(Object(Closure))
#8 /home/scippio/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Internal/Placeholder.php(177): Amp\\Coroutine->resolve(Object(Amp\\Failure))
#9 /home/scippio/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Coroutine.php(137): Amp\\Coroutine->fail(Object(RuntimeException))
#10 /home/scippio/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\\Coroutine->Amp\\{closure}(NULL, 'Note: Using con...')
#11 /home/scippio/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Coroutine.php(123): Amp\\Coroutine->resolve('Note: Using con...')
#12 /home/scippio/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\\Coroutine->Amp\\{closure}(NULL, 'Note: Using con...')
#13 /home/scippio/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Deferred.php(53): Amp\\Promise@anonymous->resolve('Note: Using con...')
#14 /home/scippio/.local/share/nvim/mason/packages/phpactor/vendor/amphp/byte-stream/lib/ResourceInputStream.php(109): Amp\\Deferred->resolve('Note: Using con...')
#15 /home/scippio/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Loop/Driver.php(119): Amp\\ByteStream\\ResourceInputStream::Amp\\ByteStream\\{closure}('cp', 'Note: Using con...')
#16 /home/scippio/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\\Loop\\Driver->tick()
#17 /home/scippio/.local/share/nvim/mason/packages/phpactor/vendor/amphp/amp/lib/Loop.php(95): Amp\\Loop\\Driver->run()
#18 /home/scippio/.local/share/nvim/mason/packages/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(114): Amp\\Loop::run(Object(Closure))
#19 /home/scippio/.local/share/nvim/mason/packages/phpactor/lib/Extension/LanguageServer/Command/StartCommand.php(50): Phpactor\\LanguageServer\\Core\\Server\\LanguageServer->run()
#20 /home/scippio/.local/share/nvim/mason/packages/phpactor/vendor/symfony/console/Command/Command.php(298): Phpactor\\Extension\\LanguageServer\\Command\\StartCommand->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 /home/scippio/.local/share/nvim/mason/packages/phpactor/vendor/symfony/console/Application.php(1040): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 /home/scippio/.local/share/nvim/mason/packages/phpactor/vendor/symfony/console/Application.php(301): Symfony\\Component\\Console\\Application->doRunCommand(Object(Phpactor\\Extension\\LanguageServer\\Command\\StartCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#23 /home/scippio/.local/share/nvim/mason/packages/phpactor/lib/Application.php(48): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#24 /home/scippio/.local/share/nvim/mason/packages/phpactor/vendor/symfony/console/Application.php(171): Phpactor\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#25 /home/scippio/.local/share/nvim/mason/packages/phpactor/bin/phpactor(46): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#26 {main}"} []
```

**Comment by scippio** [comment]
I think I should go and deal with it to the https://github.com/phpstan/phpstan/issues ...

**Comment by scippio** [comment]
btw: I found already reported this error now :facepalm:  https://github.com/phpactor/phpactor/issues/2332
