### ISSUE TITLE
Larastan doesn't support union types for casts() 

### ISSUE THREAD

**Issue by SlyDave** [nunomaduro/larastan#2006]
- Larastan Version: 2.9.8
- Laravel Version: 11.17.0

### Description

I have some casts() that are either of type "date" or null, as this is how they're defined in the database, date column, nullable `$table->date('ends_at')->nullable();`

when I define the array-shape for the casts() function on my model, as:

```php
    /**
     * @return array{
     *      ends_at: 'date'
     * }
     */
```
it works but is incorrect. (https://phpstan.org/r/0be43ac2-9674-4873-9826-84f4507f108e)
when I define it as:
```php
    /**
     * @return array{
     *      ends_at: 'date'|null
     * }
     */
```
try phpstan says it's fine (https://phpstan.org/r/df799fec-c7d8-4a69-955e-d5032cf79ed4)
but it crashes when in actual use

```
C:\www\workrest\app\GraphQL\Queries\Contract\Adjustments.php
Uncaught Error: Call to undefined method PHPStan\Type\UnionType::getValue() in C:\www\workrest\vendor\larastan\larastan\src\Properties\ModelCastHelper.php:262
#0 [internal function]: Larastan\Larastan\Properties\ModelCastHelper::Larastan\Larastan\Properties\{closure}()
#1 C:\www\workrest\vendor\larastan\larastan\src\Properties\ModelCastHelper.php(262): array_map()
#2 C:\www\workrest\vendor\larastan\larastan\src\Properties\ModelCastHelper.php(226): Larastan\Larastan\Properties\ModelCastHelper->getModelCasts()
#3 C:\www\workrest\vendor\larastan\larastan\src\Properties\ModelPropertyHelper.php(120): Larastan\Larastan\Properties\ModelCastHelper->getCastForProperty()
#4 C:\www\workrest\vendor\larastan\larastan\src\Properties\ModelPropertyExtension.php(30): Larastan\Larastan\Properties\ModelPropertyHelper->getDatabaseProperty()
#5 phar://C:/www/workrest/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ClassReflection.php(642): Larastan\Larastan\Properties\ModelPropertyExtension->getProperty()
#6 phar://C:/www/workrest/vendor/phpstan/phpstan/phpstan.phar/src/Type/ObjectType.php(189): PHPStan\Reflection\ClassReflection->getProperty()
#7 phar://C:/www/workrest/vendor/phpstan/phpstan/phpstan.phar/src/Type/ObjectType.php(152): PHPStan\Type\ObjectType->getUnresolvedPropertyPrototype()
#8 phar://C:/www/workrest/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(3957): PHPStan\Type\ObjectType->getProperty()
#9 phar://C:/www/workrest/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(3964): PHPStan\Analyser\MutatingScope->getPropertyReflection()
#10 phar://C:/www/workrest/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1684): PHPStan\Analyser\MutatingScope->propertyFetchType()
#11 phar://C:/www/workrest/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1690): PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}()
#12 phar://C:/www/workrest/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(599): PHPStan\Analyser\MutatingScope->resolveType()
#13 phar://C:/www/workrest/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1615): PHPStan\Analyser\MutatingScope->getType()
#14 phar://C:/www/workrest/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1621): PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}()
#15 phar://C:/www/workrest/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(599): PHPStan\Analyser\MutatingScope->resolveType()
#16 phar://C:/www/workrest/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(825): PHPStan\Analyser\MutatingScope->getType()
#17 phar://C:/www/workrest/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(599): PHPStan\Analyser\MutatingScope->resolveType()
#18 phar://C:/www/workrest/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1787): PHPStan\Analyser\MutatingScope->getType()
#19 phar://C:/www/workrest/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(718): PHPStan\Analyser\NodeScopeResolver->findEarlyTerminatingExpr()
#20 phar://C:/www/workrest/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(458): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#21 phar://C:/www/workrest/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(646): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()
#22 phar://C:/www/workrest/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(458): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#23 phar://C:/www/workrest/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(783): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()
#24 phar://C:/www/workrest/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(458): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#25 phar://C:/www/workrest/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(753): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()
#26 phar://C:/www/workrest/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(423): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#27 phar://C:/www/workrest/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(179): PHPStan\Analyser\NodeScopeResolver->processNodes()
#28 phar://C:/www/workrest/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/Analyser.php(79): PHPStan\Analyser\FileAnalyser->analyseFile()
#29 phar://C:/www/workrest/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyserRunner.php(74): PHPStan\Analyser\Analyser->analyse()
#30 phar://C:/www/workrest/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseApplication.php(159): PHPStan\Command\AnalyserRunner->runAnalyser()
#31 phar://C:/www/workrest/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseApplication.php(79): PHPStan\Command\AnalyseApplication->runAnalyser()
#32 phar://C:/www/workrest/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseCommand.php(221): PHPStan\Command\AnalyseApplication->analyse()
#33 phar://C:/www/workrest/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(259): PHPStan\Command\AnalyseCommand->execute()
#34 phar://C:/www/workrest/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(870): _PHPStan_c4c026984\Symfony\Component\Console\Command\Command->run()
#35 phar://C:/www/workrest/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(261): _PHPStan_c4c026984\Symfony\Component\Console\Application->doRunCommand()
#36 phar://C:/www/workrest/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(157): _PHPStan_c4c026984\Symfony\Component\Console\Application->doRun()
#37 phar://C:/www/workrest/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(124): _PHPStan_c4c026984\Symfony\Component\Console\Application->run()
#38 phar://C:/www/workrest/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(125): _PHPStan_c4c026984\{closure}()
#39 C:\www\workrest\vendor\phpstan\phpstan\phpstan(8): require('...')
#40 C:\www\workrest\vendor\bin\phpstan(119): include('...')
#41 {main}
Elapsed time: 13 seconds
```

the breaking line inside Adjustments.php is the line that attempts to fetch the possible null cast property from the model
```
$to = $contract->ends_at?->toImmutable();
```

### Laravel code where the issue was found

```php
    /**
     * @return array{
     *      ends_at: 'date'|null
     * }
     */
```

**Comment by calebdw** [comment]
Remove the `null`, Larastan automatically knows about nullable database columns:

```
    /**
     * @return array{
     *      ends_at: 'date'
     * }
     */
```

**Comment by SlyDave** [comment]
Thanks, good to know! A little magic in the static analyser handling the magic in Laravel. 🙄
