### ISSUE TITLE
Nette\MemberAccessException with nette/php-generator version 3.3.0

### ISSUE THREAD

**Issue by harrisdt15f** [nunomaduro/larastan#375]
- Larastan Version: 0.4.3
- `--level` used: max
-  "nunomaduro/larastan": "^0.4.3"
-  "nunomaduro/collision": "^3.0",
-  “nette/php-generator”："^3.2.2",

**Laravel Framework 6.5.2**
php -v
**PHP 7.3.11-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Oct 24 2019 18:23:06) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.11-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.7.2, Copyright (c) 2002-2019, by Derick Rethans**
### Description
**php artisan code:analyse**
and then got below errors

**Uncaught Nette\MemberAccessException: Call to undefined static method Nette\PhpGenerator\Helpers::createObject()**

```
Starting To Run Code Quality
PHP Fatal error:  Uncaught Nette\MemberAccessException: Call to undefined static method Nette\PhpGenerator\Helpers::createObject(). in /var/www/jianghu/vendor/nette/utils/src/Utils/ObjectHelpers.php:78

Stack trace:
#0 /var/www/jianghu/vendor/nette/utils/src/Utils/StaticClass.php(34): Nette\Utils\ObjectHelpers::strictStaticCall('Nette\\PhpGenera...', 'createObject')
#1 /tmp/phpstan/cache/nette.configurator/Container_78a53e9dce.php(805): Nette\PhpGenerator\Helpers::__callStatic('createObject', Array)
#2 /var/www/jianghu/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(227): Container_78a53e9dce->__construct(Array)
#3 /var/www/jianghu/vendor/phpstan/phpstan/src/DependencyInjection/ContainerFactory.php(77): Nette\Configurator->createContainer()
#4 /var/www/jianghu/vendor/phpstan/phpstan/src/Command/CommandHelper.php(197): PHPStan\DependencyInjection\ContainerFactory->create('/tmp/phpstan', Array, Array)
#5 /var/www/jianghu/vendor/phpstan/phpstan/src/Command/AnalyseCommand.php(83): PHPStan\Command\CommandHelper::begin(Object(S in /var/www/jianghu/vendor/nette/utils/src/Utils/ObjectHelpers.php on line 78
```

Errors got only at nette/php-generator 3.3.0 version
when I download **nette/php-generator 3.2.3** and replace manually then the error was disappered.
So, Please check it's compability. Thanks 

### Laravel code where the issue was found

```php

namespace App\Http\Controllers\BackendApi\Merchant\Admin;

use App\Http\Controllers\BackendApi\Merchant\MerchantApiMainController;
use App\Http\Requests\Backend\Merchant\Admin\MerchantAdminUser\CreateRequest;
use App\Http\Requests\Backend\Merchant\Admin\MerchantAdminUser\UpdateAdminGroupRequest;
use App\Http\Requests\Backend\Merchant\Admin\MerchantAdminUser\DeleteAdminRequest;
use App\Http\Requests\Backend\Merchant\Admin\MerchantAdminUser\SearchAdminRequest;
use App\Http\SingleActions\Backend\Merchant\Admin\MerchantAdminUser\CreateAction;
use App\Http\SingleActions\Backend\Merchant\Admin\MerchantAdminUser\UpdateAdminGroupAction;
use App\Http\SingleActions\Backend\Merchant\Admin\MerchantAdminUser\DeleteAdminAction;
use App\Http\SingleActions\Backend\Merchant\Admin\MerchantAdminUser\AllAdminsAction;
use App\Http\SingleActions\Backend\Merchant\Admin\MerchantAdminUser\SearchAdminAction;
use Illuminate\Http\JsonResponse;

/**
 * Controls the data flow into a merchant admin user object and updates the view whenever data changes.
 */
class MerchantAdminUserController extends MerchantApiMainController
{
    /**
     * create api
     * @param CreateRequest $request Request.
     * @param CreateAction  $action  Action.
     * @return JsonResponse
     */
    public function create(CreateRequest $request, CreateAction $action): JsonResponse
    {
        $inputDatas = $request->validated();
        return $action->execute($this, $inputDatas);
    }

    /**
     * 获取所有当前平台的商户管理员用户
     * @param AllAdminsAction $action Action.
     * @return JsonResponse
     */
    public function allAdmins(AllAdminsAction $action): JsonResponse
    {
        return $action->execute($this);
    }

    /**
     * 修改管理员的归属组
     * @param UpdateAdminGroupRequest $request Request.
     * @param UpdateAdminGroupAction  $action  Action.
     * @return JsonResponse
     */
    public function updateAdminGroup(
        UpdateAdminGroupRequest $request,
        UpdateAdminGroupAction $action
    ): JsonResponse {
        $inputDatas = $request->validated();
        return $action->execute($this, $inputDatas);
    }

    /**
     * 删除管理员
     * @param DeleteAdminRequest $request Request.
     * @param DeleteAdminAction  $action  Action.
     * @return JsonResponse
     */
    public function deletePartnerAdmin(
        DeleteAdminRequest $request,
        DeleteAdminAction $action
    ): JsonResponse {
        $inputDatas = $request->validated();
        return $action->execute($this, $inputDatas);
    }

    /**
     * @param SearchAdminRequest $request Request.
     * @param SearchAdminAction  $action  Action.
     * @return JsonResponse
     */
    public function searchAdmin(
        SearchAdminRequest $request,
        SearchAdminAction $action
    ): JsonResponse {
        $inputDatas = $request->validated();
        return $action->execute($this, $inputDatas);
    }
}
```

**Comment by harrisdt15f** [comment]
Today They had updated their version to 3.3.1 again so I updated their latest version and the problem get solved.
Thanks.

**Comment by szepeviktor** [comment]
@harrisdt15f I'm happy to see you resolve this problem.
