### ISSUE TITLE
Unexpected value in SchemaAggregator

### ISSUE THREAD

**Issue by Gummibeer** [nunomaduro/larastan#449]
- Larastan Version: 0.5.1
- `--level` used: 5

### Description

```
   Exception  : Unexpected value

  at app/vendor/nunomaduro/larastan/src/Properties/SchemaAggregator.php:348
    344|                             $table->setColumn(new SchemaColumn($columnName.'_id', 'string', $nullable));
    345|                             break;
    346| 
    347|                         default:
  > 348|                             throw new \Exception('Unexpected value');
    349|                     }
    350|                 }
    351|             }
    352|         }

  Exception trace:

  1   NunoMaduro\Larastan\Properties\SchemaAggregator::processColumnUpdates("categories", "table")
      app/vendor/nunomaduro/larastan/src/Properties/SchemaAggregator.php:108

  2   NunoMaduro\Larastan\Properties\SchemaAggregator::alterTable(Object(PhpParser\Node\Expr\StaticCall))
      app/vendor/nunomaduro/larastan/src/Properties/SchemaAggregator.php:58

  Please use the argument -v to see more details.
PHP Fatal error:  Uncaught Exception: Unexpected value in app/vendor/nunomaduro/larastan/src/Properties/SchemaAggregator.php:348
Stack trace:
#0 app/vendor/nunomaduro/larastan/src/Properties/SchemaAggregator.php(108): NunoMaduro\Larastan\Properties\SchemaAggregator->processColumnUpdates('categories', 'table', Array)
#1 app/vendor/nunomaduro/larastan/src/Properties/SchemaAggregator.php(58): NunoMaduro\Larastan\Properties\SchemaAggregator->alterTable(Object(PhpParser\Node\Expr\StaticCall), true)
#2 app/vendor/nunomaduro/larastan/src/Properties/SchemaAggregator.php(39): NunoMaduro\Larastan\Properties\SchemaAggregator->addUpMethodStatements(Array)
#3 app/vendor/nunomaduro/larastan/src/Properties/SchemaAggregator.php(24): NunoMaduro\Larastan\Prope in app/vendor/nunomaduro/larastan/src/Properties/SchemaAggregator.php on line 348

   Symfony\Component\Debug\Exception\FatalErrorException  : Uncaught Exception: Unexpected value in app/vendor/nunomaduro/larastan/src/Properties/SchemaAggregator.php:348
Stack trace:
#0 app/vendor/nunomaduro/larastan/src/Properties/SchemaAggregator.php(108): NunoMaduro\Larastan\Properties\SchemaAggregator->processColumnUpdates('categories', 'table', Array)
#1 app/vendor/nunomaduro/larastan/src/Properties/SchemaAggregator.php(58): NunoMaduro\Larastan\Properties\SchemaAggregator->alterTable(Object(PhpParser\Node\Expr\StaticCall), true)
#2 app/vendor/nunomaduro/larastan/src/Properties/SchemaAggregator.php(39): NunoMaduro\Larastan\Properties\SchemaAggregator->addUpMethodStatements(Array)
#3 app/vendor/nunomaduro/larastan/src/Properties/SchemaAggregator.php(24): NunoMaduro\Larastan\Prope

  at app/vendor/nunomaduro/larastan/src/Properties/SchemaAggregator.php:348
    344|                             $table->setColumn(new SchemaColumn($columnName.'_id', 'string', $nullable));
    345|                             break;
    346| 
    347|                         default:
  > 348|                             throw new \Exception('Unexpected value');
    349|                     }
    350|                 }
    351|             }
    352|         }
```

### Laravel code where the issue was found

I think that this line creates the exception. It's a blueprint macro.

```php
$table->bigForeignInteger('parent_category_id', 'categories')->nullable();
```

**Comment by canvural** [comment]
Hi,

Thank you for the report!

Maybe we can support macros on `Blueprint` in the future, but for now, I guess we can just do nothing in the `default` case of the switch.

**Comment by Gummibeer** [comment]
I would prefer doing nothing over an exception. As a user this tool shouldn't fail only because it doesn't understand what the code does!?
This creates 16 wrong failures in our tests.
