### ISSUE TITLE
Argument 1 passed to PHPStan\Type\TypeTraverser::mapInternal() must implement interface PHPStan\Type\Type, null given

### ISSUE THREAD

**Issue by stayallive** [nunomaduro/larastan#467]
- Larastan Version: 0.5.2 (phpstan 0.12.9)
- `--level` used: 1

### Description

Command:
```
vendor/bin/phpstan analyse --memory-limit=2G
```

Output (I get 13 like these but they are all the same but for different files): 
```
 ------ ----------------------------------------------------------------------- 
  Line   Repositories/UserRepository.php                                        
 ------ ----------------------------------------------------------------------- 
         Internal error: Argument 1 passed to                                   
         PHPStan\Type\TypeTraverser::mapInternal() must implement interface     
         PHPStan\Type\Type, null given, called in                               
         phar:///private/var/www/app/vendor/phpstan/phpstan/phpstan/src/T  
         ype/Generic/GenericObjectType.php on line 179                          
         Run PHPStan with --debug option and post the stack trace to:           
         https://github.com/phpstan/phpstan/issues/new                          
 ------ ----------------------------------------------------------------------- 
```

Debug output (`vendor/bin/phpstan analyse --memory-limit=2G --debug -v`):
```
/private/var/www/app/app/Repositories/UserRepository.php

In TypeTraverser.php line 45:
                                                                                                                                                                    
  Argument 1 passed to PHPStan\Type\TypeTraverser::mapInternal() must implement interface PHPStan\Type\Type, null given, called in phar:///private/var/www/simulis  
  e/vendor/phpstan/phpstan/phpstan/src/Type/Generic/GenericObjectType.php on line 179                                                                               



In TypeTraverser.php line 45:
                                                                                                                                                                    
  Uncaught TypeError: Argument 1 passed to PHPStan\Type\TypeTraverser::mapInternal() must implement interface PHPStan\Type\Type, null given, called in phar:///pri  
  vate/var/www/app/vendor/phpstan/phpstan/phpstan/src/Type/Generic/GenericObjectType.php on line 179 and defined in phar:///private/var/www/app/vendor/p  
  hpstan/phpstan/phpstan/src/Type/TypeTraverser.php:45                                                                                                              
  Stack trace:                                                                                                                                                      
  #0 phar:///private/var/www/app/vendor/phpstan/phpstan/phpstan/src/Type/Generic/GenericObjectType.php(179): PHPStan\Type\TypeTraverser->mapInternal(NULL)     
  #1 phar:///private/var/www/app/vendor/phpstan/phpstan/phpstan/src/Type/TypeTraverser.php(52): PHPStan\Type\Generic\GenericObjectType->traverse(Array)        
  #2 phar:///private/var/www/app/vendor/phpstan/phpstan/phpstan/src/Type/Generic/TemplateTypeHelper.php(28): PHPStan\Type\TypeTraverser->traverseInternal(Obj  
  ect(PHPStan\Type\Generic\GenericObjectType))                                                                                                                      
  #3 phar:///private/var/www/app/vendor/phpstan/phpstan/phpstan/src/Type/TypeTraverser.php(47): PHPStan\Type\Generic\                                          
```

### Laravel code where the issue was found

I have nu clue since the output marks the full file... how do I debug this better?

Since phpstan is a phar I cannot really start debugging this or to know on which line to look for the thing phpstan is erroring, any guidance here would be appreciated to provide some better info. 

Output never mentions larastan however it is since 0.5.2 and 0.5.1 is fine. So I thought to post here first.

**Comment by canvural** [comment]
Hi,

The error is about generics. So maybe you can share the part of code where you use any Eloquent builder, or Collection. These are the only classes generics are used in Larastan.

Also you can debug PHPStan with XDebug. Just don't forget to pass the `--xdebug` flag.

**Comment by stayallive** [comment]
I've narrowed it down to this line in a specific error:

```
return User::query()->orderBy('id')->withoutGlobalScopes();
```

`User` is an Eloquent model with a custom builder.

```
    /**
     * @param \Illuminate\Database\Query\Builder $query
     *
     * @return \App\Models\QueryBuilders\UserBuilder
     */
    public function newEloquentBuilder($query): UserBuilder
    {
        return new UserBuilder($query);
    }
    public static function query(): UserBuilder
    {
        return parent::query();
    }
```

Exchanging it for that exact query but with another model (without custom builder) removes the error.

I have a [reproduction repo](https://github.com/stayallive/larastan-467-reproduction) with a pretty minimal test case.

```
git clone https://github.com/stayallive/larastan-467-reproduction.git
cd larastan-467-reproduction
composer install
vendor/bin/phpstan analyse --memory-limit=2G
```

**Comment by canvural** [comment]
Ok, thank you.

Please read the [upgrade guide](https://github.com/nunomaduro/larastan/blob/master/UPGRADE.md#custom-eloquent-builders). If you use custom builders you have to do the mentioned things.

Please let me know if that solves your problem.

**Comment by stayallive** [comment]
🤦‍♂ I got halfway doing that but missed the part about:

```
/**
 * @template TModelClass
 * @extends Builder<TModelClass>
 */
```

Thanks for the quick responses and helpful comments!

**Comment by canvural** [comment]
Sure. Glad I could help.
