### ISSUE TITLE
[bug] laravel swagger package and larastan cause error

### ISSUE THREAD

**Issue by zong0828** [nunomaduro/larastan#668]
- Larastan Version: v0.6.4
- `--level` used:5

### Description
The use of swagger and larastan packages at the same time will cause phpstan analyse error. 

Here is swagger php link : https://github.com/zircote/swagger-php

### Laravel code where the issue was found

```php

[2020-09-27 05:09:53] local.ERROR: AST failed to parse in located source (first 20 characters: <?php

/**
 * ID of ) {"exception":"[object] (_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\SourceLocator\\Ast\\Exception\\ParseToAstFailure(code: 0): AST failed to parse in located source (first 20 characters: <?php

/**
 * ID of ) at phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Ast/Exception/ParseToAstFailure.php:22)
[stacktrace]
#0 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Ast/Locator.php(55): _HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\SourceLocator\\Ast\\Exception\\ParseToAstFailure::fromLocatedSource(Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\SourceLocator\\Located\\InternalLocatedSource), Object(PhpParser\\Error))
#1 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Ast/Locator.php(41): _HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\SourceLocator\\Ast\\Locator->findReflectionsOfType(Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Reflector\\ClassReflector), Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\SourceLocator\\Located\\InternalLocatedSource), Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Identifier\\IdentifierType))
#2 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Type/AbstractSourceLocator.php(43): _HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\SourceLocator\\Ast\\Locator->findReflection(Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Reflector\\ClassReflector), Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\SourceLocator\\Located\\InternalLocatedSource), Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Identifier\\Identifier))
#3 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Type/AggregateSourceLocator.php(31): _HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\SourceLocator\\Type\\AbstractSourceLocator->locateIdentifier(Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Reflector\\ClassReflector), Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Identifier\\Identifier))
#4 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Type/MemoizingSourceLocator.php(31): _HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\SourceLocator\\Type\\AggregateSourceLocator->locateIdentifier(Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Reflector\\ClassReflector), Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Identifier\\Identifier))
#5 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/ondrejmirtes/better-reflection/src/Reflector/ConstantReflector.php(34): _HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\SourceLocator\\Type\\MemoizingSourceLocator->locateIdentifier(Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Reflector\\ClassReflector), Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Identifier\\Identifier))
#6 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/Reflection/BetterReflection/BetterReflectionProvider.php(249): _HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Reflector\\ConstantReflector->reflect('FILTER_UNSAFE_R...')
#7 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/Reflection/BetterReflection/BetterReflectionProvider.php(274): PHPStan\\Reflection\\BetterReflection\\BetterReflectionProvider->PHPStan\\Reflection\\BetterReflection\\{closure}('FILTER_UNSAFE_R...')
#8 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/Reflection/BetterReflection/BetterReflectionProvider.php(247): PHPStan\\Reflection\\BetterReflection\\BetterReflectionProvider->resolveName(Object(PhpParser\\Node\\Name), Object(Closure), NULL)
#9 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/Reflection/BetterReflection/BetterReflectionProvider.php(230): PHPStan\\Reflection\\BetterReflection\\BetterReflectionProvider->resolveConstantName(Object(PhpParser\\Node\\Name), NULL)
#10 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/Type/Php/FilterVarDynamicReturnTypeExtension.php(52): PHPStan\\Reflection\\BetterReflection\\BetterReflectionProvider->getConstant(Object(PhpParser\\Node\\Name), NULL)
#11 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/Type/Php/FilterVarDynamicReturnTypeExtension.php(41): PHPStan\\Type\\Php\\FilterVarDynamicReturnTypeExtension->getConstant('FILTER_UNSAFE_R...')
#12 /private/var/folders/vm/xt8_93f91qxb319cskfgdvzh0000gn/T/phpstan/cache/nette.configurator/Container_1d2dbb4858.php(4035): PHPStan\\Type\\Php\\FilterVarDynamicReturnTypeExtension->__construct(Object(PHPStan\\Reflection\\BetterReflection\\BetterReflectionProvider))
#13 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/nette/di/src/DI/Container.php(157): Container_1d2dbb4858->createService0127()
#14 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/nette/di/src/DI/Container.php(90): _HumbugBox37da87c0ed2f\\Nette\\DI\\Container->createService('0127')
#15 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/DependencyInjection/Nette/NetteContainer.php(28): _HumbugBox37da87c0ed2f\\Nette\\DI\\Container->getService('0127')
#16 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/DependencyInjection/Nette/NetteContainer.php(83): PHPStan\\DependencyInjection\\Nette\\NetteContainer->getService('0127')
#17 [internal function]: PHPStan\\DependencyInjection\\Nette\\NetteContainer->PHPStan\\DependencyInjection\\Nette\\{closure}('0127')
#18 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/DependencyInjection/Nette/NetteContainer.php(84): array_map(Object(Closure), Array)
#19 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/DependencyInjection/Nette/NetteContainer.php(52): PHPStan\\DependencyInjection\\Nette\\NetteContainer->tagsToServices(Array)
#20 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/DependencyInjection/MemoizingContainer.php(47): PHPStan\\DependencyInjection\\Nette\\NetteContainer->getServicesByTag('phpstan.broker....')
#21 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/Analyser/TypeSpecifierFactory.php(24): PHPStan\\DependencyInjection\\MemoizingContainer->getServicesByTag('phpstan.broker....')
#22 /private/var/folders/vm/xt8_93f91qxb319cskfgdvzh0000gn/T/phpstan/cache/nette.configurator/Container_1d2dbb4858.php(5945): PHPStan\\Analyser\\TypeSpecifierFactory->create()
#23 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/nette/di/src/DI/Container.php(157): Container_1d2dbb4858->createServiceTypeSpecifier()
#24 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/nette/di/src/DI/Container.php(90): _HumbugBox37da87c0ed2f\\Nette\\DI\\Container->createService('typeSpecifier')
#25 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/DependencyInjection/ContainerFactory.php(70): _HumbugBox37da87c0ed2f\\Nette\\DI\\Container->getService('typeSpecifier')
#26 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/DependencyInjection/DerivativeContainerFactory.php(52): PHPStan\\DependencyInjection\\ContainerFactory->create('/var/folders/vm...', Array, Array, Array, Array, Array, '5')
#27 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/PhpDoc/StubValidator.php(67): PHPStan\\DependencyInjection\\DerivativeContainerFactory->create(Array)
#28 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/Command/AnalyseApplication.php(47): PHPStan\\PhpDoc\\StubValidator->validate()
#29 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/Command/AnalyseCommand.php(148): PHPStan\\Command\\AnalyseApplication->analyse(Array, false, Object(PHPStan\\Command\\Symfony\\SymfonyOutput), Object(PHPStan\\Command\\Symfony\\SymfonyOutput), false, true, '/Users/zonghan/...', Object(_HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Input\\ArgvInput))
#30 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/symfony/console/Command/Command.php(228): PHPStan\\Command\\AnalyseCommand->execute(Object(_HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Input\\ArgvInput), Object(_HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Output\\ConsoleOutput))
#31 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/symfony/console/Application.php(852): _HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Command\\Command->run(Object(_HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Input\\ArgvInput), Object(_HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Output\\ConsoleOutput))
#32 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/symfony/console/Application.php(235): _HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Application->doRunCommand(Object(PHPStan\\Command\\AnalyseCommand), Object(_HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Input\\ArgvInput), Object(_HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Output\\ConsoleOutput))
#33 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/symfony/console/Application.php(136): _HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Application->doRun(Object(_HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Input\\ArgvInput), Object(_HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Output\\ConsoleOutput))
#34 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/bin/phpstan(76): _HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Application->run()
#35 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/bin/phpstan(77): _HumbugBox37da87c0ed2f\\{closure}()
#36 /Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan(6): require('phar:///Users/z...')
#37 {main}

[previous exception] [object] (PhpParser\\Error(code: 0): Syntax error, unexpected ',' on line 7 on unknown line at phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/Parser/PhpParserDecorator.php:25)
[stacktrace]
#0 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Ast/Locator.php(53): PHPStan\\Parser\\PhpParserDecorator->parse('<?php\
\
/**\
 * I...')
#1 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Ast/Locator.php(41): _HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\SourceLocator\\Ast\\Locator->findReflectionsOfType(Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Reflector\\ClassReflector), Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\SourceLocator\\Located\\InternalLocatedSource), Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Identifier\\IdentifierType))
#2 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Type/AbstractSourceLocator.php(43): _HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\SourceLocator\\Ast\\Locator->findReflection(Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Reflector\\ClassReflector), Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\SourceLocator\\Located\\InternalLocatedSource), Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Identifier\\Identifier))
#3 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Type/AggregateSourceLocator.php(31): _HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\SourceLocator\\Type\\AbstractSourceLocator->locateIdentifier(Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Reflector\\ClassReflector), Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Identifier\\Identifier))
#4 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Type/MemoizingSourceLocator.php(31): _HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\SourceLocator\\Type\\AggregateSourceLocator->locateIdentifier(Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Reflector\\ClassReflector), Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Identifier\\Identifier))
#5 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/ondrejmirtes/better-reflection/src/Reflector/ConstantReflector.php(34): _HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\SourceLocator\\Type\\MemoizingSourceLocator->locateIdentifier(Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Reflector\\ClassReflector), Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Identifier\\Identifier))
#6 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/Reflection/BetterReflection/BetterReflectionProvider.php(249): _HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Reflector\\ConstantReflector->reflect('FILTER_UNSAFE_R...')
#7 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/Reflection/BetterReflection/BetterReflectionProvider.php(274): PHPStan\\Reflection\\BetterReflection\\BetterReflectionProvider->PHPStan\\Reflection\\BetterReflection\\{closure}('FILTER_UNSAFE_R...')
#8 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/Reflection/BetterReflection/BetterReflectionProvider.php(247): PHPStan\\Reflection\\BetterReflection\\BetterReflectionProvider->resolveName(Object(PhpParser\\Node\\Name), Object(Closure), NULL)
#9 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/Reflection/BetterReflection/BetterReflectionProvider.php(230): PHPStan\\Reflection\\BetterReflection\\BetterReflectionProvider->resolveConstantName(Object(PhpParser\\Node\\Name), NULL)
#10 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/Type/Php/FilterVarDynamicReturnTypeExtension.php(52): PHPStan\\Reflection\\BetterReflection\\BetterReflectionProvider->getConstant(Object(PhpParser\\Node\\Name), NULL)
#11 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/Type/Php/FilterVarDynamicReturnTypeExtension.php(41): PHPStan\\Type\\Php\\FilterVarDynamicReturnTypeExtension->getConstant('FILTER_UNSAFE_R...')
#12 /private/var/folders/vm/xt8_93f91qxb319cskfgdvzh0000gn/T/phpstan/cache/nette.configurator/Container_1d2dbb4858.php(4035): PHPStan\\Type\\Php\\FilterVarDynamicReturnTypeExtension->__construct(Object(PHPStan\\Reflection\\BetterReflection\\BetterReflectionProvider))
#13 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/nette/di/src/DI/Container.php(157): Container_1d2dbb4858->createService0127()
#14 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/nette/di/src/DI/Container.php(90): _HumbugBox37da87c0ed2f\\Nette\\DI\\Container->createService('0127')
#15 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/DependencyInjection/Nette/NetteContainer.php(28): _HumbugBox37da87c0ed2f\\Nette\\DI\\Container->getService('0127')
#16 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/DependencyInjection/Nette/NetteContainer.php(83): PHPStan\\DependencyInjection\\Nette\\NetteContainer->getService('0127')
#17 [internal function]: PHPStan\\DependencyInjection\\Nette\\NetteContainer->PHPStan\\DependencyInjection\\Nette\\{closure}('0127')
#18 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/DependencyInjection/Nette/NetteContainer.php(84): array_map(Object(Closure), Array)
#19 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/DependencyInjection/Nette/NetteContainer.php(52): PHPStan\\DependencyInjection\\Nette\\NetteContainer->tagsToServices(Array)
#20 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/DependencyInjection/MemoizingContainer.php(47): PHPStan\\DependencyInjection\\Nette\\NetteContainer->getServicesByTag('phpstan.broker....')
#21 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/Analyser/TypeSpecifierFactory.php(24): PHPStan\\DependencyInjection\\MemoizingContainer->getServicesByTag('phpstan.broker....')
#22 /private/var/folders/vm/xt8_93f91qxb319cskfgdvzh0000gn/T/phpstan/cache/nette.configurator/Container_1d2dbb4858.php(5945): PHPStan\\Analyser\\TypeSpecifierFactory->create()
#23 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/nette/di/src/DI/Container.php(157): Container_1d2dbb4858->createServiceTypeSpecifier()
#24 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/nette/di/src/DI/Container.php(90): _HumbugBox37da87c0ed2f\\Nette\\DI\\Container->createService('typeSpecifier')
#25 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/DependencyInjection/ContainerFactory.php(70): _HumbugBox37da87c0ed2f\\Nette\\DI\\Container->getService('typeSpecifier')
#26 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/DependencyInjection/DerivativeContainerFactory.php(52): PHPStan\\DependencyInjection\\ContainerFactory->create('/var/folders/vm...', Array, Array, Array, Array, Array, '5')
#27 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/PhpDoc/StubValidator.php(67): PHPStan\\DependencyInjection\\DerivativeContainerFactory->create(Array)
#28 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/Command/AnalyseApplication.php(47): PHPStan\\PhpDoc\\StubValidator->validate()
#29 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/Command/AnalyseCommand.php(148): PHPStan\\Command\\AnalyseApplication->analyse(Array, false, Object(PHPStan\\Command\\Symfony\\SymfonyOutput), Object(PHPStan\\Command\\Symfony\\SymfonyOutput), false, true, '/Users/zonghan/...', Object(_HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Input\\ArgvInput))
#30 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/symfony/console/Command/Command.php(228): PHPStan\\Command\\AnalyseCommand->execute(Object(_HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Input\\ArgvInput), Object(_HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Output\\ConsoleOutput))
#31 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/symfony/console/Application.php(852): _HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Command\\Command->run(Object(_HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Input\\ArgvInput), Object(_HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Output\\ConsoleOutput))
#32 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/symfony/console/Application.php(235): _HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Application->doRunCommand(Object(PHPStan\\Command\\AnalyseCommand), Object(_HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Input\\ArgvInput), Object(_HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Output\\ConsoleOutput))
#33 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/symfony/console/Application.php(136): _HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Application->doRun(Object(_HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Input\\ArgvInput), Object(_HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Output\\ConsoleOutput))
#34 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/bin/phpstan(76): _HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Application->run()
#35 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/bin/phpstan(77): _HumbugBox37da87c0ed2f\\{closure}()
#36 /Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan(6): require('phar:///Users/z...')
#37 {main}
"} 


```

**Comment by szepeviktor** [comment]
Thank you for your report.
Could you describe what steps lead to this error?

**Comment by zong0828** [comment]
@szepeviktor 
Here is my step. 
1. composer require --dev nunomaduro/larastan
2.setting the neon file
3. ./vendor/bin/phpstan analyse
4. Good !
5. composer require zircote/swagger-php
6. setting the swagger controller and route 
7. ./vendor/bin/phpstan analyse
8. error !

**Comment by szepeviktor** [comment]
>     setting the swagger controller and route

What if you miss this step?

**Comment by canvural** [comment]
Hi,

https://github.com/zircote/swagger-php has caused some trouble before with PHPStan. It was the mistake of the package. So maybe there is something wrong again. Please open an issue there or in PHPStan repo.

Thank you.

**Comment by szepeviktor** [comment]
You're welcome.
