### ISSUE TITLE
Model::find() return type

### ISSUE THREAD

**Issue by b1rdex** [nunomaduro/larastan#930]
- Larastan Version: 0.7.12
- laravel/framework: v8.60.0
- `--level` used: 5

### Description
I expect `find` to return one of:
1) a model instance (or null) when it's called with a scalar
2) a collection (bound with a given model class) when it's called with an array (or Arrayable)

### Laravel code where the issue was found

```php
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

/**
 * @mixin Builder
 */
class Station extends Model
{}

$station = Station::find(1);
\PHPStan\dumpType($station);

// Dumped type: Illuminate\Database\Eloquent\Collection<Illuminate\Database\Eloquent\Model>|Illuminate\Database\Eloquent\Model|null
```

**Comment by b1rdex** [comment]
```php
$station = Station::find([1,2]);
\PHPStan\dumpType($station);

// Internal error: Method newCollection() was not found in reflection of class Illuminate\Database\Eloquent\Builder.
```

```
Uncaught PHPStan\Reflection\MissingMethodFromReflectionException: Method newCollection() was not found in reflection of class Illuminate\Database\Eloquent\Builder. in phar:///Users/anatoly/PhpstormProjects/amo-back/www/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ClassReflection.php:338
#0 /Users/anatoly/PhpstormProjects/amo-back/www/vendor/nunomaduro/larastan/src/Methods/BuilderHelper.php(207): PHPStan\Reflection\ClassReflection->getNativeMethod('newCollection')
#1 /Users/anatoly/PhpstormProjects/amo-back/www/vendor/nunomaduro/larastan/src/ReturnTypes/ModelFindExtension.php(88): NunoMaduro\Larastan\Methods\BuilderHelper->determineCollectionClassName('Illuminate\\Data...')
#2 phar:///Users/anatoly/PhpstormProjects/amo-back/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(3270): NunoMaduro\Larastan\ReturnTypes\ModelFindExtension->getTypeFromStaticMethodCall(Object(PHPStan\Reflection\ResolvedMethodReflection), Object(PhpParser\Node\Expr\StaticCall), Object(NunoMaduro\Larastan\Analyser\Scope))
#3 phar:///Users/anatoly/PhpstormProjects/amo-back/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1534): PHPStan\Analyser\MutatingScope->methodCallReturnType(Object(PHPStan\Type\ObjectType), 'find', Object(PhpParser\Node\Expr\StaticCall))
#4 phar:///Users/anatoly/PhpstormProjects/amo-back/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1540): PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}()
#5 phar:///Users/anatoly/PhpstormProjects/amo-back/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(443): PHPStan\Analyser\MutatingScope->resolveType(Object(PhpParser\Node\Expr\StaticCall))
#6 /Users/anatoly/PhpstormProjects/amo-back/www/vendor/nunomaduro/larastan/src/Analyser/Scope.php(35): PHPStan\Analyser\MutatingScope->getType(Object(PhpParser\Node\Expr\StaticCall))
#7 phar:///Users/anatoly/PhpstormProjects/amo-back/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(699): NunoMaduro\Larastan\Analyser\Scope->getType(Object(PhpParser\Node\Expr\StaticCall))
#8 phar:///Users/anatoly/PhpstormProjects/amo-back/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(443): PHPStan\Analyser\MutatingScope->resolveType(Object(PhpParser\Node\Expr\Assign))
#9 /Users/anatoly/PhpstormProjects/amo-back/www/vendor/nunomaduro/larastan/src/Analyser/Scope.php(35): PHPStan\Analyser\MutatingScope->getType(Object(PhpParser\Node\Expr\Assign))
#10 phar:///Users/anatoly/PhpstormProjects/amo-back/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1344): NunoMaduro\Larastan\Analyser\Scope->getType(Object(PhpParser\Node\Expr\Assign))
#11 phar:///Users/anatoly/PhpstormProjects/amo-back/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(459): PHPStan\Analyser\NodeScopeResolver->findEarlyTerminatingExpr(Object(PhpParser\Node\Expr\Assign), Object(NunoMaduro\Larastan\Analyser\Scope))
#12 phar:///Users/anatoly/PhpstormProjects/amo-back/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(258): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Expression), Object(NunoMaduro\Larastan\Analyser\Scope), Object(Closure))
#13 phar:///Users/anatoly/PhpstormProjects/amo-back/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(423): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\ClassMethod), Array, Object(NunoMaduro\Larastan\Analyser\Scope), Object(Closure))
#14 phar:///Users/anatoly/PhpstormProjects/amo-back/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(258): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\ClassMethod), Object(NunoMaduro\Larastan\Analyser\Scope), Object(PHPStan\Node\ClassStatementsGatherer))
#15 phar:///Users/anatoly/PhpstormProjects/amo-back/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(507): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Class_), Array, Object(NunoMaduro\Larastan\Analyser\Scope), Object(PHPStan\Node\ClassStatementsGatherer))
#16 phar:///Users/anatoly/PhpstormProjects/amo-back/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(258): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Class_), Object(NunoMaduro\Larastan\Analyser\Scope), Object(Closure))
#17 phar:///Users/anatoly/PhpstormProjects/amo-back/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(473): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Namespace_), Array, Object(NunoMaduro\Larastan\Analyser\Scope), Object(Closure))
#18 phar:///Users/anatoly/PhpstormProjects/amo-back/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(226): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Namespace_), Object(NunoMaduro\Larastan\Analyser\Scope), Object(Closure))
#19 phar:///Users/anatoly/PhpstormProjects/amo-back/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(149): PHPStan\Analyser\NodeScopeResolver->processNodes(Array, Object(NunoMaduro\Larastan\Analyser\Scope), Object(Closure))
#20 phar:///Users/anatoly/PhpstormProjects/amo-back/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/Analyser.php(52): PHPStan\Analyser\FileAnalyser->analyseFile('/Users/anatoly/...', Array, Object(PHPStan\Rules\Registry), NULL)
#21 phar:///Users/anatoly/PhpstormProjects/amo-back/www/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyserRunner.php(56): PHPStan\Analyser\Analyser->analyse(Array, Object(Closure), NULL, true, Array)
#22 phar:///Users/anatoly/PhpstormProjects/amo-back/www/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseApplication.php(148): PHPStan\Command\AnalyserRunner->runAnalyser(Array, Array, Object(Closure), NULL, true, true, '/Users/anatoly/...', NULL, NULL, Object(_PHPStan_0ebfea013\Symfony\Component\Console\Input\ArgvInput))
#23 phar:///Users/anatoly/PhpstormProjects/amo-back/www/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseApplication.php(79): PHPStan\Command\AnalyseApplication->runAnalyser(Array, Array, true, '/Users/anatoly/...', Object(PHPStan\Command\Symfony\SymfonyOutput), Object(PHPStan\Command\Symfony\SymfonyOutput), Object(_PHPStan_0ebfea013\Symfony\Component\Console\Input\ArgvInput))
#24 phar:///Users/anatoly/PhpstormProjects/amo-back/www/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseCommand.php(157): PHPStan\Command\AnalyseApplication->analyse(Array, true, Object(PHPStan\Command\Symfony\SymfonyOutput), Object(PHPStan\Command\Symfony\SymfonyOutput), false, true, '/Users/anatoly/...', Array, Object(_PHPStan_0ebfea013\Symfony\Component\Console\Input\ArgvInput))
#25 phar:///Users/anatoly/PhpstormProjects/amo-back/www/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(228): PHPStan\Command\AnalyseCommand->execute(Object(_PHPStan_0ebfea013\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_0ebfea013\Symfony\Component\Console\Output\ConsoleOutput))
#26 phar:///Users/anatoly/PhpstormProjects/amo-back/www/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(856): _PHPStan_0ebfea013\Symfony\Component\Console\Command\Command->run(Object(_PHPStan_0ebfea013\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_0ebfea013\Symfony\Component\Console\Output\ConsoleOutput))
#27 phar:///Users/anatoly/PhpstormProjects/amo-back/www/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(237): _PHPStan_0ebfea013\Symfony\Component\Console\Application->doRunCommand(Object(PHPStan\Command\AnalyseCommand), Object(_PHPStan_0ebfea013\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_0ebfea013\Symfony\Component\Console\Output\ConsoleOutput))
#28 phar:///Users/anatoly/PhpstormProjects/amo-back/www/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(138): _PHPStan_0ebfea013\Symfony\Component\Console\Application->doRun(Object(_PHPStan_0ebfea013\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_0ebfea013\Symfony\Component\Console\Output\ConsoleOutput))
#29 phar:///Users/anatoly/PhpstormProjects/amo-back/www/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(82): _PHPStan_0ebfea013\Symfony\Component\Console\Application->run()
#30 phar:///Users/anatoly/PhpstormProjects/amo-back/www/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(83): _PHPStan_0ebfea013\{closure}()
#31 /Users/anatoly/PhpstormProjects/amo-back/www/vendor/phpstan/phpstan/phpstan(8): require('phar:///Users/a...')
#32 {main}
```

❯ composer info | grep phpstan
nunomaduro/larastan                    v0.7.12            Larastan - Discover bugs in your code without running it. A phpstan/phpstan wrapper for Laravel
phpstan/phpstan                        0.12.98            PHPStan - PHP Static Analysis Tool
phpstan/phpstan-phpunit                0.12.22            PHPUnit extensions and rules for PHPStan
phpstan/phpstan-strict-rules           0.12.11            Extra strict and opinionated rules for PHPStan

Phpstan config:
```
includes:
    - ./vendor/nunomaduro/larastan/extension.neon
    - phpstan-baseline.neon
rules:
parameters:
    tmpDir: /tmp/phpstan
    paths:
        - app

    # The level 8 is the highest level
    level: 5

    checkMissingIterableValueType: false
    reportUnmatchedIgnoredErrors: false
    ignoreErrors:
        - '#Unsafe usage of new static#'
```

**Comment by szepeviktor** [comment]
Very interesting!
Thank you for your bug report.

**Comment by canvural** [comment]
Hi,

Inferring return type of `find` already works as you described and it's correct. So the issue must be in your setup.

I think 

```
/**
 * @mixin Builder
 */
```

can cause the issues. Can you remove it and try again?

**Comment by b1rdex** [comment]
Removing the mixin breaks PhpStorm code completion - it says there is no ‘find’ method found. 

Отправлено с iPhone

**Comment by canvural** [comment]
@b1rdex But does the static analysis error go away?

**Comment by b1rdex** [comment]
Yes, removing the mixin solves the problem. But, IMO, it should be fixed somehow to allow having the mixin present – it's generated by https://github.com/barryvdh/laravel-ide-helper and adds PhpStorm code completion support.

**Comment by szepeviktor** [comment]
e.g. VSCode became PHPStan-friendly
https://github.com/bmewburn/vscode-intelephense
I hope PhpStorm will follow!

**Comment by b1rdex** [comment]
I don't get why you closed the issue. PhpStorm supports Psalm/PHPStan generic templates and other basic SCA-helping syntax. But that isn't related to reading stubs from larastan plugin at all :-) And I don't see any possible way for it to improve that.

I assume you guys use Laravel in your project – how do your models look like?
I understand that `class Station extends Model {}` is enough for Laravel itself, but that's not usable at all.

**Comment by szepeviktor** [comment]
BTW "laravel-ide-helper" has "helper" in its name. An IDE should be capable (or extendable) to understand frameworks.

Are you looking for the "Laravel Idea" plugin?

**Comment by b1rdex** [comment]
I have https://plugins.jetbrains.com/plugin/7532-laravel installed and enabled, but it depends on the helper I mentioned above

**Comment by szepeviktor** [comment]
laravel-ide-helper is for non-Laravel-capable IDE-s. Please understand that.
I hope PhpStorm will get better at Laravel, will be capable understanding Laravel without source code modification!
