### ISSUE TITLE
"Package 'sentry/sentry' is not installed" error in BitBucket Pipelines

### ISSUE THREAD

**Issue by yoX64** [nunomaduro/larastan#966]
- Larastan Version: 0.7.13
- `--level` used: 0

### Description
`Package "sentry/sentry" is not installed` is the error I'm getting when I run `php vendor/bin/phpstan analyze --memory-limit=2G --debug` in Bitbucket Pipelines. Locally, in Docker, is working.

#### BitBucket Pipelines step config
```yaml
- step:
          name: Check Code Analysis
          size: 2x
          script:
            - apt-get -y update
            - apt-get install -y libzip-dev libicu-dev zip libfreetype6-dev libjpeg62-turbo-dev git
            - docker-php-ext-install zip
            - docker-php-ext-configure intl
            - docker-php-ext-install intl
            - docker-php-ext-install pcntl
            - docker-php-ext-install pdo_mysql
            - docker-php-ext-configure gd
            - docker-php-ext-install -j$(nproc) gd
            - ./composer install
            - php vendor/bin/phpstan analyze --memory-limit=2G --debug
```

#### PHPStan config file
```neon
includes:
    - ./vendor/nunomaduro/larastan/extension.neon

parameters:
    noUnnecessaryCollectionCall: false
    parallel:
        maximumNumberOfProcesses: 1
    level: 0
    paths:
        - app
        - config
        - database
        - routes
```

#### The error trace
```
+ php vendor/bin/phpstan analyze --memory-limit=2G --debug
Note: Using configuration file /opt/atlassian/pipelines/agent/build/phpstan.neon.
OutOfBoundsException thrown in phar:///opt/atlassian/pipelines/agent/build/vendor/phpstan/phpstan/phpstan.phar/vendor/composer/InstalledVersions.php on line 188 
while loading bootstrap file /opt/atlassian/pipelines/agent/build/vendor/nunomaduro/larastan/bootstrap.php: 
Package "sentry/sentry" is not installed

#0 /opt/atlassian/pipelines/agent/build/vendor/composer/package-versions-deprecated/src/PackageVersions/Versions.php(329): Composer\InstalledVersions::getPrettyVersion('sentry/sentry')
#1 /opt/atlassian/pipelines/agent/build/vendor/jean85/pretty-package-versions/src/PrettyVersions.php(13): PackageVersions\Versions::getVersion('sentry/sentry')
#2 /opt/atlassian/pipelines/agent/build/vendor/sentry/sentry/src/ClientBuilder.php(79): Jean85\PrettyVersions::getVersion('sentry/sentry')
#3 /opt/atlassian/pipelines/agent/build/vendor/sentry/sentry/src/ClientBuilder.php(87): Sentry\ClientBuilder->__construct(Object(Sentry\Options))
#4 /opt/atlassian/pipelines/agent/build/vendor/sentry/sentry-laravel/src/Sentry/Laravel/ServiceProvider.php(157): Sentry\ClientBuilder::create(Array)
#5 /opt/atlassian/pipelines/agent/build/vendor/laravel/framework/src/Illuminate/Container/Container.php(869): Sentry\Laravel\ServiceProvider->Sentry\Laravel\{closure}(Object(Illuminate\Foundation\Application), Array)
#6 /opt/atlassian/pipelines/agent/build/vendor/laravel/framework/src/Illuminate/Container/Container.php(754): Illuminate\Container\Container->build(Object(Closure))
#7 /opt/atlassian/pipelines/agent/build/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\Container\Container->resolve('Sentry\\ClientBu...', Array, true)
#8 /opt/atlassian/pipelines/agent/build/vendor/laravel/framework/src/Illuminate/Container/Container.php(692): Illuminate\Foundation\Application->resolve('Sentry\\ClientBu...', Array)
#9 /opt/atlassian/pipelines/agent/build/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(826): Illuminate\Container\Container->make('Sentry\\ClientBu...', Array)
#10 /opt/atlassian/pipelines/agent/build/vendor/sentry/sentry-laravel/src/Sentry/Laravel/ServiceProvider.php(168): Illuminate\Foundation\Application->make('Sentry\\ClientBu...')
#11 /opt/atlassian/pipelines/agent/build/vendor/laravel/framework/src/Illuminate/Container/Container.php(869): Sentry\Laravel\ServiceProvider->Sentry\Laravel\{closure}(Object(Illuminate\Foundation\Application), Array)
#12 /opt/atlassian/pipelines/agent/build/vendor/laravel/framework/src/Illuminate/Container/Container.php(754): Illuminate\Container\Container->build(Object(Closure))
#13 /opt/atlassian/pipelines/agent/build/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\Container\Container->resolve('Sentry\\State\\Hu...', Array, true)
#14 /opt/atlassian/pipelines/agent/build/vendor/laravel/framework/src/Illuminate/Container/Container.php(692): Illuminate\Foundation\Application->resolve('Sentry\\State\\Hu...', Array)
#15 /opt/atlassian/pipelines/agent/build/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(826): Illuminate\Container\Container->make('Sentry\\State\\Hu...', Array)
#16 /opt/atlassian/pipelines/agent/build/vendor/sentry/sentry-laravel/src/Sentry/Laravel/ServiceProvider.php(44): Illuminate\Foundation\Application->make('Sentry\\State\\Hu...')
#17 /opt/atlassian/pipelines/agent/build/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Sentry\Laravel\ServiceProvider->boot()
#18 /opt/atlassian/pipelines/agent/build/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#19 /opt/atlassian/pipelines/agent/build/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#20 /opt/atlassian/pipelines/agent/build/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#21 /opt/atlassian/pipelines/agent/build/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#22 /opt/atlassian/pipelines/agent/build/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(914): Illuminate\Container\Container->call(Array)
#23 /opt/atlassian/pipelines/agent/build/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(895): Illuminate\Foundation\Application->bootProvider(Object(Sentry\Laravel\ServiceProvider))
#24 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(Sentry\Laravel\ServiceProvider), 34)
#25 /opt/atlassian/pipelines/agent/build/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(896): array_walk(Array, Object(Closure))
#26 /opt/atlassian/pipelines/agent/build/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#27 /opt/atlassian/pipelines/agent/build/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#28 /opt/atlassian/pipelines/agent/build/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\Foundation\Application->bootstrapWith(Array)
#29 /opt/atlassian/pipelines/agent/build/vendor/nunomaduro/larastan/bootstrap.php(24): Illuminate\Foundation\Console\Kernel->bootstrap()
#30 phar:///opt/atlassian/pipelines/agent/build/vendor/phpstan/phpstan/phpstan.phar/src/Command/CommandHelper.php(358): require_once('/opt/atlassian/...')
#31 phar:///opt/atlassian/pipelines/agent/build/vendor/phpstan/phpstan/phpstan.phar/src/Command/CommandHelper.php(359): PHPStan\Command\CommandHelper::PHPStan\Command\{closure}('/opt/atlassian/...')
#32 phar:///opt/atlassian/pipelines/agent/build/vendor/phpstan/phpstan/phpstan.phar/src/Command/CommandHelper.php(298): PHPStan\Command\CommandHelper::executeBootstrapFile('/opt/atlassian/...', Object(PHPStan\DependencyInjection\MemoizingContainer), Object(PHPStan\Command\Symfony\SymfonyOutput), true)
#33 phar:///opt/atlassian/pipelines/agent/build/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseCommand.php(81): PHPStan\Command\CommandHelper::begin(Object(_PHPStan_76800bfb5\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_76800bfb5\Symfony\Component\Console\Output\ConsoleOutput), Array, NULL, '2G', NULL, Array, '/opt/atlassian/...', NULL, '0', false, true, true)
#34 phar:///opt/atlassian/pipelines/agent/build/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(228): PHPStan\Command\AnalyseCommand->execute(Object(_PHPStan_76800bfb5\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_76800bfb5\Symfony\Component\Console\Output\ConsoleOutput))
#35 phar:///opt/atlassian/pipelines/agent/build/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(856): _PHPStan_76800bfb5\Symfony\Component\Console\Command\Command->run(Object(_PHPStan_76800bfb5\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_76800bfb5\Symfony\Component\Console\Output\ConsoleOutput))
#36 phar:///opt/atlassian/pipelines/agent/build/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(237): _PHPStan_76800bfb5\Symfony\Component\Console\Application->doRunCommand(Object(PHPStan\Command\AnalyseCommand), Object(_PHPStan_76800bfb5\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_76800bfb5\Symfony\Component\Console\Output\ConsoleOutput))
#37 phar:///opt/atlassian/pipelines/agent/build/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(138): _PHPStan_76800bfb5\Symfony\Component\Console\Application->doRun(Object(_PHPStan_76800bfb5\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_76800bfb5\Symfony\Component\Console\Output\ConsoleOutput))
#38 phar:///opt/atlassian/pipelines/agent/build/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(82): _PHPStan_76800bfb5\Symfony\Component\Console\Application->run()
#39 phar:///opt/atlassian/pipelines/agent/build/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(83): _PHPStan_76800bfb5\{closure}()
#40 /opt/atlassian/pipelines/agent/build/vendor/phpstan/phpstan/phpstan(8): require('phar:///opt/atl...')
#41 {main}
```

As you can see in the trace, there seems to be an issue with the paths. The code is trying to find `sentry/sentry` in the `phpstan` library, not in my codebase.

Any ideas on how to fix this?

**Comment by warmwhisky** [comment]
> Hi,
> 
> Please check [this](https://github.com/phpstan/phpstan/issues/4482#issuecomment-771474006) comment, it explains everything for you to solve the issue.
> 
> If it still happens, please remove the `includes: - ./vendor/nunomaduro/larastan/extension.neon` part from your PHPStan config, and run again. If the issue still happens, as a last chance you can try to open issue/discussion in PHPStan repo.

This fixed it for me. Thanks
